### ISSUE TITLE
already expired certs are not refreshed instantly

### ISSUE THREAD

**Issue by RezzZ** [linuxserver/docker-swag#100]
Expected Behavior
I closed my ports and only refresh certs when they are about to expire. this time I was too late. certs already expired and swag is not updating them.

Current Behavior
Certs are not instantly refreshed, even after restart of the container

Steps to Reproduce
Environment
OS: CPU architecture: x86_64/arm32/arm64 How docker service was installed:
Running swag: latest and just updated today so version would be 1.13.0
On Centos8, x64, using docker-compose

Command used to create docker container (run/create/compose/screenshot)
Docker logs
```
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
```
Although true the check should not only be if they are about to expire but if they are already expired as well.

**Comment by aptalca** [comment]
It _does_ check if they're already expired

**Comment by RezzZ** [comment]
hmm thats weird, all my proxy conf domains are expired. the root and R3 certificates are updated. any way to force update certs of my subdomains?

**Comment by aptalca** [comment]
> all my proxy conf domains are expired. the root and R3 certificates are updated

I don't follow

**Comment by RezzZ** [comment]
Sorry for my poor explanation, I'm still new to this ssl stuff.
I have setup several subdomains like ha.mydomain.com, portainer.mydomain.com via the proxy confs.
all certs were created without problem but they expired today.
When looking at the certificates inside chrome I see 2 valid certs above my subdomain:
'DST Root CA X3' and 'R3', and they last till end of september this year. But all subdomains were not updated

**Comment by aptalca** [comment]
Try `docker exec -it swag openssl x509 -in /config/keys/letsencrypt/fullchain.pem -noout -dates` on host and it will show you the expiration date
