### ISSUE TITLE
Skipping the "chown" at container startup?

### ISSUE THREAD

**Issue by arjones85** [linuxserver/docker-swag#101]
Hello,

Is there a way of preventing the container from running the "chown abc:abc....." command at start? All my files will already have the correct permissions, and I am serving over a million of them with this container. Startup takes an obscene amount of time because of the unnecessary chown.

Thanks for the help!

**Comment by j0nnymoe** [comment]
No this isn't an option. I would argue that if your files already had the correct permissions, the chown wouldn't run.
Marked as invalid as issue template wasn't completed, if you provide the info we asked for, we can help on this further.

**Comment by aptalca** [comment]
Chown is only done on /config so you can put your files in a folder mapped to something else like /mywebsite and set the root directive in nginx config accordingly

**Comment by arjones85** [comment]
> Chown is only done on /config so you can put your files in a folder mapped to something else like /mywebsite and set the root directive in nginx config accordingly

This was helpful, I hadn't thought about doing it that way. Thank you!


> No this isn't an option. I would argue that if your files already had the correct permissions, the chown wouldn't run.

You would be making an invalid argument. It runs regardless of what the permissions already are on the files :-)

Issue resolved by moving www folder outside of config. Closing issue. Thanks!
