### ISSUE TITLE
ipv6 not working after recent update

### ISSUE THREAD

**Issue by trasba** [linuxserver/docker-swag#103]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

ipv6 working (binding to port 80/443 on ipv6 host interface)

## Current Behavior

ipv6 not working

## Steps to Reproduce

1. Run Container
2. check port bindings (e.g. netstat -tlnpa on host) -> not binding port 80 and 443 on ipv6

## Resolution
Hi this is actually not a bug within docker-swag. I actually reasoned with myself whether to post it here or not.  
However it took me a long time to find the reason and I wanted to support others facing the same issue.

This actually happens when using a docker-ce with version >= 20.10.2 the details can be found here:
* https://askubuntu.com/questions/1307626/docker-daemon-does-not-bind-to-tcp6 and
* https://github.com/moby/moby/issues/24379#issuecomment-569082209

possible work arounds are:
* install a docker-ce version < 20.10.2, this can be done by:
finding a suitable version from rep with: ```apt-cache madison docker-ce```
* move the ports and proxy the ipv6 ports to the moved ports e.g. with 6tunnel or socat

## Remark
Hope this will help someone in need.
*Cheers*

**Comment by drizuid** [comment]
thanks for providing the info. Unfortunately we provide NO support for ipv6 at all. On another note, I do use ipv6 in my swag container and it works perfectly fine.  Will close this as unsupported, but it seems you found the issue was upstream anyway.
