### ISSUE TITLE
Fearure request: generate separate SSL certificates

### ISSUE THREAD

**Issue by evanre** [linuxserver/docker-swag#113]
## Desired Behavior
Generate SSL certificates separately for domains (at least for EXTRA_DOMAINS)

## Current Behavior
A single SSL certificate generates for all the domains listed in config. It's okay for internal or personal domains, but it's not very good for others, every user of every such domains can open the certificate and see the list of all domains on this server.

## Alternatives Considered
I tried to implement a custom script which would generate certificates for a list of domains in some custom env var (lets say SEPARATE_DOMAINS) but the problem that the main script wipes certbot's directory (including live one which is actually stores all the generated certs) and moving them from this directory gets a very difficult to manage (or renew) this custom certificates.

It's actually a problem for me, because I maintain a couple of websites for my clients (I'm a web developer). So the only way I see at the moment is to switch to docker-nginx image. But the effort to write a custom script which would handle build certbot, generate and renew certs seems huge for me at the moment. Much appreciate for any thoughts.

**Comment by j0nnymoe** [comment]
At this time, no plans to add this. It's been discussed in in various other issues https://github.com/linuxserver/docker-swag/issues/33 .
