### ISSUE TITLE
where to specify MAXMINDDB_LICENSE_KEY later if I didn't do initially 

### ISSUE THREAD

**Issue by AlexBGoode** [linuxserver/docker-swag#117]
Hello folks

Please kindly advise where I can specify MAXMINDDB_LICENSE_KEY parameter if I didn't do it initially.
I am very happy with that container using it along with my instance of home assistant and it does everything perfectly.
But at the beginning I didn't care of GoiIP filtering, now I requested the license key and... have no idea where to edit a corresponding config file

docker run -d \
  --name=swag \
  --cap-add=NET_ADMIN \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e URL=yourdomain.url \
  -e SUBDOMAINS=www, \
  -e VALIDATION=http \
  -e CERTPROVIDER= `#optional` \
  -e DNSPLUGIN=cloudflare `#optional` \
  -e PROPAGATION= `#optional` \
  -e DUCKDNSTOKEN= `#optional` \
  -e EMAIL= `#optional` \
  -e ONLY_SUBDOMAINS=false `#optional` \
  -e EXTRA_DOMAINS= `#optional` \
  -e STAGING=false `#optional` \
###   -e MAXMINDDB_LICENSE_KEY= `#optional` \
  -p 443:443 \
  -p 80:80 `#optional` \
  -v /path/to/appdata/config:/config \
  --restart unless-stopped \
  linuxserver/swag

**Comment by aptalca** [comment]
Recreate the container with the updated docker run. Set the maxmind bit, keep everything else the same.

**Comment by AlexBGoode** [comment]
Yes, probably the re-creation (rm & run again) is the only way to fix it.  I hoped there was a graceful way to edit an existing config somewhere within docker's backend... okay, solved the problem at least this way!
