### ISSUE TITLE
Updating Nginx to 1.19.4

### ISSUE THREAD

**Issue by Sanderluc5** [linuxserver/docker-swag#118]
Is it possible to update Nginx to a newer version?

For a project I'm currently working at I need to have access to a function that's only included in the 1.19.4 version of nginx:
http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_reject_handshake.

**Comment by aptalca** [comment]
No, we pull the stable releases from alpine repo

**Comment by tobbenb** [comment]
We use the package in the alpine repo, so once it's updated there, we'll build a new container with the updated version.

**Comment by Sanderluc5** [comment]
Ok. Good to know.

I currently have changed my /etc/apk/repositories to the edge branch.
Now I'm running version 1.12.0 so far so good.
