### ISSUE TITLE
DH params job failing for several weeks

### ISSUE THREAD

**Issue by mambocab** [linuxserver/docker-swag#119]
Not a bug in the container but in the infra: the dhparams Jenkins job mentioned in the docs [has been failing for several weeks](https://ci.linuxserver.io/blue/organizations/jenkins/Xtras-Builders-Etc%2Fdhparams-uploader/activity/). This seems worth fixing soon.

Apologies if this isn't the right place for this bug report. This is just the best place I know of. Thank you!

**Comment by aptalca** [comment]
Thanks for the heads up. But we are switching to the predefined ffdhe4096 per rfc7919, so we won't be using the dhparams builder job anymore.
