### ISSUE TITLE
DNS Plugin inwx renewal failing

### ISSUE THREAD

**Issue by webermar** [linuxserver/docker-swag#120]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Swag is not renewing via inwx dns plugin. I didn't change any config, it worked beforehand, but it seems to be unable to find the credentials for inwx now.
I checked via docker exec and looked from inside the container, everything is where it should be.

------------------------------

## Expected Behavior
Renew LE cert via dns-inwx plugin

## Current Behavior
Failing LE Cert renewal

## Steps to Reproduce
use DNS plugin
edit app/dns-conf/inwx.ini
provide credentials
restart container

inwx.ini content is, as oGGy990 documented it:

dns_inwx_url                  = https://api.domrobot.com/xmlrpc/
dns_inwx_username       = your_username
dns_inwx_password       = """your_password"""
dns_inwx_shared_secret = your_shared_secret optional

## Environment
**OS: Ubuntu Server**
**CPU architecture:** x86_64
**How docker service was installed:**
official docker

## Docker logs
Cert is due for renewal, auto-renewing...
Plugin legacy name certbot-dns-inwx:dns-inwx may be removed in a future version. Please use dns-inwx instead.
Plugins selected: Authenticator certbot-dns-inwx:dns-inwx, Installer None
Renewing an existing certificate for *.xxx.tld and 5 more domains
Performing the following challenges:
dns-01 challenge for xxx.de
dns-01 challenge for xxx.de
dns-01 challenge for xxx.de
dns-01 challenge for xxx.de
dns-01 challenge for xxx.de
dns-01 challenge for xxx.de
Cleaning up challenges
Failed to renew certificate xxx.de with error: Missing properties in credentials configuration file /config/dns-conf/inwx.ini:
 * Property "certbot_dns_inwx:dns_inwx_url" not found (should be URL of the INWX XML-RPC API to use.).
 * Property "certbot_dns_inwx:dns_inwx_username" not found (should be Username of the INWX API account.).
 * Property "certbot_dns_inwx:dns_inwx_password" not found (should be Password of the INWX API account.).
 * Property "certbot_dns_inwx:dns_inwx_shared_secret" not found (should be Optional shared secret code for the two-factor authentication assigned to the INWX API account.).

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/xxx/fullchain.pem (failure)

**Comment by webermar** [comment]
Found a solution:
Take the output literally:
Edit the inwx.ini
Remove Comments.
Add "certbot_dns_inwx:" before every key:

certbot_dns_inwx:dns_inwx_url = https://api.domrobot.com/xmlrpc/
certbot_dns_inwx:dns_inwx_username = your_username
certbot_dns_inwx:dns_inwx_password = your_password
certbot_dns_inwx:dns_inwx_shared_secret = your_shared_secret optional

(do not forget to check 0600 permissions on inwx.ini, otherwise othere people can see your credentials)

I'm assuming this is a bug.

**Comment by Coffeeri** [comment]
> Found a solution:
> Take the output literally:
> Edit the inwx.ini
> Remove Comments.
> Add "certbot_dns_inwx:" before every key:
> 
> certbot_dns_inwx:dns_inwx_url = https://api.domrobot.com/xmlrpc/
> certbot_dns_inwx:dns_inwx_username = your_username
> certbot_dns_inwx:dns_inwx_password = your_password
> certbot_dns_inwx:dns_inwx_shared_secret = your_shared_secret optional
> 
> (do not forget to check 0600 permissions on inwx.ini, otherwise othere people can see your credentials)
> 
> I'm assuming this is a bug.

I can confirm the problem and your solution approach.
One more thing I've noticed to your temporary fix: When restarting the swag container, it automatically removes the "certbot_dns_inwx:"-prefix, so that you'll need to add it before the random back-off time ends.

**Comment by aptalca** [comment]
`Plugin legacy name certbot-dns-inwx:dns-inwx may be removed in a future version. Please use dns-inwx instead.`
This isn't right. We are using the new plugin name, `dns-inwx`: https://github.com/linuxserver/docker-swag/blob/master/root/etc/cont-init.d/50-config#L216-L218

Do you have the latest image?

**Comment by Coffeeri** [comment]
> `Plugin legacy name certbot-dns-inwx:dns-inwx may be removed in a future version. Please use dns-inwx instead.`
> This isn't right. We are using the new plugin name, `dns-inwx`: https://github.com/linuxserver/docker-swag/blob/master/root/etc/cont-init.d/50-config#L216-L218
> 
> Do you have the latest image?

For my part: I have tried the latest image and the issues seems to be resolved.

**Comment by webermar** [comment]
> 
> 
> > `Plugin legacy name certbot-dns-inwx:dns-inwx may be removed in a future version. Please use dns-inwx instead.`
> > This isn't right. We are using the new plugin name, `dns-inwx`: https://github.com/linuxserver/docker-swag/blob/master/root/etc/cont-init.d/50-config#L216-L218
> > Do you have the latest image?
> 
> For my part: I have tried the latest image and the issues seems to be resolved.

Using the latest image (docker pull, no version tag in docker-compose file specified and got okayed that pull) and it isn't solved for me. Excatly the same problem persists. Confusingly, "Plugin legacy name certbot-dns-inwx:dns-inwx may be removed in a future version. Please use dns-inwx instead." persists too. What should I do or change?

**Comment by christianhubmann** [comment]
This problem still persists for me even with the latest image (I am using linuxserver/swag:latest).

As @webermar and @Coffeeri have noted, I have to add certbot_dns_inwx: before every key in inwx.ini, but the prefix is automatically removed every time the container is restarted.

So every few months I have to manually intervene and renew the certificate by hand because not only does the renew fail, it seems that swag/nginx stops forwarding requests when the renew fails.

Here is the output of `/app/le-renew.sh`:
````
Running certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/mydomain.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Plugin legacy name certbot-dns-inwx:dns-inwx may be removed in a future version. Please use dns-inwx instead.
Renewing an existing certificate for *.mydomain.com and mydomain.com
Failed to renew certificate mydomain.com with error: Missing properties in credentials configuration file /config/dns-conf/inwx.ini:
 * Property "certbot_dns_inwx:dns_inwx_url" not found (should be URL of the INWX XML-RPC API to use.).
 * Property "certbot_dns_inwx:dns_inwx_username" not found (should be Username of the INWX API account.).
 * Property "certbot_dns_inwx:dns_inwx_password" not found (should be Password of the INWX API account.).
 * Property "certbot_dns_inwx:dns_inwx_shared_secret" not found (should be Optional shared secret code for the two-factor authentication assigned to the INWX API account.).

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/mydomain.com/fullchain.pem (failure)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
````

The workaround from @webermar (set DNS-plugin to invalid value, delete everything, revert) did not work for me.
