### ISSUE TITLE
OVH DNS plugin broken in version 1.15

### ISSUE THREAD

**Issue by npodbielski** [linuxserver/docker-swag#121]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

In latest version of swag (1.15 in the time of writing) seems like DNS plugin for OVH is broken. It throws an errror instead of generating a correct certificate (for main domain and wildcard subdomains). 
I did not do anything uncommon. I just followed a tutorial from here https://docs.linuxserver.io/general/swag#create-container-via-dns-validation-with-a-wildcard-cert.
I tested it also in previous version (1.14) and it works. So the problem is with latest version.

## Expected Behavior
SWAG should generate correct certificate.

## Current Behavior
After running a swag it spits an error during DNS validation:

swag    | Cleaning up challenges
swag    | Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
swag    | An unexpected error occurred:
swag    | TypeError: create_record() got an unexpected keyword argument 'type'
swag    | Please see the logfiles in /var/log/letsencrypt for more details.

## Steps to Reproduce
1. Prepare SWAG like here https://docs.linuxserver.io/general/swag#create-container-via-dns-validation-with-a-wildcard-cert. 
2. Change DNS plugin to OVH
3. Run it.
4. Stop it
5. Edit ovh credentials file with correct ones
6. It throws an error

## Environment
**Ubuntu server 20.04**
**CPU architecture:** x86_64
**How docker service was installed:**
Via docker-compose following tutorial here:
https://docs.linuxserver.io/general/swag#create-container-via-dns-validation-with-a-wildcard-cert. 

## Command used to create docker container (run/create/compose/screenshot)
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - URL=np0.pl
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=ovh
      - VALIDATION=dns
      - EMAIL={removed}
    volumes:
      - /path/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

## Docker logs

swag    | Cleaning up challenges
swag    | Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
swag    | An unexpected error occurred:
swag    | TypeError: create_record() got an unexpected keyword argument 'type'
swag    | Please see the logfiles in /var/log/letsencrypt for more details.

**Comment by TheSpad** [comment]
Please can you provide the log from /var/log/letsencrypt

**Comment by npodbielski** [comment]
directory log/letsencrypt that is mounted by container is empty. You want me to bash in swag container and get a log from there?

**Comment by TheSpad** [comment]
If the logs are empty in the host mount they'll be empty in the container as well.

Searching around it looks like it might be this issue https://github.com/certbot/certbot/pull/8819

We pull the plugins from pip when we build so once they merge the PR our next build should pick it up.

**Comment by npodbielski** [comment]
Ok. Cool for now 1.14 works fine so at least there is a workaround for time being. Thx.

**Comment by vinceHH** [comment]
Hello,

I can reproduce this issue, exactly the same problem on my system.

**Comment by Roxedus** [comment]
And the answer TheSpad commented still applies

**Comment by Alcolo47** [comment]
After an docker pull, the problem still present in the latest image (ghcr.io/linuxserver/swag       version-1.15.0      a8f797a58012   11 hours ago   351MB)

```
swag_1  | Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword arg│Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be s
ument 'type'                                                                                             │cheduled on the current node.

```

**Comment by TheSpad** [comment]
It will, until they release certbot 1.16 the fix will be missing from our image. Use version-1.14 until that happens.

**Comment by tom967** [comment]
[Certbot 1.16 is released.](https://github.com/certbot/certbot/releases/tag/v1.16.0)

**Comment by Roxedus** [comment]
> [Certbot 1.16 is released.](https://github.com/certbot/certbot/releases/tag/v1.16.0)

Yup, and built 🎉 

@npodbielski can you confirm?

**Comment by tom967** [comment]
This issue is gone for me. @npodbielski may close this.
One more big shoutout for LSIO and certbot !

**Comment by npodbielski** [comment]
Yep. Latest version runs and do not throws an error. Thanks guys! :champagne:
