### ISSUE TITLE
Pls can I manually change the default 80

### ISSUE THREAD

**Issue by sontjer** [linuxserver/docker-swag#122]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by j0nnymoe** [comment]
Please fill out the information we requested in the issue template.
