### ISSUE TITLE
Block Direct Access by Public IP by Default

### ISSUE THREAD

**Issue by thegodsquirrel** [linuxserver/docker-swag#124]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

It would be convenient to have this blocked by default and then have the option to comment it out, if its not a desired behavior.  Leaking the container information for all the scanners in the world to see is not ideal IMHO.  

## Current Behavior

Currently, when I navigate to my public IP via HTTPS I see the "Welcome to your SWAG instance" page.  

## Alternatives Considered

I attempted to use NGINX configs to 404 the page when it is accessed at https://myPublicIP but I do not have a deep understanding of all the configs and how they interact in SWAG. Setting I tried:

if ($host != "example.com") {
 return 404;
}
Does not seem to work in SWAG proxy confs.

If there is a quick fix to this any help would be appreciated.

**Comment by aptalca** [comment]
That's because it's the server block that is designated as `default server` in the nginx conf. If someone accesses your instance by IP directly, or an address not recognized by your server, nginx serves the default server block.

Feel free to modify it however you like. All of those confs are in the config folder.

**Comment by thegodsquirrel** [comment]
Thank you for your concise answer.  I was modifiying the incorrect file.  I needed to put the code I was trying to use in the site-confs/default file in the main server block section for port 443:
if ($host != "example.com") {
return 404;

This produced the intended results.  Thanks again.  
}
