### ISSUE TITLE
Upgrade nginx 1.18 to the latest stable 1.20 version

### ISSUE THREAD

**Issue by Paul6552** [linuxserver/docker-swag#125]
Is it possible to upgrade nginx 1.18 to the latest stable version 1.20?
Nginx has improved a lot in this version especially for httpS-connections.
Thanks

**Comment by TheSpad** [comment]
We pull our packages from the latest stable Alpine repo. When Alpine moves to 1.20 for nginx (probably with 3.14) then we will too.

**Comment by dsm1212** [comment]
@TheSpad Alpine 3.14 is out now and has the updated nginx.

**Comment by Roxedus** [comment]
We are aware, a rebase will happen soon.
