### ISSUE TITLE
PHP 8 ?

### ISSUE THREAD

**Issue by romanvoloboev** [linuxserver/docker-swag#126]
Hi! When PHP 8 will be available?
Latest alpine stable branch has PHP 8.0.6. 
https://pkgs.alpinelinux.org/packages?name=php8&branch=v3.13

So why you don't use it already?

**Comment by aptalca** [comment]
> So why you don't use it already?

Do you want us to break people's production web servers?

**Comment by romanvoloboev** [comment]
> > So why you don't use it already?
> 
> Do you want us to break people's production web servers?

No, you could create separate branch and image for it. Who wants php8 will use it.

**Comment by aptalca** [comment]
PRs welcome

**Comment by romanvoloboev** [comment]
LOL, no thanks.

**Comment by dipodidae** [comment]
I would also really appreciate php 8
