### ISSUE TITLE
ERROR Cert does not exist! although actions performed correctly

### ISSUE THREAD

**Issue by sutidor** [linuxserver/docker-swag#13]
## Expected Behavior
get new cert with dns inwx plugin, no error

## Current Behavior
throws:
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/inwx.ini file.

But certificates are generated, challenge cleaned up, all fine.

I suspect though, that the renewal does not work. 7 days left to expire and no action yet and no new log entries for >2 months now.

## Steps to Reproduce
1. edit inwx.ini file
2. run swag
3. very last log entry is the error
4. container keeps running

## Environment
**OS: Debian** Edit: same behaviour on raspberrypi 4 with raspberry OS     
**CPU architecture:** x86_64
**How docker service was installed:according to docker offical docs**      

## Command used to create docker container (run/create/compose/screenshot)
created in portainer so I post config here

image
linuxserver/swag:latest 	

ports
444->443
81->80

volumes
/etc/letsencrypt -> /etc/letsencrypt
/config:letsencrypt_data

ENV
PGID 	1000
TZ 	Europe/Berlin
URL 	a.b
DNSPLUGIN 	inwx
ONLY_SUBDOMAINS 	true
STAGING 	false
PUID 	1000
VALIDATION 	dns
PATH 	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PS1 	$(whoami)@$(hostname):$(pwd)\$
HOME 	/root
TERM 	xterm
DHLEVEL 	2048
S6_BEHAVIOUR_IF_STAGE2_FAILS 	2
EMAIL 	server@a.b
SUBDOMAINS 	abc
AWS_CONFIG_FILE 	/config/dns-conf/route53.ini

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support the app dev(s) visit:,
Certbot: https://supporters.eff.org/donate/support-work-on-certbot,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-config: executing... ,
[cont-init.d] 20-config: exited 0.,
[cont-init.d] 30-keygen: executing... ,
using keys found in /config/keys,
[cont-init.d] 30-keygen: exited 0.,
[cont-init.d] 50-config: executing... , 

Variables set:

0

0
TZ=Europe/Berlin

l
SUBDOMAINS=abc 
EXTRA_DOMAINS= 
ONLY_SUBDOMAINS=true 
VALIDATION=dns 
DNSPLUGIN=inwx 
EMAIL=server@a.b
STAGING=false 

rm: cannot remove '/etc/letsencrypt': Resource busy 
SUBDOMAINS entered, processing 
SUBDOMAINS entered, processing 
Only subdomains, no URL in cert 
Sub-domains processed are:  -d abc.a.b 
E-mail address entered: server@a.b
dns validation via inwx plugin is selected 
Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created 
nerating new certificate 
Saving debug log to /var/log/letsencrypt/letsencrypt.log 
Plugin legacy name certbot-dns-inwx:dns-inwx may be removed in a future version. Please use dns-inwx instead. 
Plugins selected: Authenticator certbot-dns-inwx:dns-inwx, Installer None 
Obtaining a new certificate 
Performing the following challenges: 
dns-01 challenge for abc.a.b 
Waiting 60 seconds for DNS changes to propagate 
Waiting for verification... 
Cleaning up challenges 
IMPORTANT NOTES: 
 - Congratulations! Your certificate and chain have been saved at: 
   /etc/letsencrypt/live/abc.a.b/fullchain.pem 
   Your key file has been saved at: 
   /etc/letsencrypt/live/abc.a.b/privkey.pem 
   Your cert will expire on 2020-12-20. To obtain a new or tweaked 
   version of this certificate in the future, simply run certbot 
   again. To non-interactively renew *all* of your certificates, run 
   "certbot renew" 
 - Your account credentials have been saved in your Certbot 
   configuration directory at /etc/letsencrypt. You should make a 
   secure backup of this folder now. This configuration directory will 
   also contain certificates and private keys obtained by Certbot so 
   making regular backups of this folder is ideal. 
 - If you like Certbot, please consider supporting our work by: 

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate 
   Donating to EFF:                    https://eff.org/donate-le 

ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/inwx.ini file.

## Letsencrypt Log (last lines)
[...]
/etc/letsencrypt/live/abc.a.b/fullchain.pem
Your key file has been saved at:
/etc/letsencrypt/live/abc.a.b/privkey.pem
Your cert will expire on 2020-12-20. To obtain a new or tweaked version of this certificate in the future, simply run certbot again. To non-interactively renew *all* of your certificates, run "certbot renew"
2020-09-22 00:36:54,284:DEBUG:certbot._internal.reporter:Reporting to user: If you like Certbot, please consider supporting our work by:

Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
Donating to EFF:                    https://eff.org/donate-le

**Comment by drizuid** [comment]
Please try reproducing the error when NOT using portainer. We do not support portainer here as it uses deprecated libcompose and does not work properly. If you are able to reproduce with docker compose or docker create/run, please let us know.

**Comment by sutidor** [comment]
I tried hard to reproduce the error, but all I got was success. Used docker create and docker start.
By the way portainer still shows the image and the logs, so I can use it normally.

Thank you for the rapid help, much appreciated
