### ISSUE TITLE
Can not run after last update

### ISSUE THREAD

**Issue by firebull81** [linuxserver/docker-swag#135]
## Expected Behavior
Normaly run the Docker container

## Current Behavior
Container can't run at all.

## Steps to Reproduce
1. Get latest Docker image
2. Update container to this image
3. Run the container

## Environment
**OS:** Raspbian GNU/Linux 10 (buster)
**CPU architecture:** ARMv7 Processor rev 5 (v7l)
**How docker service was installed:**
From official Docker repo. Using Docker Compose

## Command used to create docker container (run/create/compose/screenshot)
  version: "2.1"
  testing: 
    image: ghcr.io/linuxserver/nginx
    container_name: testing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sofia
    volumes:
      - /mnt/testing:/config
    ports:
      - 8007:80
    restart: unless-stopped

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

chown: changing ownership of '/config': Operation not permitted
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
chown: changing ownership of '/config/nginx/site-confs/default': Operation not permitted
chown: changing ownership of '/config/nginx/site-confs': Operation not permitted
chown: changing ownership of '/config/nginx/nginx.conf': Operation not permitted
chown: changing ownership of '/config/nginx': Operation not permitted
chown: changing ownership of '/config/www/index.html': Operation not permitted
chown: changing ownership of '/config/www': Operation not permitted
chown: changing ownership of '/config/log/nginx': Operation not permitted
chown: changing ownership of '/config/log/php': Operation not permitted
chown: changing ownership of '/config/log': Operation not permitted
chown: changing ownership of '/config/keys/cert.key': Operation not permitted
chown: changing ownership of '/config/keys/cert.crt': Operation not permitted
chown: changing ownership of '/config/keys': Operation not permitted
chown: changing ownership of '/config/php/php-local.ini': Operation not permitted
chown: changing ownership of '/config/php/www2.conf': Operation not permitted
chown: changing ownership of '/config/php': Operation not permitted
chown: changing ownership of '/config/geoip2db': Operation not permitted
chown: changing ownership of '/config/custom-cont-init.d': Operation not permitted
chown: changing ownership of '/config/custom-services.d': Operation not permitted
chown: changing ownership of '/config': Operation not permitted
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
[cont-init.d] 40-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
chown: changing ownership of '/config/custom-cont-init.d': Operation not permitted
chown: changing ownership of '/config/custom-services.d': Operation not permitted
[cont-init.d] 90-custom-folders: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by firebull81** [comment]
BTW, the last working image is "ghcr.io/linuxserver/nginx:1.18.0-r15-ls134"

**Comment by firebull81** [comment]
This is the log, using those (ghcr.io/linuxserver/nginx:1.18.0-r15-ls134) image

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

chown: changing ownership of '/config': Operation not permitted
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
chown: changing ownership of '/config/nginx/site-confs/default': Operation not permitted
chown: changing ownership of '/config/nginx/site-confs': Operation not permitted
chown: changing ownership of '/config/nginx/nginx.conf': Operation not permitted
chown: changing ownership of '/config/nginx': Operation not permitted
chown: changing ownership of '/config/www/index.html': Operation not permitted
chown: changing ownership of '/config/www': Operation not permitted
chown: changing ownership of '/config/log/nginx': Operation not permitted
chown: changing ownership of '/config/log/php': Operation not permitted
chown: changing ownership of '/config/log': Operation not permitted
chown: changing ownership of '/config/keys/cert.key': Operation not permitted
chown: changing ownership of '/config/keys/cert.crt': Operation not permitted
chown: changing ownership of '/config/keys': Operation not permitted
chown: changing ownership of '/config/php/php-local.ini': Operation not permitted
chown: changing ownership of '/config/php/www2.conf': Operation not permitted
chown: changing ownership of '/config/php': Operation not permitted
chown: changing ownership of '/config/geoip2db': Operation not permitted
chown: changing ownership of '/config/custom-cont-init.d': Operation not permitted
chown: changing ownership of '/config/custom-services.d': Operation not permitted
chown: changing ownership of '/config': Operation not permitted
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
[cont-init.d] 40-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by j0nnymoe** [comment]
You've posted this on the wrong github repo.

**Comment by firebull81** [comment]
Oh ok.
But it's the same behaviour on Swag also.
