### ISSUE TITLE
Redirect to an other website when URL doesn't match any configured

### ISSUE THREAD

**Issue by mada199122** [linuxserver/docker-swag#136]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Default webpage redirect to an other website for example google
All the URLs that don't match the configured redirect to an other website
## Current Behavior

Default webpage Swag default webpage

**Comment by aptalca** [comment]
Create a new catch all server block, designate it as default server and do the redirect.

Closing as this is not a bug

**Comment by mada199122** [comment]
I've tried many times always failing...
 could you kindly explain me a little bit more how can I do that?
It is also enough to "return 444" instead of the redirect...
