### ISSUE TITLE
Can't reverse proxy Wordpress dockerized because of dabatase issue 

### ISSUE THREAD

**Issue by WoisWoi** [linuxserver/docker-swag#137]
![image](https://user-images.githubusercontent.com/75491231/124392193-941d2100-dcf4-11eb-8e10-8ac5b5818781.png)
------------------------------

## Expected Behavior
DB connection to suceed 

## Current Behavior
Not working only with the domain name, it's working with the IP.

## Steps to Reproduce
DB, wordpress and swag in docker 

## Environment
**OS:** ubuntu 20.4 tls
**CPU architecture:** x64
**How docker service was installed:**
 linuxserver/swag

## Command used to create docker container (run/create/compose/screenshot)
 compose with container also tried to create with portainer

**Comment by drizuid** [comment]
closing this as it's a database configuration issue from the OP and nothing to do with wordpress or swag.
