### ISSUE TITLE
[emerg] duplicate location "/" in /config/nginx/site-confs/default:43

### ISSUE THREAD

**Issue by Rickexe** [linuxserver/docker-swag#147]
Hello,

I am getting this error `nginx: [emerg] duplicate location "/" in /config/nginx/site-confs/default:43` when starting Swag. 

I deleted all the files to get the latest updates and now I get this. There's nothing you need to do to reproduce this error. It's the default file that Swag creates on start. No point pasting my config here because it's all default. This is a bug. Please fix.

**Comment by j0nnymoe** [comment]
This file hasn't been touched for nearly 4 months and I can't reproduce this error.
Marking this issue as invalid until more information is provided.

**Comment by Roxedus** [comment]
The only way to get duplicated / is if you made nginx load additional files.

**Comment by Rickexe** [comment]
Nope, it's a clean install. The error is in the file default and since that's the default config it's a bug.

**Comment by j0nnymoe** [comment]
>I deleted all the files to get the latest updates
>Nope, it's a clean install. 

Which is it?

**Comment by Rickexe** [comment]
Both of course lol. I deleted everything. So it's a clean install.

**Comment by Roxedus** [comment]
I have done 3 clean installs, and each time it has succeeded. There was no residue persistent storage in any of my runs. 

Please provide the requested information if you want us to help you troubleshoot this.

**Comment by aptalca** [comment]
> The error is in the file default and since that's the default config it's a bug.

There is no such bug.

**Comment by Rickexe** [comment]
OK HAHAHAH. I'll use something else then instead of swag. Always used to work perfectly. Good luck with your bug fixing!

**Comment by j0nnymoe** [comment]
> OK HAHAHAH. I'll use something else then instead of swag. Always used to work perfectly. Good luck with your bug fixing!

We've tried to replicate in house and not getting the same bug. We've asked you to provide the requested information and you haven't. So there is no bug for us to fix if there is no proof.

**Comment by Roxedus** [comment]
> OK HAHAHAH. I'll use something else then instead of swag. Always used to work perfectly. Good luck with your bug fixing!

Please let us find this "bug", as we cant replicate it with the provided steps.

**Comment by CarbonMac** [comment]
I think I understand what their confusion was, they probably forgot they had a subfolder configuration for a dashboard or something. Lead me here at least

**Comment by jarrisonfor** [comment]
@Rickexe isnt a bug, i think you have a proxy-conf that has a location / equal to de default conf file

today I had this problem and it was because I had the heimdall activated, and had deleted the default file from the "site-confs" folder to update the swag

`grep -ri "In order to use this location block you need to edit the default" nginx/proxy-confs/`

```
nginx/proxy-confs/heimdall.subfolder.conf:# In order to use this location block you need to edit the default file one folder up and comment out the / location
nginx/proxy-confs/organizr.subfolder.conf.sample:# In order to use this location block you need to edit the default file one folder up and comment out the / and ~ \.php$ locations
nginx/proxy-confs/heimdall.subfolder.conf.sample:# In order to use this location block you need to edit the default file one folder up and comment out the / location
```

**Comment by madkoin** [comment]
@jarrisonfor  thank you for your answer, I had the same problem and since I'm a beginner, I didn't think about the configuration of heimdall, which I had just added, by deleting the config file of heimdall in proxy-confs, and by restarting swag that solved my problem
