### ISSUE TITLE
A custom cert location

### ISSUE THREAD

**Issue by MartinX3** [linuxserver/docker-swag#149]
## Desired Behavior

I want to share the certs with the host.
There I run "cockit" which should use my cert.

## Current Behavior

Following the docs everything in /config is in the same volume.
You mention in your docs to only share the etc folder for super duper security, but don't explain how it works, if you put /config in its own volume.

Of course if I would want to share the cert with other containers, I could mount the /config volume with the "subPath" command for security reasons.

## Alternatives Considered

Splitting the /config stuff into different volumes

Allowing swag to use the host network (might be a security problem)

**Comment by aptalca** [comment]
Services running on host (as opposed to containers) would have access to the certs as long as the config folder is host mounted and the permissions are allowing it. Just point your service (assuming it's running as the same user as swag) to where the config folder is mounted on host (ie. `/home/user/swag/keys/letsencrypt/fullchain.pem`)

**Comment by MartinX3** [comment]
I use a container volume to isolate the config and make it only accessible to containers mounting it.

**Comment by aptalca** [comment]
No point in doing that, really. Bind mounts are just as isolated as docker volumes. Docker volumes are also available (ie. auto mounted) at `/var/lib/docker/volumes`

**Comment by MartinX3** [comment]
So it's better if I look somehow how I can put the cockpit UI into a docker container (I don't want to use the hostnetwork flag).
Or if I can split the /config folder into several volumes (I don't want to share the entire /config folder with the host).

Thank you for the response.

**Comment by aptalca** [comment]
> I don't want to share the entire /config folder with the host

Like I said, they already are by default

**Comment by MartinX3** [comment]
Yes, of course.
My PersistentVolumeClaim with default storageClassName is physically stored on the host. Otherwise it couldn't survive reboots.

But it is also only accessible by root or the userID podman choose to protect the data in the volume.

So by the holy security I can't access volume files as the rootless user podman runs with, too, by default. Which makes it unable for an attacker to steal my data, if he breaks out of my rootless podman container and has the rights of the rootless host user.
