### ISSUE TITLE
2 Servers running docker with the same domain name NEED HELP

### ISSUE THREAD

**Issue by aussieboer61** [linuxserver/docker-swag#150]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I'm running 2 servers one with unraid, and another raspberry pi arm64. I've been running Swag (earlier on letsencrypt) on unraid for years with no issues, recently added a raspberry pi. I'm trying to run 2 instances of swag on each server:

Reverse proxy running on servers on Docker:
unRaid server:  Emby, Sonarr, Radarr, Ombi
Raspberry Pi: PiHole, Octoprint

## Current Behavior
Swag on unraid docker takes over not passing the traffic to the raspberry pi docker.

## Steps to Reproduce

1. Use the same domain name
2. Use subdomain names
3. Set ports to forward on router from 80/443 to server port 1443/180 eg. 192.168.1.2:180 (unraid) 192.168.1.3:180 (raspberry pi)
4. Configure environment and conf files 
5. Set docker to forward port from 180/1443 to 80/443

## Environment
**OS: unRaid Raspbian 64bit
**CPU architecture:** x86_64 and arm64
**How docker service was installed:**

## Docker logs
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support the app dev(s) visit:,
Certbot: https://supporters.eff.org/donate/support-work-on-certbot,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    99,
User gid:    100,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-config: executing... ,
[cont-init.d] 20-config: exited 0.,
[cont-init.d] 30-keygen: executing... ,
using keys found in /config/keys,
[cont-init.d] 30-keygen: exited 0.,
[cont-init.d] 50-config: executing... ,
Variables set:,
PUID=99,
PGID=100,
TZ=Australia/Brisbane,
URL=*************,
SUBDOMAINS=pihole,octoprint,
EXTRA_DOMAINS=,
ONLY_SUBDOMAINS=true,
VALIDATION=dns,
CERTPROVIDER=,
DNSPLUGIN=cloudflare,
EMAIL=admin@***************,
STAGING=false,
,
Using Let's Encrypt as the cert provider,
SUBDOMAINS entered, processing,
SUBDOMAINS entered, processing,
Only subdomains, no URL in cert,
Sub-domains processed are:  -d pihole.************ -d octoprint.**************,
E-mail address entered: ***************,
dns validation via cloudflare plugin is selected,
Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created,
Saving debug log to /var/log/letsencrypt/letsencrypt.log,
No match found for cert-path /config/etc/letsencrypt/live/pihole.cairnscustom.com.au/fullchain.pem!,
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.,
Generating new certificate,
Saving debug log to /var/log/letsencrypt/letsencrypt.log,
Account registered.,
Requesting a certificate for pihole.********** and octoprint.**********,
Unsafe permissions on credentials configuration file: /config/dns-conf/cloudflare.ini,
Waiting 10 seconds for DNS changes to propagate,
,
Successfully received certificate.,
Certificate is saved at: /etc/letsencrypt/live/pihole.*********/fullchain.pem,
Key is saved at:         /etc/letsencrypt/live/pihole.***********/privkey.pem,
This certificate expires on 2021-11-30.,
These files will be updated when the certificate renews.,
,
NEXT STEPS:,
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.,
,
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -,
If you like Certbot, please consider supporting our work by:,
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate,
 * Donating to EFF:                    https://eff.org/donate-le,
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -,
New certificate generated; starting nginx,
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please retrieve a free license key from MaxMind,,
and add a new env variable "MAXMINDDB_LICENSE_KEY", set to your license key.,
[cont-init.d] 50-config: exited 0.,
[cont-init.d] 60-renew: executing... ,
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).,
[cont-init.d] 60-renew: exited 0.,
[cont-init.d] 70-templates: executing... ,
[cont-init.d] 70-templates: exited 0.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Server ready

**Comment by aptalca** [comment]
You don't need two swag instances, one's enough. Swag can reverse proxy services on other devices (as long as it can directly access them).

So if you run swag on unraid, in order to reverse proxy a service on your rpi, set the ip in the proxy conf to your rpi's lan ip and the port to the host mapped port

**Comment by nemchik** [comment]
Extra hint:

If your raspberry pi is running pihole (in docker or natively, doesn't matter) and you want swag on unraid to proxy pihole, enable the pihole proxy and edit these lines:
```nginx
        set $upstream_app pihole;
        set $upstream_port 80;
        set $upstream_proto http;
```
They appear more than once in the file, so edit each set.

You'll want to edit the app line to look like this:
`set $upstream_app 192.168.1.15;` but use the IP address of your raspberry pi on your LAN. You also might need to edit the port to change it from 80 to whatever you use to access the web UI on your LAN.

This method would be true for any proxy file. Just edit the file to use your Pi's LAN IP.

**Comment by aussieboer61** [comment]
I'm running Swag in Bridge mode with the other dockers on unraid, I'm guessing I'll have to run them as Host then in order for Swag to reach docker on the raspberry pi?

**Comment by j0nnymoe** [comment]
Nope, no need for host mode.

**Comment by aussieboer61** [comment]
Awesome, thank you guys, I'm up and running.
