### ISSUE TITLE
Cloudflare IPs blocked with 522 error

### ISSUE THREAD

**Issue by subzero355** [linuxserver/docker-swag#151]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Access domain.com successfully which is proxied via Cloudflare to SWAG instance.

## Current Behavior
When I try to access domain.com, I get 522 error from Cloudflare.

## Steps to Reproduce
Live link [here](https://music.teej.xyz)

## Environment
**OS:** Ubuntu
**CPU architecture:** x86_64
**How docker service was installed:**
Using official docker-compose.yml

## Command used to create docker container (run/create/compose/screenshot)
![image](https://user-images.githubusercontent.com/7847452/131826758-d9343e83-f942-4b4f-a3ef-c5af743731c0.png)

## Docker logs
```
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please retrieve a free license key from MaxMind,
and add a new env variable "MAXMINDDB_LICENSE_KEY", set to your license key.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing...
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 70-templates: executing...
[cont-init.d] 70-templates: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 98-cloudflare-real-ip: executing...
[cont-init.d] 98-cloudflare-real-ip: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Server ready
```

## fail2ban log
![image](https://user-images.githubusercontent.com/7847452/131827031-fb34af0d-29ad-4f19-9736-8a7025a147f9.png)

## Nginx access log
![image](https://user-images.githubusercontent.com/7847452/131827191-862e6d67-0b74-427f-9902-4be2f8a3a778.png)

## Syslog
I see lot of entries blocked with Cloudflare IPs

**Comment by subzero355** [comment]
All my domains configured in SWAG was working fine till yesterday.

**Comment by subzero355** [comment]
Apologies for raising this as an issue, I changed the SSL settings on CF from Full to Flexible and everything broke. When I changed it back to Full, it works fine now. I still don't understand what happened.

**Comment by TheSpad** [comment]
Flexible will break if the backend is doing http->https redirection, Full (and Full Strict) always forces https so doesn't run into that problem.
