### ISSUE TITLE
Connection to letsencrypt fails in 50-config

### ISSUE THREAD

**Issue by anhi** [linuxserver/docker-swag#155]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Certbot should connect to letsencrypt.

## Current Behavior
When starting the container, the init-script 50-config fails. The letsencrypt.log contains this error message:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4ca3138490>: Failed to establish a new connection: [Errno -3] Try again'))
2021-09-14 09:56:10,477:ERROR:certbot._internal.log:An unexpected error occurred:
2021-09-14 09:56:10,478:ERROR:certbot._internal.log:requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4ca3138490>: Failed to establish a new connection: [Errno -3] Try again'))
```

When I log in to the container afterwards and manually re-run 50-config, the certificate is requested and generated correctly. 

## Steps to Reproduce

1. start the container

## Environment
**OS:**  Linux 4.14-24-qnap
**CPU architecture:** x86_64
**How docker service was installed:**

**Comment by Roxedus** [comment]
Your container cannot connect to the internet

**Comment by anhi** [comment]
Yes, but only during the first run of /init. If I change cmd to tail -f /dev/null and exec into the container, the following happens:

if I call /init manually, I get the same error. If I stop /init and run it again, manually, it works.

Does the init system set up anything network related that might be triggered in the wrong order?

**Comment by Roxedus** [comment]
No, the init does not wait for, or touch any network config.

**Comment by anhi** [comment]
Strangely enough, this can be fixed by changing cmd from /init to bash /init.
