### ISSUE TITLE
Support certbot manual challenge

### ISSUE THREAD

**Issue by fserb** [linuxserver/docker-swag#160]
Would it be possible to support a [certbot's manual](https://certbot.eff.org/docs/using.html?highlight=dns#manual) challenge (for DNS mostly) ? I know that renew wouldn't work automatically, but it's better than nothing?

------------------------------

## Desired Behavior

Specify a `VALIDATION=manual` and check the logs for the `TXT DNS` that needs to be added.

## Current Behavior
If the user doesn't use one of the available plugin providers, there's no good alternative (for DNS).

**Comment by denizdogan** [comment]
> Manual challenges are not something we plan to support

Why not?

**Comment by aptalca** [comment]
Because automated renewals will fail

**Comment by nemchik** [comment]
I'm not saying this WILL be supported, but it MAY be considered while one of the future items on my todo list (using certbot's `cli.ini`) is worked on. I believe the ini may account for the ability to do manual validation and include renewals. I am not going to reopen this now, but if it seems doable I will update here and mention the PR where the changes would be.
