### ISSUE TITLE
Add container env variable for certbot flags

### ISSUE THREAD

**Issue by acl1704** [linuxserver/docker-swag#163]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Add a container variable for optional additional certbot flags.

Example docker-compose.yml variable:
`- CERTBOT_FLAGS="--key-type ecdsa --elliptic-curve secp384r1 --staple-ocsp --must-staple" #optional`

The key type, if ecdsa is set, could be defaulted to secp384r1 similar to how 4096 is currently set for RSA keys.

Lets Encrypt will be rolling out ECDSA as the preferred chain in the future. The [ISRG X2 root has opened for public comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1701317) with the intermediates already [open for production issuance](https://community.letsencrypt.org/t/ecdsa-availability-in-production-environment/150679) on an opt-in basis.

## Current Behavior

Currently RSA 4096 certificates are hardcoded.
https://github.com/linuxserver/docker-swag/blob/ce33eeebe79e3e543a5c3b97ee2a1914d71d825f/root/etc/cont-init.d/50-config#L338

## Alternatives Considered

The configuration file the container path of `/etc/letsencrypt/renewal` could contain the extra options, but they would not be available for the initial certificate.

**Comment by lowson** [comment]
Also need this to deal with the expired root certificate. Overall not and issues unless you using certs for TLS-DNS

fix would be to inject --preferred-chain "ISRG Root X1"

**Comment by aptalca** [comment]
Latest image fixes that. No need for certbot args

**Comment by iofq** [comment]
@aptalca Would certbot args still be useful for OP's use case? I can take a stab at it. Or, maybe just a `KEY_TYPE` var that would default to RSA and could be set to ECDSA?

**Comment by acl1704** [comment]
I'm interested in more than just ecdsa of course. Swag definitely works as-is for the vast majority of users, I just want more flexibility for the miniscule minority. Granted, if you're doing testing of certificate compatibility there're more appropriate environments.
