### ISSUE TITLE
swag doesn't seem to be listening on port 443

### ISSUE THREAD

**Issue by IsThisNameGoodEnough** [linuxserver/docker-swag#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
A fresh install of swag results in both port 80 and 443 being opened, and entering the server IP into a browser will bring you to a placeholder "Welcome to our server" website.

## Current Behavior
After spinning up a fresh swag container Let's Encrypt is able to generate a cert, and port 80 redirects to port 443 properly, but there doesn't seem to be anything listening on port 443.

## Steps to Reproduce
I was running into this issue with a new swag install on a server with quite a few other services running, so I performed the following to isolate the issue.
1. Created a new droplet on Digital Ocean with the latest docker CE and docker compose installed.
2. Created a new A record for temp.myurl.com that points to the temporary server.
3. Confirmed that UFW was inactive.
3. Used `docker-compose up -d` with the .yml file listed in the section further down to create the swag container.
4. Confirmed that port 80 was responding and port 443 was not responding using an online port scanner.  Also confirmed that navigating to http://temp.myurl.com redirected to https://temp.myurl.com, but that https://temp.myurl.com would time out.
5. Spun down swag by using `docker-compose down`.
6. Spun up a container of nginx using the following docker compose file:
```
---
version: "2"
services:
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
```
7. Confirmed that port 80 and port 443 were both responding using an online port scanner.  Also confirmed that navigating to http://temp.myurl.com redirected to https://temp.myurl.com and displayed the correct placeholder website using a self-signed cert.

## Environment
**OS:** Ubuntu 20.04 LTS      
**CPU architecture:** x86_64      
**How docker service was installed:**      
Using Digital Oceans's docker droplet, which has docker CE and docker compose pre-installed.  After the droplet is up and running I updated everything using apt-get update && apt-get upgrade

## Command used to create docker container (run/create/compose/screenshot)
```
---
version: "2.1"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=myurl.com # I scrubbed the real url for this ticket
      - SUBDOMAINS=temp,
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
    volumes:
      - /opt/docker/swag/config:/config
    ports:
      - 443:443
    ports:
      - 80:80
    restart: unless-stopped
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
............................+++++
...........................+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=1000
PGID=1000
TZ=America/New_York
URL=myurl.com
SUBDOMAINS=temp,
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=true
VALIDATION=http
DNSPLUGIN=
EMAIL=
STAGING=

Created donoteditthisfile.conf
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Only subdomains, no URL in cert
Sub-domains processed are:  -d temp.myurl.com
No e-mail address entered or address invalid
http validation is selected
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Registering without email!
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for temp.myurl.com
Waiting for verification...
Cleaning up challenges
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/temp.myurl.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/temp.myurl.com/privkey.pem
   Your cert will expire on 2020-12-26. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

New certificate generated; starting nginx
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please retrieve a free license key from MaxMind,
and add a new env variable "MAXMINDDB_LICENSE_KEY", set to your license key.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing...
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
Server ready
```

**Comment by aptalca** [comment]
you have two `ports:` sections in your compose yaml for swag. Merge those into one. It looks like compose is processing the second one and ignoring the first.

**Comment by IsThisNameGoodEnough** [comment]
Well don't I feel foolish!  Thanks for the keen eye.  Everything's working after merging to one.

The yaml file I was originally using came directly from [linuxserver's docs](https://docs.linuxserver.io/images/docker-swag#usage).  Might make sense to fix the typo in the docs if possible.

Thanks again!
