### ISSUE TITLE
404 nginx error with Organizr

### ISSUE THREAD

**Issue by LeeDurant** [linuxserver/docker-swag#170]
Issue: receiving in-page 404 error from SWAG when using organizr, whether installed on a local truenas jail or within the docker stack. 
created: 10/14/2021
image: ghcr.io/linuxserver/swag:latest
installed via docker-compose file:

`---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=REMOVED.org
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
    volumes:
      - /home/REMOVED/appdata/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
`

notes: the forward was working until about three months ago, but I hadn't had time to address it until recently. I rolled up a brief truenas jail with organizr to see if the issue was with the organizr docker image but it seems the issue lies with SWAG. When I point towards the local address (192.168.1.9 for docker or 192.168.1.5 for truenas jail) then I am able to access the normal Organizr UI. When I attempt to reach it via my reverse-proxy'd URL through SWAG, however, I am unable to do so. This is the only container or forward using SWAG that I am having issues with.

**contents:** organizr.subfolder.conf file contents:

Version 2021/05/18

location /organizr {
    return 301 $scheme://$host/organizr/;
}

location / {

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app 192.168.1.5;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    rewrite /organizr(.*) $1 break;

}

**contents:** ~/appdata/swag/nginx/site-confs/default contents:

Version 2021/04/27 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/d>

error_page 502 /502.html;

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    root /config/www;
    index index.html index.htm index.php;

    server_name _;

    include /config/nginx/proxy-confs/*.subfolder.conf;

    include /config/nginx/ssl.conf;
    
client_max_body_size 0;

include /config/nginx/proxy-confs/*.subdomain.conf;
proxy_cache_path cache/ keys_zone=auth_cache:10m;

![image](https://user-images.githubusercontent.com/50924770/138301610-73e2de5f-d867-41e7-8420-31c4fb08bb90.png)

**Comment by drizuid** [comment]
This is extremely difficult to read without proper code blocks. That said, if you could use pastebin or similar after doing the following

1) `tail -f /home/REMOVED/appdata/swag/log/nginx/access.log /home/REMOVED/appdata/swag/log/nginx/error.log` while that runs, try to access organizr. 
2) provide the output you get from the tail via pastebin or similar
3) if you get NOTHING, the traffic isn't reaching swag at all and that's a different issue.

note: your best bet for support is to come to discord in #swag-support.
