### ISSUE TITLE
Automatic proxy DNS with Cloudflare

### ISSUE THREAD

**Issue by HarvsG** [linuxserver/docker-swag#178]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

SWAG already works with DuckDNS. It would be amazing if SWAG could auto-magically configure DynamicDNS with Cloudflare's Proxy DNS server. The user would have to point their domain at cloudflare's nameservers and provide an API key and then SWAG would update the DNS endpoints and configure all locally proxied endpoints (Cloudflare does not allow wild cards for free users) as cloudflare proxy endpoints. This would therefore keep the users public IP private on their SWAG hosted sites.

**Comment by aptalca** [comment]
SWAG doesn't manage CNAME or A records for any service (not for duckdns either)
