### ISSUE TITLE
Mutual TLS Implementation

### ISSUE THREAD

**Issue by obvionaoe** [linuxserver/docker-swag#183]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Would it be possible for SWAG to manage and renew a CA and client certificates, so that it'd be easier to maintain a mutual TLS configuration with NGINX?

A quick draft for what the implementation of this feature could be: 
- a CA self-signed certificate inside SWAG dedicated to mutual TLS
- an endpoint disabled by default that could receive requests for certificate generation or renewal, using a key/token for authentication
- the client would then create a script that'd run on startup, connect to this endpoint and retrieve a certificate if there were none available or renew the old one (and possibly use certutil to import it into the Firefox cert database, but that's not necessary)

## Current Behavior
There's no behaviour to facilitate mutual TLS, I believe.

## Alternatives Considered
A manual/cronjob based implementation, that would take too much time to maintain and probably fail a few times.

Please let me know if this would be possible and/or could involve security vulnerabilities!
Thanks

**Comment by obvionaoe** [comment]
I'd still like to see this implemented

**Comment by Roxedus** [comment]
The point of SWAG is to utilize certbot, which as you point out, is not used for mutual TLS.
