### ISSUE TITLE
Adguard home can't be queried via DoH

### ISSUE THREAD

**Issue by RotasOpera** [linuxserver/docker-swag#184]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I noticed that the adguard home template seems to be wrong. Due to the target of /dns-query not pointing to /dns-query internally the name resolution via DoH from Android fails unless I add /dns-query to the proxy_pass.

------------------------------

## Expected Behavior
It should be possible to add the Adguard subdomain to Androids private DNS

## Current Behavior
When adding the private DNS it gives an error that the connection could not be established.

## Steps to Reproduce
1. Currently the Adguard template reads 
`location /dns-query {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app adguard;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }`
2. I needed to change the last line to `proxy_pass $upstream_proto://$upstream_app:$upstream_port/dns-query;`
3. Tbh I'm not even sure if the Port is correct in this case as well. I had to change it to point to 443. But I do have a super weird configuration.

## Environment
**OS:** Debian
**CPU architecture:** x86_64
**How docker service was installed:**
from Docker hub registry using docker-compose

## Command used to create docker container (run/create/compose/screenshot)
`adguard:
  image: adguard/adguardhome
  container_name: adguard
  restart: unless-stopped
  volumes:
    - /home/dockeruser/config/adguard/workdir:/opt/adguardhome/work
    - /home/dockeruser/config/adguard/confdir:/opt/adguardhome/conf
    - /home/dockeruser/config/letsencrypt/keys/letsencrypt/fullchain.pem:/opt/certs/fullchain.pem:ro
    - /home/dockeruser/config/letsencrypt/keys/letsencrypt/privkey.pem:/opt/certs/privkey.pem:ro
  ports:
    - 53:53/udp
    - 12080:80/tcp
    - 12443:443/tcp
    - 12081:3000/tcp
    - 853:853/tcp`

**Comment by aptalca** [comment]
When using variables, nginx automatically appends the location name to the proxy address
