### ISSUE TITLE
Suggestion: Integration with CrowdSec

### ISSUE THREAD

**Issue by klausagnoletti** [linuxserver/docker-swag#187]
I'd like to suggest integration with [CrowdSec](https://crowdsec.net/). 

Basically CrowdSec is crowdsourced threat intelligence and a modern version of fail2ban (and much more). Being crowdsourced in this context means that threat intelligence is being shared anonymously across users.

Very shortly said it consists of (at least) two parts: an agent which (like f2b) parses logs and detects attacks. The agent also sends and receives threat intelligence and instructing the bouncer in which traffic to block. The other part is a bouncer which basically blocks traffic on various layers in the OSI model. There's firewall bouncers for L3 and application bouncers for L7. This is wordpress, php, cloudflare - and nginx. Basically it's a LUA script which I guess you would want to (easily) integrate with SWAG. More info is at https://doc.crowdsec.net/docs/bouncers/nginx.

I am head of community at CrowdSec and an avid user myself. So if you have any questions or comments please let me know. Also in the near future we would add support for ModSecurity so if there's plans to integrate that into SWAG it could be really interesting imho.

**Comment by ikifar2012** [comment]
I was just about to make this request. I really hope this can be added

**Comment by cheekoo** [comment]
Would love this feature too! Thanks in advance

**Comment by klausagnoletti** [comment]
The quick and dirty way to get swag working with CrowdSec is to have the agent and firewall installed on the host (which I have on my own instance as of a couple of days), point to the log files in the `/etc/crowdsec/aquis.yaml`(of course adjusted to your environment):
```
---
filenames:
  - /<path to nginxlogs>/*.log
labels:
  type: nginx
---
```
Protip: remember the `---` as a separator between entries or you get weird errors :-)

After this, install the nginx collection: `sudo cscli collections install crowdsecurity/nginx` and reload crowdsec `sudo systemctl reload crowdsec`.

Another approach would be to extend the npm container with the new openresty bouncer and run the CrowdSec agent either on the docker host or in its own container (and maybe share data between the containers using docker volumes. This is not yet tested but knock yourselves out :-)

Let me know what comes out of it!

**Comment by TheSpad** [comment]
Just a note to say that we are aware of this request and are investigating how we can offer the integration - it's just a bit fiddly as we need to engineer around some assumptions that don't apply to containers.

**Comment by klausagnoletti** [comment]
Thanks for the update! I'll be in touch to see how we can collaborate on this.

**Comment by lordraiden** [comment]
This project includes crwodsecurity with nginx already integrated maybe you can take some ideas on how to do it

https://github.com/bunkerity/bunkerized-nginx

**Comment by TheSpad** [comment]
We're working with CrowdSec. Just waiting on a new point release of the bouncer to address some dependency issues with Alpine and we should be good to go.

**Comment by klausagnoletti** [comment]
> This project includes crowdsec with nginx already integrated maybe you can take some ideas on how to do it
> 
> https://github.com/bunkerity/bunkerized-nginx

@lordraiden Thanks for pointing me to this. We (CrowdSec) had no idea this existed. It's quite brilliant!

**Comment by TheSpad** [comment]
Quick update - just waiting on the v1.0 release of the bouncer to publish the mod, it's all tested and working against the RC so hopefully shouldn't be long.

**Comment by lordraiden** [comment]
It's a bit confusing but it looks like it's have been already released
https://github.com/crowdsecurity/cs-nginx-bouncer/releases
![imagen](https://user-images.githubusercontent.com/17175395/157510195-a1d071d1-2830-4d74-bd0b-35ffdf2da1a1.png)

**Comment by j0nnymoe** [comment]
@lordraiden give us a change lol, it was only released 3 hours ago

**Comment by TheSpad** [comment]
Once v1.0.0 is out of pre-release status I'll test and kick off the mod build.

**Comment by TheSpad** [comment]
Mod has been published https://github.com/linuxserver/docker-mods/tree/swag-crowdsec
