### ISSUE TITLE
Please upgrade Bitwarden support to Vaultwarden

### ISSUE THREAD

**Issue by cheekoo** [linuxserver/docker-swag#191]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
One of the things changed is the authentication failed log message. fail2ban configs need to be updated, and this is first time I would be using fail2ban, otherwise I would have done it. 

Sample Log:
[2021-12-05 21:13:04.660][vaultwarden::api::identity][ERROR] Username or password is incorrect. Try again. IP: <ADDR>. Username: <Email>.

**Comment by aptalca** [comment]
Included fail2ban confs are coming straight from the upstream fail2ban project. We don't maintain them. You should submit this request to them.

**Comment by Roxedus** [comment]
Said upstream config is also incorrect for when it was called bitwarden_rs
