### ISSUE TITLE
Huge Access Logs

### ISSUE THREAD

**Issue by vladbejenaru** [linuxserver/docker-swag#192]
I have not drilled into it as I just saw it and do not have the right tools and time from where I am right now, but see the attached picture: around of 16GB of access log...
Is this normal? Should I pay special attention to anything in particular?

Thanks!
![2021-12-09 13_10_38-23 88 42 151 - PuTTY](https://user-images.githubusercontent.com/33312839/145394137-f3e5bef9-c8c6-4d02-b8e4-e6efc6d2a372.png)

**Comment by Roxedus** [comment]
Please follow the issue template, as it provides vital information

**Comment by vladbejenaru** [comment]
I will try. One question: this is neither a bug or a feature... is more a support request... maybe here its even not the place for this... if this is the case maybe you can point me in the right direction where I could look for support for something like this. Thanks.

**Comment by Roxedus** [comment]
We don't know if it is a bug yet

**Comment by vladbejenaru** [comment]
for reference, I have file it as a bug here: https://github.com/linuxserver/docker-swag/issues/207

This item can be closed. Thanks.
