### ISSUE TITLE
Update gandi dns plugin

### ISSUE THREAD

**Issue by Steve-Brule** [linuxserver/docker-swag#193]
The current gandi dns implementation yields the following warning messages:

`Plugin legacy name certbot-plugin-gandi:dns may be removed in a future version. Please use dns instead.
Certbot is moving to remove 3rd party plugins prefixes. Please use --authenticator dns-gandi --dns-gandi-credentials`

**Comment by nemchik** [comment]
This will be resolved in https://github.com/linuxserver/docker-swag/pull/277
