### ISSUE TITLE
How to I connect container (for example duplicati in my case) to the proxy?

### ISSUE THREAD

**Issue by airdogvan** [linuxserver/docker-swag#20]
Went on Discord but I'm not permitted to post in any of the builds, rules and other available channels and there's no support channel.

Read all the docs, included the config/nginx/proxy-confs/duplicati.subdomain.conf but don't understand how the proxy is supposed to know at which subdomain to reach it.

Where do I tell either the proxy or duplicati which subdomain should be used?

**Comment by nemchik** [comment]
https://github.com/linuxserver/reverse-proxy-confs/blob/4bd10ca6a5d46d7fd0e486124622dc904f02a55c/duplicati.subdomain.conf.sample#L7
This line in your `config/nginx/proxy-confs/duplicati.subdomain.conf` file would mean that any hostname you accessed that begins with `duplicati.` and resolve to your server would proxy duplicati.

ex: duplicati.airdogvan.com
