### ISSUE TITLE
php8 image from standard-base branch?

### ISSUE THREAD

**Issue by steccas** [linuxserver/docker-swag#200]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Hi, I've noticed that the standard-base branch is using a more updated nginx-build including php8. It would be useful in some situations to have a built image to pull like swag:php8 or swag:beta or something.

## Current Behavior
Swag images don't provide the php8 branch.

## Alternatives Considered
Building the branch myself. Creating an unofficial package.

**Comment by nemchik** [comment]
The plan is for the `standard-base` branch to merge into the `master` branch and become the `latest` tag at some point in the future. I've dragged my feet quite a bit on this, but I'm at some initial phases of testing currently.

**Comment by Steccas** [comment]
@nemchik oh that's clearer now! Maybe you need any help with something?

**Comment by nemchik** [comment]
> @nemchik oh that's clearer now! Maybe you need any help with something?

Not yet. The plan is to get a pre-release of swag available for testing. I just need to put the time in.
