### ISSUE TITLE
Pihole webgui admin page issues a "502 Bad Gateway" error when using SWAG / Authelia

### ISSUE THREAD

**Issue by happening-primal** [linuxserver/docker-swag#203]
This isn't really a bug, but more likely some type of user error...anyway...

I'm getting a "502 Bad Gateway" error when I try to access pihole admin webgui proxied via swag and authenticated with authelia.  I did some looking, and simply creating the docker container outside of the swag stack using the below docker-compose.yml allows me to go to the pihole webgui.  When I try to push this through the swag/authelia authelia stack I am getting the 502 error.

Any help much obliged.

docker-compose.yml:

version: "3.1"

services:
&ensp;pihole:
&ensp;&ensp;container_name: pihole
&ensp;&ensp;image: pihole/pihole:latest
&ensp;&ensp;ports:
&ensp;&ensp;&ensp;&ensp;- 53:53/tcp
&ensp;&ensp;&ensp;&ensp;- 53:53/udp
&ensp;&ensp;&ensp;&ensp;- 67:67/udp
&ensp;&ensp;&ensp;&ensp;- 8080:80/tcp
&ensp;&ensp;&ensp;&ensp;#- 8443:443/tcp
&ensp;&ensp;environment:
&ensp;&ensp;&ensp;&ensp;- PUID=1000
&ensp;&ensp;&ensp;&ensp;- PGID=1000
&ensp;&ensp;&ensp;&ensp;- TZ=Europe/London
&ensp;&ensp;&ensp;&ensp;- WEBPASSWORD=my_super_secret_password
&ensp;&ensp;volumes:
&ensp;&ensp;&ensp;&ensp;- /home/my_user_directory/docker/pihole/etc-pihole:/etc/pihole
&ensp;&ensp;&ensp;&ensp;- /home/my_user_directorydocker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d
&ensp;&ensp;dns:
&ensp;&ensp;&ensp;&ensp;- 127.0.0.1
&ensp;&ensp;&ensp;&ensp;- 1.1.1.1
&ensp;&ensp;cap_add:
&ensp;&ensp;&ensp;&ensp;- NET_ADMIN
&ensp;&ensp;deploy:
&ensp;&ensp;&ensp;&ensp;restart_policy:
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;condition: on-failure

swag pihole.subfolder.conf file:

\## Version 2021/05/18
\# pihole does not require a base url setting

location /pihole {
&ensp;&ensp;return 301 $scheme://$host/pihole/;
}

location ^~ /pihole/ {
&ensp;&ensp;\# enable the next two lines for http auth
&ensp;&ensp;\#auth_basic "Restricted";
&ensp;&ensp;#auth_basic_user_file /config/nginx/.htpasswd;

&ensp;&ensp;# enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
&ensp;&ensp;#auth_request /auth;
&ensp;&ensp;#error_page 401 =200 /ldaplogin;

&ensp;&ensp;# enable for Authelia, also enable authelia-server.conf in the default site config
&ensp;&ensp;include /config/nginx/authelia-location.conf;

&ensp;&ensp;include /config/nginx/proxy.conf;
&ensp;&ensp;include /config/nginx/resolver.conf;
&ensp;&ensp;set $upstream_app pihole;
&ensp;&ensp;set $upstream_port 8080;
&ensp;&ensp;set $upstream_proto http;
&ensp;&ensp;proxy_pass $upstream_proto://$upstream_app:$upstream_port;

&ensp;&ensp;rewrite /pihole(.*) $1 break;
&ensp;&ensp;proxy_hide_header X-Frame-Options;
}

location /pihole/admin {
&ensp;&ensp;return 301 $scheme://$host/pihole/admin/;
}

location ^~ /pihole/admin/ {
&ensp;&ensp;\# enable the next two lines for http auth
&ensp;&ensp;\#auth_basic "Restricted";
&ensp;&ensp;\#auth_basic_user_file /config/nginx/.htpasswd;

&ensp;&ensp;\# enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
&ensp;&ensp;\#auth_request /auth;
&ensp;&ensp;\#error_page 401 =200 /ldaplogin;

&ensp;&ensp;\# enable for Authelia, also enable authelia-server.conf in the default site config
&ensp;&ensp;include /config/nginx/authelia-location.conf;

&ensp;&ensp;include /config/nginx/proxy.conf;
&ensp;&ensp;include /config/nginx/resolver.conf;
&ensp;&ensp;set $upstream_app pihole;
&ensp;&ensp;set $upstream_port 8080;
&ensp;&ensp;set $upstream_proto http;
&ensp;&ensp;proxy_pass $upstream_proto://$upstream_app:$upstream_port;

&ensp;&ensp;rewrite /pihole(.*) $1 break;
&ensp;&ensp;proxy_hide_header X-Frame-Options;
}

**Comment by Roxedus** [comment]
upstream_port should be 80. Take a read at the common reasons for a 502 error, https://docs.linuxserver.io/general/swag#502

**Comment by happening-primal** [comment]
> Can you elaborate a little on this? Do you mean the specification on the docker-compose.yml file '- 8080:80/tcp'?. If so, I get an error if I try to use port 80 for pihole as it is conflicting with use of port 80 by swag. Maybe some newb lack of understanding...
> 
> > upstream_port should be 80. Take a read at the common reasons for a 502 error, https://docs.linuxserver.io/general/swag#502

Ah, yes, so it's the swag pihole.subfolder.conf file that needs to continue to point to port 80. 

The swag *.subfolder.conf file needs to point to the second port specified in the docker-configuration.yml port configuration '- 8080:80/tcp'...in this case, port 80.

Thanks for your help and quick reply!!!

Final working set of the docker-configuration.yml and pihole.subfolder.conf file contents below for anyone having this issue.

docker-compose.yml:

version: "3.1"

services:
&ensp;pihole:
&ensp;&ensp;container_name: pihole
&ensp;&ensp;image: pihole/pihole:latest
&ensp;&ensp;ports:
&ensp;&ensp;&ensp;&ensp;- 53:53/tcp
&ensp;&ensp;&ensp;&ensp;- 53:53/udp
&ensp;&ensp;&ensp;&ensp;- 67:67/udp
&ensp;&ensp;&ensp;&ensp;- 8080:80/tcp
&ensp;&ensp;&ensp;&ensp;#- 8443:443/tcp
&ensp;&ensp;environment:
&ensp;&ensp;&ensp;&ensp;- PUID=1000
&ensp;&ensp;&ensp;&ensp;- PGID=1000
&ensp;&ensp;&ensp;&ensp;- TZ=Europe/London
&ensp;&ensp;&ensp;&ensp;- WEBPASSWORD=my_super_secret_password
&ensp;&ensp;volumes:
&ensp;&ensp;&ensp;&ensp;- /home/my_user_directory/docker/pihole/etc-pihole:/etc/pihole
&ensp;&ensp;&ensp;&ensp;- /home/my_user_directorydocker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d
&ensp;&ensp;dns:
&ensp;&ensp;&ensp;&ensp;- 127.0.0.1
&ensp;&ensp;&ensp;&ensp;- 1.1.1.1
&ensp;&ensp;cap_add:
&ensp;&ensp;&ensp;&ensp;- NET_ADMIN
&ensp;&ensp;deploy:
&ensp;&ensp;&ensp;&ensp;restart_policy:
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;condition: on-failure

swag pihole.subfolder.conf file:

\## Version 2021/05/18
\# pihole does not require a base url setting

location /pihole {
&ensp;&ensp;return 301 $scheme://$host/pihole/;
}

location ^~ /pihole/ {
&ensp;&ensp;\# enable the next two lines for http auth
&ensp;&ensp;\#auth_basic "Restricted";
&ensp;&ensp;#auth_basic_user_file /config/nginx/.htpasswd;

&ensp;&ensp;# enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
&ensp;&ensp;#auth_request /auth;
&ensp;&ensp;#error_page 401 =200 /ldaplogin;

&ensp;&ensp;# enable for Authelia, also enable authelia-server.conf in the default site config
&ensp;&ensp;include /config/nginx/authelia-location.conf;

&ensp;&ensp;include /config/nginx/proxy.conf;
&ensp;&ensp;include /config/nginx/resolver.conf;
&ensp;&ensp;set $upstream_app pihole;
&ensp;&ensp;set $upstream_port 80;
&ensp;&ensp;set $upstream_proto http;
&ensp;&ensp;proxy_pass $upstream_proto://$upstream_app:$upstream_port;

&ensp;&ensp;rewrite /pihole(.*) $1 break;
&ensp;&ensp;proxy_hide_header X-Frame-Options;
}

location /pihole/admin {
&ensp;&ensp;return 301 $scheme://$host/pihole/admin/;
}

location ^~ /pihole/admin/ {
&ensp;&ensp;\# enable the next two lines for http auth
&ensp;&ensp;\#auth_basic "Restricted";
&ensp;&ensp;\#auth_basic_user_file /config/nginx/.htpasswd;

&ensp;&ensp;\# enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
&ensp;&ensp;\#auth_request /auth;
&ensp;&ensp;\#error_page 401 =200 /ldaplogin;

&ensp;&ensp;\# enable for Authelia, also enable authelia-server.conf in the default site config
&ensp;&ensp;include /config/nginx/authelia-location.conf;

&ensp;&ensp;include /config/nginx/proxy.conf;
&ensp;&ensp;include /config/nginx/resolver.conf;
&ensp;&ensp;set $upstream_app pihole;
&ensp;&ensp;set $upstream_port 80;
&ensp;&ensp;set $upstream_proto http;
&ensp;&ensp;proxy_pass $upstream_proto://$upstream_app:$upstream_port;

&ensp;&ensp;rewrite /pihole(.*) $1 break;
&ensp;&ensp;proxy_hide_header X-Frame-Options;
}
