### ISSUE TITLE
DYNDNS

### ISSUE THREAD

**Issue by hackitz** [linuxserver/docker-swag#206]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Can you add dyndns to the supported list for dnsplugin

## Current Behavior
I do not see dyndns on the list

**Comment by TheSpad** [comment]
There's no certbot plugin for dyndns so we can't add support for it. You're limited to http validation.

**Comment by hackitz** [comment]
ok thanks, guess i need to use a different dns provider. as my isp has blocked port 80.  which does not allow letsencypt/swag to update.
thanks for the quick reply.

**Comment by aptalca** [comment]
cloudflare is highly recommended (for dns only)
