### ISSUE TITLE
Huge Access Logs swag docker

### ISSUE THREAD

**Issue by vladbejenaru** [linuxserver/docker-swag#207]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Logs should not be this huge. Eventually an option to rotate the logs and to delete old logs once certain log size is achieved
## Current Behavior

Right now I have approx. 15GB of logs

## Steps to Reproduce

1. sudo ls -la /var/lib/docker/volumes/swag/_data/log/nginx
2. right now is looking something like this:
![image](https://user-images.githubusercontent.com/33312839/150525666-c7605200-a833-4a82-9273-3b9e9b5d8a3b.png)

## Environment
**OS:** Debian 11 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
**CPU architecture:** x86_645.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
**How docker service was installed:** docker was installed from official repo via cli

## Command used to create docker container (run/create/compose/screenshot)

docker pull ghcr.io/linuxserver/swag:latest
docker run  --name=swag   --cap-add=NET_ADMIN   --net=lsio   -e PUID=1000   -e PGID=1000   -e TZ=Europe/xxxxx   -e URL=example1.com   -e SUBDOMAINS=xxx,zzz,yyy   -e VALIDATION=http   -e EMAIL=me@mydomain.com   -e ONLY_SUBDOMAINS=false `#optional`   -e EXTRA_DOMAINS=xxx.example2.com,yyy.example2.com `#optional`   -e STAGING=false `#optional`   -p 443:443   -p 80:80 `#optional`   -v swag:/config   --restart unless-stopped   ghcr.io/linuxserver/swag
docker start swag
## Docker logs

[swag_docker_logs_anonymized.txt](https://github.com/linuxserver/docker-swag/files/7913559/swag_docker_logs_anonymized.txt)

**Comment by TheSpad** [comment]
The logs are already rotated and old ones deleted as you can see from your screenshot and https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/root/etc/logrotate.d/nginx - as for why your logs are so big you'd need to look into what's being logged and if necessary adjust the nginx logging parameters and/or the logrotate config to compensate.

**Comment by vladbejenaru** [comment]
rotated, yes, but the old ones are not deleted, they are only compressed. where can i set the settings for logging? should I do it in the `nginx.conf` file?

thanks.

**Comment by TheSpad** [comment]
Yes, they are, the default configuration retains 14 logs. The log rotation configuration is in the file I linked.

If you want to change the nginx logging config then yes, nginx.conf is probably the best place to do that.

**Comment by Roxedus** [comment]
> **rotate** *count*
	Log files are rotated count times before being removed or mailed to the address specified in a mail directive. If count is 0, old versions are removed rather than rotated.

Logrotate is configured to keep 14 rotates.

Without seeing you access logs, it would look like you get a lot of traffic (bot/crawlers or just genuine hits) weekly, which accounts for the size. Personally I would inspect the logs to see if I could configure some contionals to drop logging certain endpoints.

**Comment by vladbejenaru** [comment]
> The log rotation configuration is in the file I linked.

I am sorry but I cannot find this file in the volumes of the swag docker... What am I doing wrong?

> Logrotate is configured to keep 14 rotates.
is there any way to adjust this.

thanks.

> Without seeing you access logs, it would look like you get a lot of traffic (bot/crawlers or just genuine hits) weekly, which accounts for the size. Personally I would inspect the logs to see if I could configure some contionals to drop logging certain endpoints.

I assume that this is not the topic of this forum, but I would appreciate if someone could point me in direction on how to analyze these logs. I would like to understand why they are happening as I am hosting a small app for only 2 persons....

Thanks again!

**Comment by Roxedus** [comment]
> I am sorry but I cannot find this file in the volumes of the swag docker... What am I doing wrong?
> is there any way to adjust this?
It is not directly exposed to the user.

**Comment by TheSpad** [comment]
It's not in the /config mount, it's in the container filesystem at `/etc/logrotate.d/nginx` - you'd have to mount a file over it or use our [customisation logic](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers) if you wanted to modify it persistently.

If you're not doing any kind of geo-blocking or using a tool like fail2ban/crowdsec you're going to get ongoing bot scanning against your services regardless of the "size" of what you're hosting. A tool like [goaccess](https://goaccess.io/) or similar may help you to identify where most of your traffic is coming from.

We also have [dbip](https://github.com/linuxserver/docker-mods/tree/swag-dbip) and [maxmind](https://github.com/linuxserver/docker-mods/tree/swag-maxmind) geo-ip mods for swag as well as fail2ban built in.

**Comment by vladbejenaru** [comment]
huh, I thought fail2ban was somehow taking care of this, but it seems I have to read some more. do you know any tutorial that I can follow for these tools?

if not, I will just have to dig in and eventually write one at the end :)
