### ISSUE TITLE
[feature request] support porkbun dns api

### ISSUE THREAD

**Issue by ksurl** [linuxserver/docker-swag#208]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

add porkbun to supported dns providers

https://porkbun.com/api/json/v3/documentation

## Current Behavior

not supported directly as far as I can see in the dns-conf folder

## Alternatives Considered

workaround is to set dns nameservers on domain to a supported provider like cloudflare

**Comment by j0nnymoe** [comment]
It would need to be supported by certbot first before we can implement it within swag.

**Comment by ksurl** [comment]
I'll look at it upstream then. thanks

**Comment by gsaiz** [comment]
@j0nnymoe Is it not already supported via this plugin? [certbot-dns-porkbun](https://pypi.org/project/certbot-dns-porkbun/)

**Comment by nemchik** [comment]
That should work, but there's no Alpine package for it. This would mean we'd need to ship python in swag to install from the link you provided. It is possible for you to use our custom init to add python and the plugin, and replace our scripts that run certbot to support it if you're comfortable with doing that.

I don't see a high likelihood of us including python in the swag image currently.

**Comment by nemchik** [comment]
I stand corrected. We already ship python for certbot. It should go doable for us.

**Comment by 0xakihiko** [comment]
Would like to up this.

**Comment by FlavorMeld** [comment]
Sorry, didn't see this feature request so I didn't tie it to my PR. 

https://github.com/linuxserver/docker-swag/pull/250
