### ISSUE TITLE
Having an issue getting swag to serve pages with custom .css and .js files

### ISSUE THREAD

**Issue by happening-primal** [linuxserver/docker-swag#209]
Specifically, I'm trying to get swag to reverse proxy [libretranslate](https://github.com/LibreTranslate/LibreTranslate) and ([rss-proxy ](https://github.com/damoeb/rss-proxy).  They run outside of swag just fine, so I know the docker containers are functioning just fine.  What I have found is that if you view the page source the .css and .js redirect to the swag default home page, in my case, homer.  If I view the source for rss-proxy it looks like the below.  However, when I click on the .css link (styles.fca99c9a11ec95436bf5.css) or .js link (runtime-es2015.cdfb0ddb511f65fdc0a0.js) it just tries to redirect me to homer (see html at the bottom.

======================================================================
rss-proxy source:

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>RSS-proxy playground</title>
  <base href="/">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <link href="favicon.ico" rel="icon" type="image/x-icon">
<link rel="stylesheet" href="styles.fca99c9a11ec95436bf5.css"></head>
<body>
<app-root></app-root>
<script src="runtime-es2015.cdfb0ddb511f65fdc0a0.js" type="module"></script><script src="runtime-es5.cdfb0ddb511f65fdc0a0.js" nomodule defer></script><script src="polyfills-es5.790a3785e4df737dcc1e.js" nomodule defer></script><script src="polyfills-es2015.9f9a7e9d82395a8b4bf0.js" type="module"></script><script src="main-es2015.73d3d495c2160e54d3e6.js" type="module"></script><script src="main-es5.73d3d495c2160e54d3e6.js" nomodule defer></script></body>
</html>

======================================================================

<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex"><title>homer</title><link href="css/chunk-2ce48702.3f75b2e0.css" rel="prefetch"><link href="css/chunk-355f6f92.500fe474.css" rel="prefetch"><link href="css/chunk-388b48e3.e2c4317b.css" rel="prefetch"><link href="css/chunk-655d6310.89da3e06.css" rel="prefetch"><link href="css/chunk-7981bd83.b69211c5.css" rel="prefetch"><link href="css/chunk-7cad209b.3610de1b.css" rel="prefetch"><link href="css/chunk-86525ac4.b66e2dd8.css" rel="prefetch"><link href="css/chunk-f47203b8.29a37b88.css" rel="prefetch"><link href="css/chunk-fd3ed72e.dce59c38.css" rel="prefetch"><link href="js/chunk-2ce48702.9651c0f1.js" rel="prefetch"><link href="js/chunk-2e94844a.4305cf0b.js" rel="prefetch"><link href="js/chunk-355f6f92.8dbd090d.js" rel="prefetch"><link href="js/chunk-388b48e3.495bd024.js" rel="prefetch"><link href="js/chunk-655d6310.1c349404.js" rel="prefetch"><link href="js/chunk-7981bd83.2d75a60d.js" rel="prefetch"><link href="js/chunk-7cad209b.cb9dcd5b.js" rel="prefetch"><link href="js/chunk-86525ac4.f8c40d77.js" rel="prefetch"><link href="js/chunk-9e3ef38a.31e3d381.js" rel="prefetch"><link href="js/chunk-f47203b8.2a52a494.js" rel="prefetch"><link href="js/chunk-fd3ed72e.603e39a3.js" rel="prefetch"><link href="css/app.e3980547.css" rel="preload" as="style"><link href="css/chunk-vendors.2c82c67b.css" rel="preload" as="style"><link href="js/app.95840dfd.js" rel="preload" as="script"><link href="js/chunk-vendors.454b593d.js" rel="preload" as="script"><link href="css/chunk-vendors.2c82c67b.css" rel="stylesheet"><link href="css/app.e3980547.css" rel="stylesheet"><link rel="icon" type="image/png" sizes="32x32" href="assets/icons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="assets/icons/favicon-16x16.png"><link rel="manifest" href="assets/manifest.json" crossorigin="use-credentials"><meta name="theme-color" content="#3367D6"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black"><meta name="apple-mobile-web-app-title" content="Homer Dashboard"><link rel="apple-touch-icon" href="assets/icons/icon-maskable.png"><link rel="mask-icon" href="assets/icons/safari-pinned-tab.svg" color="#3367D6"><meta name="msapplication-TileImage" content="assets/icons/icon-any.png"><meta name="msapplication-TileColor" content="#000000"></head><body><noscript><strong>We're sorry but homer doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="js/chunk-vendors.454b593d.js"></script><script src="js/app.95840dfd.js"></script></body></html>

**Comment by jaysgrant** [comment]
I'm running into a similar issue with a custom python flask based container I've written. The CSS works perfectly fine if I access the container outside of swag, but using swag, a 404 shows in the console when the css is attempted to be read.

**Comment by happening-primal** [comment]
> I'm running into a similar issue with a custom python flask based container I've written. The CSS works perfectly fine if I access the container outside of swag, but using swag, a 404 shows in the console when the css is attempted to be read.

I should have come back previously and properly closed the loop on this...

Having said that, what I found was that my issue (and others like it related to other containers) was related to the use of swag sub-folders where a subdomain was required.  Try setting your container up to run through a swag subdomain to your FQDN and see if it works properly.

Hope that gets you on your way.
