### ISSUE TITLE
Keep samples files separated from user configuration files

### ISSUE THREAD

**Issue by GuiPoM** [linuxserver/docker-swag#211]
Hello,

I use docker-swag on a daily basis and this is a very great project to ease the setup of my reverse proxy. 
One issue I have when I maintain my configuration files is that they are located in the proxy-confs folder where all samples as well as the default template are also located. 
So when you try to edit your own configuration, you have name completion to the subdomain file, the subfolder one and so on. 

Maybe things are done that way for a very good reason, but I tried moving all the sample files to a subdirectory named samples, and this helps a lot to manage your own files. You clearly see what file you copied, sometimes files you copied but you are not using and should be deleted, etc ... of course there are always ways to find them, by properly doing a file lookup on this directory, but not as convenient as only having user files there. And of course if you decide to make any change there so that you better see and manage your own files, the next time the container is started all samples are added again.

I would like you to think about moving these samples to a subfolder. Was there a good reason to have them here and would there be any issue to have them now seperated from the use files ?

**Comment by STaRDoGG** [comment]
What i did was create 2 subfolders in that proxy-confs folder; one named "subdomains", one named "subfolders".

Then when i need to add a new, say, subdomain reverse proxy, I'll move the sample i want to the subdomain folder and remove the .sample extension.

This way all of my active proxies are separated from the huge sample folder, and even the subdomain confs are separated from the subfolder confs.

**Comment by GuiPoM** [comment]
Oh, this is a clever idea ! I was thinking the other way round but I did not think about putting my own configuration into a subfolder. That could be a good way to organize my settings. I will give it a try !

**Comment by nemchik** [comment]
> What i did was create 2 subfolders in that proxy-confs folder; one named "subdomains", one named "subfolders".
> 
> Then when i need to add a new, say, subdomain reverse proxy, I'll move the sample i want to the subdomain folder and remove the .sample extension.
> 
> This way all of my active proxies are separated from the huge sample folder, and even the subdomain confs are separated from the subfolder confs.

This is actually really clever. Nice!

**Comment by GuiPoM** [comment]
I tried it, and there is a major drawback: by putting the settings to a subfolder all the paths defined in the templates have also to be modified accordingly.
This is not a big deal as long as you keep these configuration for a long time, but when from time to time there are new sample provides with updated configurations it starts to introduce more maintenance. So I definitively think that samples have to move away, not the configuration files.

**Comment by STaRDoGG** [comment]
> I tried it, and there is a major drawback: by putting the settings to a subfolder all the paths defined in the templates have also to be modified accordingly. This is not a big deal as long as you keep these configurations for a long time, but when from time to time there are new samples provides with updated configuration it starts to introduce more maintenance. So I definitively think that samples have to move away, not the user configuration files.

I forgot to add to my post that if order for it to work, you have to add 2 lines to:

`swag\config\nginx\site-confs\default`

```
# enable subfolder method reverse proxy confs
include /config/nginx/proxy-confs/*.subfolder.conf;
include /config/nginx/proxy-confs/subfolder/*.subfolder.conf;          <------------
```

and

```
# enable subdomain method reverse proxy confs
include /config/nginx/proxy-confs/*.subdomain.conf;
include /config/nginx/proxy-confs/subdomain/*.subdomain.conf;          <------------
```

The arrows point to the lines needing to be added.

**Comment by foxy82** [comment]
> > What i did was create 2 subfolders in that proxy-confs folder; one named "subdomains", one named "subfolders".
> > Then when i need to add a new, say, subdomain reverse proxy, I'll move the sample i want to the subdomain folder and remove the .sample extension.
> > This way all of my active proxies are separated from the huge sample folder, and even the subdomain confs are separated from the subfolder confs.
> 
> This is actually really clever. Nice!

Would you consider making this part of the container? As you say it is a neat way to see the actual config you are using and could be done in a way that is backward compatible?

**Comment by STaRDoGG** [comment]
> could be done in a way that is backward compatible?

Just a thought on backward compatibility, I think it could be done like this:

Replace the current lines:

1. 
```
include /config/nginx/proxy-confs/*.subfolder.conf;
include /config/nginx/proxy-confs/*.subdomain.conf;
```

and replace with the new lines:

```
include /config/nginx/proxy-confs/subfolder/*.subfolder.conf;
include /config/nginx/proxy-confs/subdomain/*.subdomain.conf;
```

2. Have the container create the `subfolder`  and `subdomain` directories if they don't already exist.

3. Have the container search for any active `subdomain.conf` / `subfolder.conf` and if found, move it/them to their respective directory.

4. Just keep adding any `.sample` confs to the directory they already are in, as usual, so only sample confs live there.

5. Update any docs to let people know how to use this new convention. (just move a `.sample.conf` to the respective subfolder, and proceed as usual with it).

Also, if there is a scanner (cronjob) set to a quick timer, say, 1 second, to scan the folder to do the moving, the use wouldn't even need to manually move the file; just remove the .sample extension, and the scanner will auto-move it for the user.

6. Update the [SWAG Dashboard](https://github.com/linuxserver/docker-mods/tree/swag-dashboard). It currently doesn't recognize the confs in those subfolders.

All-in-all, a pretty quick, and simple enhancement.

**Comment by GuiPoM** [comment]
If there is anything to change here, why not keeping the conf files where they should be and move the sample files somewhere else, for example in a sample subfolder ?

The sample files are already container data added automatically at startup when the conf files are important user data, I would not recommend to move them and have them potentially touched during each startup.
The sample files are on the contrary quite safe to work with.

**Comment by STaRDoGG** [comment]
> why not keeping the conf files where they should be and move the sample files somewhere else, for example in a sample subfolder ?

In that case, the subfolder and subdomain confs would all be in the same folder. This method separates those out so the confs all go into their respective subdirectories.

**Comment by STaRDoGG** [comment]
I whipped up a script to handle points 2 and 3 in my post above; which is the bulk of the work needing done.

```
#!/usr/bin/bash

# + ----------------------------------------------------------------------------------- +
# | Proxy Folders for SWAG - J. Scott Elblein / STaRDoGG                                |
# + ----------------------------------------------------------------------------------- +
# | Last Updated: 08/01/2022                                                            |
# |                                                                                     |
# | Script to:                                                                          |
# |  - Check existence of subdomain/subfolder proxy dirs, creating as necessary.        |
# |  - Auto-move any subdomain/subfolder .conf files to the respective directory above. |
# |  - Runs as an infinite loop, so it runs ever 5 seconds, which means a user can also |
# |    simply remove the '.sample' from a sample conf and within 5s it will be moved.   |
# |                                                                                     |
# + ----------------------------------------------------------------------------------- +
# |                                                                                     |
# | Usage:                                                                              |
# |                                                                                     |
# | See thread for full details:                                                        |
# | https://github.com/linuxserver/docker-swag/issues/211#issuecomment-1201899809       |
# |                                                                                     |
# | - Drop this file into: /config/etc (chmod +x)                                       |
# | - 2 lines need to be added to: swag\config\nginx\site-confs\default                 |
# | - Add script to container startup.                                                  |
# + ----------------------------------------------------------------------------------- +

declare -a arr=("/config/nginx/proxy-confs/subdomain" "/config/nginx/proxy-confs/subfolder")

while :
do

    for i in ${arr[@]}
    do
        # Check whether the subdirectory exist(s)
        if [ ! -d ${i} ]; then
            # Nope, create it.
            mkdir $i
            chown abc:abc $i
        fi
    done

    # Move any 'live' proxies in the samples directory into their specific subdirectory
    mv /config/nginx/proxy-confs/*.subdomain.conf "/config/nginx/proxy-confs/subdomain" 2>/dev/null
    mv /config/nginx/proxy-confs/*.subfolder.conf "/config/nginx/proxy-confs/subfolder" 2>/dev/null

    # Repeat loop every 5 seconds, indefinitely.
    sleep 5

done
```

It still needs to be started in container init, which I didn't address.

**Comment by FlavorMeld** [comment]
I found it simpler to just create a simple custom-cont-init.d script to move the samples. 

movetemplates.sh

`#!/bin/bash
echo "**** moving templates ****"
mv /config/nginx/proxy-confs/*.sample /config/nginx/proxy-confs/_templates/`

**Comment by STaRDoGG** [comment]
@GuiPoM ^---- that sounds like what you're looking for. 

I tend to be a lil more OCD with my organization, and like things neat and tidy, going in their own folders. :D

**Comment by nemchik** [comment]
After some significant time spent considering various possible reorganizations of the sample files and configuration folders we've opted to keep the existing structure. Some of the suggestions above are very creative and should work fine, but we do not plan to change how we ship things.

**Comment by GuiPoM** [comment]
> After some significant time spent considering various possible reorganizations of the sample files and configuration folders we've opted to keep the existing structure. Some of the suggestions above are very creative and should work fine, but we do not plan to change how we ship things.

This is very disappointing 😐 
Can you add a deployment option to not add template? When you are running in production you only need to maintain what you have, and all these files are not helping doing these things right and efficiently.

**Comment by coreyaboy** [comment]
I'm a little new to Docker. Not realizing it was a behavior of the container, I burned several hours this morning trying to figure out why two hundred conf.sample files that I no longer needed were occasionally undeleting themselves. Google brought me here while I was looking for a solution to my problem, so I'm going to reply with my solution for the next person that google brings here.

For people such as @GuiPoM and myself whom prefer an arrangment with sample config files being stowed seperately from active configs, there's a simple way to tweak their nginx config to give us that behavior.

Manually make a new folder named /config/nginx/site-confs/**proxy-confs-production**

Edit lines 24 and 60 of the file /config/nginx/site-confs/**default.conf** and add **-production** to the paths and restart SWAG.

You can now as needed copy the samples you want to use from proxy-confs to proxy-confs-production, rename them and work on them there. Just keep in mind that when upgrade time comes along, you might have some extra sluething to do to figure out what relevant samples have been updated.
