### ISSUE TITLE
Illegal instruction while running certbot in swag container on aarch64

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-swag#214]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I have installed swag container on a Raspberry 3+ (aarch64/8) and during execution of "cerbot" to get let's encrypt certificates I get the following error in log:
"Running_ certbot renew
/app/le-renew.sh: line 27:   543 Illegal instruction     (core dumped) certbot -n renew --pre-hook"
The bug happens during first certificate build as well as certificate renew.
When I rebuild the image using git sources and Dockerfile.aarch64 it's working, so I think the wrong platform was selected for certbot build in swag image.
------------------------------

## Expected Behavior

During certificate first build or renew certbot should shouldn't crash with "illegal instruction" 
## Current Behavior

During certificate first build or renew certbot should successfully run and generate / renew the  certificates

## Steps to Reproduce

1.Install and configure swag container in docker compose
2. run "docker-compose up"
3. swag container is successfully installed but during certificate generation certbot crashes with "illegal instruction"
4.

## Environment
**OS:** Raspian (Debian) 5.10.92-v8+
**CPU architecture:** arm64 aarch64/v8
**How docker service was installed:**
Swag installed from "linuxserver/swag" as well as from "ghcr.io/linuxserver/swag"

## Command used to create docker container (run/create/compose/screenshot)

  swag:
    image: "linuxserver/swag"
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
      - URL=mydomain.provider.fr
      - VALIDATION=http
      - EMAIL=myemail@provider.fr
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./swag/config:/config

## Docker logs

Extract of log:
"Running_ certbot renew
/app/le-renew.sh: line 27:   543 Illegal instruction     (core dumped) certbot -n renew --pre-hook"

**Comment by Roxedus** [comment]
Please run `docker exec -it swag uname -a` and post the output

**Comment by FrancisH92** [comment]
Here it is:
Linux IOT-Server 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux

**Comment by Roxedus** [comment]
Try pulling the specific architecture `lscr.io/linuxserver/swag:arm64v8-latest`

**Comment by FrancisH92** [comment]
Answer:
Using default tag: latest
Error response from daemon: pull access denied for swag, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by Roxedus** [comment]
How did you manage that?
```sh
 ~ docker pull lscr.io/linuxserver/swag:arm64v8-latest
arm64v8-latest: Pulling from linuxserver/swag
```

**Comment by FrancisH92** [comment]
I changed the docker-compose.yml line for image in swag section:
swag:
     image: "lscr.io/linuxserver/swag:arm64v8-latest"
     ...
then ran docker-compose pull swag
I tried as well with:
image: "lscr.io/linuxserver/swag:arm64v8", same result

**Comment by Roxedus** [comment]
Error says you are trying a `docker pull swag`

**Comment by FrancisH92** [comment]
My mistake I typed docker instead of docker-compose !
Tried again, worked this time and succeeded to pull the specific architecture image.
However I tried to renew the certificates by issuing:
docker exec -it swag certbot renew
and I got :
Running certbot renew
/app/le-renew.sh: line 27:   543 Illegal instruction     (core dumped) certbot -n renew --pre-hook "if ps aux | grep [n]ginx: > /dev/null; then s6-svc -d /var/run/s6/services/nginx; fi" --post-hook "if ps aux | grep 's6-supervise nginx' | grep -v grep > /dev/null; then s6-svc -u /var/run/s6/services/nginx; fi;     cd /config/keys/letsencrypt &&     openssl pkcs12 -export -out privkey.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem -passout pass: &&     sleep 1 &&     cat privkey.pem fullchain.pem > priv-fullchain-bundle.pem &&     chown -R abc:abc /config/etc/letsencrypt"

**Comment by FrancisH92** [comment]
Hi,
Latest check: when I build the container myself using the following in docker-compose.yml it is working:
  swag:
    build:
      context: "https://github.com/linuxserver/docker-swag.git"
      dockerfile: "./Dockerfile.aarch64"
Issuing "docker exec -it swag certbot --version" is returning "certbot 1.23.0" as expected, while with the pulled image it was returning nothing.
So working for me now.
Thanks for your good work and help.
Francis
