### ISSUE TITLE
Export dashboard metrics to prometheus

### ISSUE THREAD

**Issue by ytzelf** [linuxserver/docker-swag#222]
Hi everyone,

First off, this is probably the best, most complete offering for a homelab reverse proxy. I tried caddy and npm before and this is just above with included f2b filters, dashboard and app templates, so thanks a lot for this.

I was wondering if exporting dashboard metrics to prometheus was on the roadmap? If not it would be a great addition to an already brilliant solution.

Thanks a lot!

**Comment by quietsy** [comment]
Hey @ytzelf , glad you like it.
The metrics in the dashboard are created by `goaccess` which reads the nginx logs, you could export the nginx logs straight into prometheus with something like [https://github.com/martin-helmich/prometheus-nginxlog-exporter](https://github.com/martin-helmich/prometheus-nginxlog-exporter).

**Comment by ytzelf** [comment]
Reopening this as I understand the answer for traffic data but it would still be interesting to expose the list of url proxied and availables? Unless there's a way to programmatically access these?

Thanks!
