### ISSUE TITLE
Add info to docs about Authelia

### ISSUE THREAD

**Issue by 0x199x** [linuxserver/docker-swag#228]
I set up swag a few days ago for the first time, and I've been seeing a lot of comments about Authelia in the nginx configs and was looking into setting up the swag dashboard, which requires something like Authelia for external access.  Not knowing what it was, I naturally went to the docs. It turns out there's really nothing there.

* It's not a linuxserver.io container, so there's no page for it on the container docs.

* It's not mentioned on the "SWAG Setup" page in the docs (regarding what it is or how to configure it)
https://docs.linuxserver.io/general/swag

* It's not mentioned in the linuxserver.io/swag page (except briefly in the version notes)
https://docs.linuxserver.io/images/docker-swag

* Nothing other than a mention of it in the swag dashboard readme either
https://github.com/linuxserver/docker-mods/tree/swag-dashboard

It was surprisingly hard to find. I had to duckduckgo it to find out how to install it.  Which led me to an official [blog post](https://www.linuxserver.io/blog/2020-08-26-setting-up-authelia) from 2020.  

Since that's the only link I can find for information about it (related to swag), I don't even know if it's still up-to-date. I'm sure a lot has changed in two years.

I think it would be beneficial to add some info about this in the docs.  SSO would have been nice to know about when I first set up my swag container.  From a new user perspective, a note on the SWAG Setup page would be helpful.

👍

**Comment by drizuid** [comment]
We have no plans to do this at this time. We don't explain other things nginx can do either, we simply try to make it simple if you choose to use those things.
