### ISSUE TITLE
Compatibility with grafana cloud

### ISSUE THREAD

**Issue by lordraiden** [linuxserver/docker-swag#229]
I am researching how to integrate SWAG logs with grafana or grafana cloud

According to the documentation https://grafana.com/docs/grafana-cloud/integrations/integrations/integration-nginx/?plcmt=nav-products-cta1&cta=cloud
![imagen](https://user-images.githubusercontent.com/17175395/165325889-135306e4-57c7-46d6-a0d6-739045d7d31c.png)

It's possible to do this currently? or it requires a mod or something change in SWAG?

BTW Grafana cloud has a free tier for those interested
https://grafana.com/auth/sign-up/create-user?pg=lokidash
and some interesting dashboards https://grafana.com/grafana/dashboards/12559

**Comment by Roxedus** [comment]
Yes, you are free to modify the files nginx loads from /config/nginx, you can specify the log location and format in tve nginx.conf as you desire.
