### ISSUE TITLE
How to get memcached to auto start

### ISSUE THREAD

**Issue by vcxpz** [linuxserver/docker-swag#23]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

Is there any way to get Memcached to autostart on startup/update of the container?
running "memcached -l 127.0.0.1 -m 512-p 11211 -u abc" works but obviously is not persistent through restarts, I have tried doing a crontab with @reboot but it does not work. the only thing I can think of is to make a script to start it if it is not started and make it run every minute with corn. but there's got to be an easier way

**Comment by aptalca** [comment]
You need to create a custom service. See here: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
