### ISSUE TITLE
OCSP Stapling requires specified resolver

### ISSUE THREAD

**Issue by SebastianGode** [linuxserver/docker-swag#231]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
By default the Server should get an A+ rating on ssllabs, however due to missing OCSP Stapling it will only get an A. 

## Current Behavior
OCSP Stapling is configured here:
https://github.com/linuxserver/docker-swag/blob/master/root/defaults/ssl.conf#L16
However it seems like it is missing a resolver in order to work. Adding this line makes the OCSP Stabling test working on ssllabs:
`resolver 1.1.1.1 1.0.0.1 valid=300s;`
Of course we could also use another resolver and also include an v6 one.

## Steps to Reproduce
Go to https://www.ssllabs.com/ssltest/ and enter the domain and you will only get an A score, with the added line an A+.

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** arm64
**How docker service was installed:**
Official Docker Repo

**Comment by nemchik** [comment]
We do actually include a resolver.
https://github.com/linuxserver/docker-swag/blob/5df55cc0c0e207ab9833b61fc1ce05a9b5f9058d/root/defaults/nginx.conf#L33
Which is populated by:
https://github.com/linuxserver/docker-swag/blob/5df55cc0c0e207ab9833b61fc1ce05a9b5f9058d/root/etc/cont-init.d/50-config#L82-L95

You're free to edit to edit the resolver file to be whatever you'd like.

**Comment by SebastianGode** [comment]
Ah okay, somehow I did not notice that file, thanks :)
