### ISSUE TITLE
ECC certificate instead of RSA 4096 Let's Encrypt

### ISSUE THREAD

**Issue by SebastianGode** [linuxserver/docker-swag#232]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
I would like to have a option to obtain an ECC certificate from Let's Encrypt instead of a RSA 4096 one. This is considered slightly more secure. Certbot has an option for ECC certificates since several years now I think.

## Current Behavior
Currently I don't see a way to add an enviroment variable to specify the type of certificate to obtain for Let'sEncrypt.

**Comment by aptalca** [comment]
It's only available based on an allow list. Allow list is based on account ids. We don't make account ids persistent.

https://community.letsencrypt.org/t/ecdsa-availability-in-production-environment/150679

**Comment by SebastianGode** [comment]
@aptalca This isn't the way I thought it works.
The next big release of certbot even ships with ECDSA certificates by default: https://community.letsencrypt.org/t/ecdsa-certificates-by-default-and-other-upcoming-changes-in-certbot-2-0/177013
They are also signed by R3 which does not require an allow list. Let's Encrypt offers two ways of signing ECDSA ones, one by their RSA authority R3 and one by their ECDSA authority E1 which requires the allow list. It is possible to obtain an ECC certificate without being in the list I think. Need to try it by myself, but at least google says so.

**Comment by SebastianGode** [comment]
Hey @aptalca 
I've now tried updating my manual certificate at home to ECC.
It works flawlessly using 
`sudo certbot certonly --manual --preferred-challenges=dns --email <email> --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --key-type ecdsa -d *.domain.com`

Can we also somehow include this into swag?

**Comment by SebastianGode** [comment]
`comment for non-stale`

**Comment by nemchik** [comment]
ECC certs should now be the default since we've upgraded to certbot 2.x. You can reissue your certs to get ECC certs.
