### ISSUE TITLE
Audiobookshelf

### ISSUE THREAD

**Issue by miseree** [linuxserver/docker-swag#236]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Please add a sample proxy configuration for AudioBookShelf

------------------------------

**Comment by Roxedus** [comment]
Proxy configurations are pulled from https://github.com/linuxserver/reverse-proxy-confs
