### ISSUE TITLE
nginx logrotate fails as /var/run/ss6/services does not exist

### ISSUE THREAD

**Issue by vcxpz** [linuxserver/docker-swag#24]
I have just been trying to setup logrotate and found that the default Nginx logrotate file config has `s6-svc -h /var/run/ss6/services/nginx` but this file does not exist and I believe the path is misspelt as `s6-svc -h /var/run/s6/services/nginx` is a file and reloads Nginx after the files have rotated

**Comment by Roxedus** [comment]
Logrotate is infact set with the correct path. Verified on my production instance, and a test instance i just spun up. https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/root/etc/logrotate.d/nginx#L11
