### ISSUE TITLE
please add extra file type to mime.types

### ISSUE THREAD

**Issue by arajczy** [linuxserver/docker-swag#241]
Please add the below line to /etc/nginx/mime.types:

`application/manifest+json webmanifest;`

Thanks

**Comment by nemchik** [comment]
This actually comes from upstream https://pkgs.alpinelinux.org/contents?branch=v3.17&name=nginx&arch=x86_64&repo=main (honestly, i think it comes from nginx itself, not alpine). You could mount in a custom copy of the file, or use a custom init script to add the line to the file if it doesn't exist. I don't think this is something we want to maintain within swag.
