### ISSUE TITLE
Custom repository for reverse proxy configs via environment variables.

### ISSUE THREAD

**Issue by sarvesh-lad** [linuxserver/docker-swag#242]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
This is with respect to publicly exposing server management software (ex: syno, qnap, unraid, proxmox, esxi, etc)

MOD or feature to enable github repository for custom reverse proxy config

It can work one of the following ways:
1. Add an environment variable to use a third party repo and over ride the default one if provided
2. Add an environment variable to run after the default one and override existing and add new ones

## Current Behavior

Currently only the default reverse proxy repo domains are available. And the current position for critical management server is deny by default which makes sense but not all users are prone to enable it and forget good security practices.

## Alternatives Considered

Do allow such config but:
1. Allow such config but enable access only via local network, similar to one set for the dashboard proxy config
2. Enable auth by default and force user to comment it to disable auth.
3. dont extract said  critical proxy config if the local network variable is not passed in compose or run.

**Comment by nemchik** [comment]
I understand what you're getting at, but I feel like it's unnecessary. You're welcome to create a repository with sample configs for any service you like, and share that information with others who can easily copy your files. I don't think we need to facilitate the ability to replace our examples, although maybe an automated way to add to them using an external repo. The concern is that we have some conventions about how we make configs, and those conventions change occasionally, and it's easy for us to update our own repos without worrying about too many issues breaking things for users. It's rare (making big sweeping changes), but it has happened.

**Comment by sarvesh-lad** [comment]
> I understand what you're getting at, but I feel like it's unnecessary. You're welcome to create a repository with sample configs for any service you like, and share that information with others who can easily copy your files. I don't think we need to facilitate the ability to replace our examples, although maybe an automated way to add to them using an external repo. The concern is that we have some conventions about how we make configs, and those conventions change occasionally, and it's easy for us to update our own repos without worrying about too many issues breaking things for users. It's rare (making big sweeping changes), but it has happened.

Oh yeah no doubt, but I doubt many even know of the mods. Just wanted to throw it out there it would be nice to provide your own config repo. If its not possible its fine, but figured I throw this idea out there for consideration. Call it beta if you have to!
