### ISSUE TITLE
[feature request] Custom hook after renewal/creation

### ISSUE THREAD

**Issue by bilak** [linuxserver/docker-swag#25]
It would be nice if we can register/create some script that will be executed after renewal/creation of certificate process.
Example: I'd like to copy certificate to some folder when it's renewed. I know that I can handle this from outside of container with some periodical checking, but if swag contains cron for this, why just don't use that.
So it would be nice if we can have some custom script executed within `--post-hook`. Optionally there could be also custom script for `--pre-hook`.

**Comment by aptalca** [comment]
you can edit this file: https://github.com/linuxserver/docker-swag/blob/master/root/app/le-renew.sh via a custom script and sed, or map in a custom version of it
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by bilak** [comment]
Hmmm, just thinking loud...
I'm using watchover to automatically update images. If I modify that script and you will modify it in future, that can probably break something and I will probably investigate that for many days as I won't remember what I've changed 😄 
Personally I would prefer some additional script, something like `&& ./custom-post-hooks.sh`. So users are able to add scripts easily. What do you think?

**Comment by aptalca** [comment]
We don't recommend watchtower for automatic updates. It is your responsibility to oversee the updates and check the changelog for breaking changes.

Doing sed in a custom script shouldn't break the existing script and will survive container recreation.

I'll consider user customization of pre/post-hook, but it's probably too fringe a feature and won't be a high priority.

**Comment by eklee** [comment]
Somewhat related to a post renewal-hook, is it possible for the container to restart a host service after a cert renewal, or do I have to use a script to monitor changes for the certs from the host?

**Comment by aptalca** [comment]
You can either use a script to monitor changes (cron, inotify, etc.) or you can use a custom script in swag that seds the referral script to add your hook in

**Comment by nemchik** [comment]
In progress. Other things are blocking https://github.com/linuxserver/docker-swag/pull/161

**Comment by nemchik** [comment]
This is now completed and released.

**Comment by 1aam2am1** [comment]
Hi. Is this implemented in some way?
As I can't find anything in readme or docks.

So how exactly should I add my custom post hook script so that it will reload custom software/other containers.

**Comment by nemchik** [comment]
You should be able to add any pre or post hook you'd like into the `/config/etc/letsencrypt/renewal-hooks/` subfolders. It's more of an advanced feature, so it's not documented. We can't support anything you do with hooks, but you at least have a way to do it.

**Comment by UliPrantz** [comment]
Maybe some (small) documentation would be helpful anyway don't you think? 

Even for advanced users it's hard to tell how to get things up and running - it could save many hours for many people to get some basics like:

- Which kind of scripts work? (bash, python, anything with a working shebang line?)
- Do we need to make them executable? (I guess so?)
- Any specific endings required? (extrapolating from the `10-nginx` example in `renewal-hooks/post` - no ending is a good start?)

**Comment by aptalca** [comment]
It's a certbot feature so their docs should cover most if not all of that.
