### ISSUE TITLE
Remove DST Root CA X3 from chainlist

### ISSUE THREAD

**Issue by Peppe909** [linuxserver/docker-swag#251]
Hi,

this is my first bug report, so im sorry if i will miss some information. Im using Unraid with SWAG docker and ZeroSSL for the certs. Im using Emby for streaming to my clients, but they have issues connection, as the cert DST Root CA X3 expired. Is it somehow possible, to remove this certificate from the chainlist? Or what should be done? Ive already used the --preferred-chain "ISRG Root X1" and changed in my conf file under [renewalparams] the parameter with preferred_chain = ISRG Root X1 with no success. Should i address this issue to ZeroSSL or can you help me out?

Thanks
Peppe

**Comment by aptalca** [comment]
Afaik that root cert change was specific to Let's Encrypt, not ZeroSSL.

**Comment by Peppe909** [comment]
Ive reinstalled Swag, used Zerossl to gain the certificates, but after SSL check, it shows DST Root CA X3   Self-signed - Valid until: Thu, 30 Sep 2021 14:01:15 UTC
EXPIRED.

Sorry to have ultranoob questions or answers...

**Comment by aptalca** [comment]
Fill out the issue template

**Comment by drizuid** [comment]
template not filled out.
