### ISSUE TITLE
Request: docs on how to setup dnsplugin=cloudflare when cloudflare is set to proxy

### ISSUE THREAD

**Issue by ofersadan85** [linuxserver/docker-swag#252]
As stated in the [docs](https://docs.linuxserver.io/general/swag#create-container-via-dns-validation-with-a-wildcard-cert) we can only use the cloudflare plugin to get a "wildcard" certificate if cloudflare is set to DNS mode only (no proxy). From the docs:

> On our dns provider, we'll create an A record for the main domain and point it to our server IP (wan). We'll also create a CNAME for * and point it to the A record for the domain. On Cloudflare, we'll click on the orange cloud to turn it grey so that it is dns only and not cached/proxied by Cloudflare, which would add more complexities.

What if I need to use the proxy option in cloudflare? How will I go about "adding complexities" if I need them? The docs make it seem like this wouldn't work at all for proxy-enabled domains, which is probably the whole reason to use cloudflare in the first place. Should this still work (and the docs need to change) or is this something that will be added in the future?

**Comment by aptalca** [comment]
Just means it's not something we provide support for. It works when set up properly. You can consult Cloudflare docs.
