### ISSUE TITLE
SearXNG Proxy Config

### ISSUE THREAD

**Issue by servebeer** [linuxserver/docker-swag#253]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Please include a proxy config sample for SearXNG.

## Current Behavior
No sample config provided

## Alternatives Considered
n/a

**Comment by aptalca** [comment]
Proxy confs are mostly community submitted and reside here: https://github.com/linuxserver/reverse-proxy-confs
