### ISSUE TITLE
How to set SMTP credentials for email notification for the Fail2Ban include in SWAG?

### ISSUE THREAD

**Issue by MilesTEG1** [linuxserver/docker-swag#257]
Hello,
I’m new to SWAG container, and I would like to get fail2ban notifications with email. But I can’t find a way to set my smtp server and ID/pwd for it…
So, how can I set SMTP credentials for email notification for the Fail2Ban include in SWAG ?

Thanks in advance.

**Comment by aptalca** [comment]
This is not the proper place for this. Please use discord or forum.
