### ISSUE TITLE
Update writes over 'default' in sites-config

### ISSUE THREAD

**Issue by slimshizn** [linuxserver/docker-swag#267]
Wrote over my default configuration, glad I had a back up. Not sure if this is intended.

**Comment by aptalca** [comment]
Please specify `Wrote over my default configuration`

Old `default` gets renamed to `default.conf` during first run because in the latest version of SWAG (and our nginx baseimage) only files with the `.conf` extension are active nginx confs

**Comment by slimshizn** [comment]
Ah okay, mostly my mistake for that one then for not reading over changes. So all files need to be changed over to file.conf? Thank you

**Comment by slimshizn** [comment]
Yep changed all over to .conf, working fine. Thanks for the super fast reply.
