### ISSUE TITLE
incorrect path in tautulli.subfolder.conf.sample ?

### ISSUE THREAD

**Issue by PriamX** [linuxserver/docker-swag#269]
If I'm not mistaken, the path in the last location block in the file `/config/proxy-confs/tautulli.subfolder.conf.sample`,  should be `/tautulli/images` instead of `/tautulli/image`

**Comment by Roxedus** [comment]
Path is /tautulli/image/images on my install.

**Comment by PriamX** [comment]
Then it looks right for your install.

My pull is `linuxserver/tautulli`, image directory in the container is `/app/tautulli/data/interfaces/default/images/` no 'image' (singular) reference there.

And certainly changing the location from `location ^~ /tautulli/image` to `location ^~ /tautulli/images` fixed the broken image links I was getting.

I wonder if our docker image files are different.

Looking at the source HTML, it's definitely "images" plural, not singular (see below) in the install I'm using. 

![image](https://user-images.githubusercontent.com/43935458/193889411-96a2c5b7-1318-4111-a2d7-caf5bd3ea8f2.png)

**Comment by Roxedus** [comment]
The block is intended for newsletters, which do use /image/images. I also see /images used for favicons when browsing the ui while authenticated.

**Comment by PriamX** [comment]
I haven't used the newsletters feature. Where I noticed the broken links (mainly) was the icons on the movie info page, for example (this is, of course, fixed here):

![image](https://user-images.githubusercontent.com/43935458/193892193-dde4ee86-4ff4-4311-a650-36e2118eecf9.png)
