### ISSUE TITLE
branch or anything like to has the httpredis support

### ISSUE THREAD

**Issue by mzramna** [linuxserver/docker-swag#271]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
could be branched or modified the swag image to use an nginx version compiled with the [redis caching support](https://www.nginx.com/resources/wiki/modules/redis/)?
since it is installed into the compilation step, it only will be avaliable if the image already came with the modified nginx executable, or maybe ir could be created an docker mod for this? if only a docker mod is needed i'll try to do it myself later

**Comment by aptalca** [comment]
We do include an http-redis module: https://github.com/linuxserver/docker-swag/blob/master/Dockerfile#L41 Is that not what you're looking for?

**Comment by mzramna** [comment]
yes!!! exactaly this, sorry i didn't know it was possible to install trough apk, what i've researched says nginx has to install it in compilation stage
