### ISSUE TITLE
New default.conf is not including ssl.conf, causing issues during startup

### ISSUE THREAD

**Issue by Hermanio** [linuxserver/docker-swag#279]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When starting up the container with the new default.conf configuration, it should start up without issues and display the default SWAG page over HTTPS.

## Current Behavior

Startup fails with the following error:
```
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:14
```

If I add the following line to that section of the default.conf file, the issue goes away:

```
    include /config/nginx/ssl.conf;
```

That line is also present on an earlier version of the default configuration file, `version 2020/03/05`. 

This issue caused me some trouble when trying to upgrade from `linuxserver/swag:version-1.28.0` because I thought I'd refresh my default.conf to be up to date with this project. 

Is this change intentional, or did I miss something from [this announcement?](https://info.linuxserver.io/issues/2022-08-20-nginx-base/)

## Steps to Reproduce

Unable to provide steps to reproduce at this time without regenerating LetsEncrypt certs on a new instance, but happy to add those if someone knows how to skip that part for testing purposes.

## Environment
**OS:** Ubuntu 22.04.1 LTS
**CPU architecture:** x86_64
**How docker service was installed:** official Docker repo

**Comment by nemchik** [comment]
Your docker container logs (that you did not include) indicate that you need to update `nginx.conf` where the `ssl.conf` is now located by default.

https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/25351b52f83fc1ff1385e0abde7760583344f934/root/defaults/nginx/nginx.conf.sample#L58

**Comment by Hermanio** [comment]
Yep, that was it, my bad.
