### ISSUE TITLE
nginx: [warn] "ssl_stapling" ignored

### ISSUE THREAD

**Issue by mammo0** [linuxserver/docker-swag#28]
## Expected Behavior
Fast startup of the nginx server.

## Current Behavior
The nginx server does start. But before it's fully usable it produces the following warnings:
```
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
```
Every few seconds a new warning like this is generated. This process takes about half a minute. During that period the nginx server is not accessible. After that the nginx server works as expected.

## Steps to Reproduce
Can't provide this, since I noticed this behavior today when I was manually restarting the server. No configs were changed, or proxy sites added/removed.

## Environment
**OS:** QNAP QTS 4.4.3
**CPU architecture:** x86_64
**How docker service was installed:** from the official docer repo

## Command used to create docker container (~run/create/compose/~ screenshot)
![settings](https://user-images.githubusercontent.com/5417004/97445123-35b1ce80-192d-11eb-9eb1-e629674b36ba.png)

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1003
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
Variables set:
PUID=1003
PGID=100
TZ=<hidden>
URL=<hidden>
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
DNSPLUGIN=cloudflare
EMAIL=<hidden>
STAGING=

SUBDOMAINS entered, processing
Wildcard cert for <hidden> will be requested
E-mail address entered: <hidden>
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please retrieve a free license key from MaxMind,
and add a new env variable "MAXMINDDB_LICENSE_KEY", set to your license key.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing... 
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Server ready
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
```

**Comment by nemchik** [comment]
Could you try stopping the container and changing the location for the config volume and then start the container again?

This will recreate the container, and start it with no config so that it can generate new config files, including new certificates. Once you see the `Server ready` line in the logs try restarting the container and checking if the logs continue to show the `ssl_stapling` error.

After confirming that you will want to set your config folder location back to the original location so that your sites/proxies will continue to work, and we will probably want to have a look at your nginx configs. This is mainly to confirm if you see the same issue with a fresh config folder.

**Comment by aptalca** [comment]
You might be having dns issues. Are you doing host networking by any chance? Or have pihole or adguard running?

**Comment by mammo0** [comment]
@nemchik Tried that but now nginx even doesn't start:
```
SUBDOMAINS entered, processing
Wildcard cert for <hidden> will be requested
E-mail address entered: <hidden>
dns validation via cloudflare plugin is selected
nerating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-cloudflare, Installer None
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17ec478550>: Failed to establish a new connection: [Errno -3] Try again'))
Please see the logfiles in /var/log/letsencrypt for more details.
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```

My Cloudflare API key is correct since I just created a new one for this test. Rolled back to my working config.

@aptalca For all my Docker containers (including swag) I use bridged networking. Have no Pihole or other blocking services running.

**Comment by aptalca** [comment]
The new log confirms that you have outgoing connection issues for the swag container as it tries to reach `https://acme-v02.api.letsencrypt.org` and fails

**Comment by mammo0** [comment]
Seems 

> The new log confirms that you have outgoing connection issues for the swag container as it tries to reach `https://acme-v02.api.letsencrypt.org` and fails

Seems right, because I can't even `ping github.com` from inside the container. Using the IP address works. But the DNS issue is only in the container since I can ping `acme-v02.api.letsencrypt.org` from the docker host without problems.

**Comment by aptalca** [comment]
For good measure, I'd recommend rebooting your server. Also try putting it on the default bridge temporarily to eliminate custom bridge setting issues.

**Comment by mammo0** [comment]
> For good measure, I'd recommend rebooting your server.

That did the trick! Don't know why it works now but it seems that QNAP had already some DNS problems in the past: https://forum.qnap.com/viewtopic.php?t=143142

Now all DNS names resolve and no warning is printed by nginx anymore.
Thanks for your support!
