### ISSUE TITLE
Could not build optimal variables_hash warn

### ISSUE THREAD

**Issue by mada199122** [linuxserver/docker-swag#280]
I just notice that in the log I have this line

`could not build optimal variables_hash, you should increase either variables_hash_max_size: 1024 or variables_hash_bucket_size: 64; ignoring variables_hash_bucket_size`

Should I worry about it?

In the proxy.conf file I have the default settings

```
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
```

I'm running Swag on a Synology NAS DS 920+

Thanks

**Comment by nemchik** [comment]
It shouldn't cause any breaking issues, but you can increase the values (I would recommend googling the nginx documentation to understand how changing those values works). The need to increase these values is entirely based on your configurations (how many proxy files you have enabled, or other ways you may have customized your configs) and your system resources, so there is no "one-size-fits-all" value we could ship for everyone.

**Comment by C8opmBM** [comment]
I'm also having this issue lately.

Having followed the advice from [here](https://serverfault.com/questions/419847/nginx-setting-server-names-hash-max-size-and-server-names-hash-bucket-size/786726#786726), I haven't reached to a satisfactory value, no matter how high I alternatively increase the sizes. I reached to the max bucket size and warning was still present.
I have around 30 reverse proxies subdomain, so not that many comparing to others, but I still can't figure out the optimal settings for this.

I've settled for 
```
proxy_headers_hash_bucket_size 256;
proxy_headers_hash_max_size 4096;
```
Could be low, I don't know, but not even values of milions would satisfy that warning.
If there's a solution, please chime in.

**Comment by C8opmBM** [comment]
> 

I found the answer in issue #282 and now the warning is gone.
As said, I have about 30 reverse proxy subdomain.

So I added in `nginx.conf`

```
   # Set defaults 
    types_hash_max_size 2048;
    variables_hash_max_size 2048;
```

And modify `proxy.conf` to

proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 2048;

**Comment by mada199122** [comment]
In which point did you add the two lines in the `nginx.conf` file?

thanks

**Comment by C8opmBM** [comment]
```
http {
[...]
    types_hash_max_size 2048;
    variables_hash_max_size 2048;
[...]
}
```

**Comment by mada199122** [comment]
I confirm the warn is gone for me too!!!

Thanks
