### ISSUE TITLE
Add subfolder support for slskd

### ISSUE THREAD

**Issue by neofright** [linuxserver/docker-swag#286]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Desired Behavior
[slskd](https://github.com/slskd/slskd) should be accessible via subfolder `/slskd`

## Current Behavior
There is no `slskd.subfolder.conf.sample` file.

## Alternatives Considered
I have tried the following config, however I get 504 Gateway Time-out*
```
# first edit the slskd.yml and set 'url_base: /slskd' and restart the slskd container

location ^~ /slskd {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;

    #include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app slskd;
    set $upstream_port 5000;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
```
slskd provide some basic instructions [here](https://github.com/slskd/slskd/blob/master/docs/reverse_proxy.md).

**Comment by j0nnymoe** [comment]
Looks like it's missing a `;` after `set $upstream_app slskd`

**Comment by neofright** [comment]
> Looks like it's missing a `;` after `set $upstream_app slskd`

Thanks, my actual config has `set $upstream_app 192.168.x.x;` because my container uses the wireguard client network via `network_mode: service:wireguard_client` and because of this I am unable to use Docker's built in support for accessing a container via its name. I manually edited the config when I pasted it into the issue and missed the `;`. Adding the `;` as there already is in my config unfortunately still doesn't work!

I've edited the post.

**Comment by neofright** [comment]
When migrating from the stock nginx Docker container to swag, I forgot to set `network_mode: host` for the swag container. That will be the reason for my timeouts!

Hopefully this issue can still be used to get a working config for slskd into swag. Although I realise now that I should probably have opened this issue here: https://github.com/linuxserver/reverse-proxy-confs ?

Please close if I have opened it in the wrong place!
