### ISSUE TITLE
Error "Process end with All authorizations were not finalized by the CA" for ZeroSSL

### ISSUE THREAD

**Issue by masterlog80** [linuxserver/docker-swag#288]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Getting a certificate for the target Domain once deploying the image trough Docker Compose using `VALIDATION=dns`, `CERTPROVIDER=zerossl` and `DNSPLUGIN=cloudflare`.

## Current Behavior

Once deploying the image trough Docker Compose, the process ends with `Process end with All authorizations were not finalized by the CA` despite all the settings seems to be fine. I have also noticed that the variable `PROPAGATION` doesn't seem to be respected (as well as the default 10 sec value): despite the logs for the container are showing `Waiting ** seconds for DNS changes to propagate` the waiting time is longer (over 5min+). I am wondering if this may affect the availability of the `_acme-challenge` TXT record added for verification.

## Steps to Reproduce

1. Create a new YML file for docker-compose with `CERTPROVIDER=zerossl` and `DNSPLUGIN=cloudflare`
2. Deploy the container
3. The container will fail per entries on file `/config/dns-conf/cloudflare.ini`
4. Delete the container
5. Complete the configuration on file /config/dns-conf/cloudflare.ini
6. Recreate the container and check the logs

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** x86_64
**How docker service was installed:** official docker repo

## Docker logs 

```
E-mail address entered: ******@********.****
dns validation via cloudflare plugin is selected
Retrieving EAB from ZeroSSL
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for salvetti.info
Unsafe permissions on credentials configuration file: /config/dns-conf/cloudflare.ini
Waiting ** seconds for DNS changes to propagate
All authorizations were not finalized by the CA.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```

**Comment by masterlog80** [comment]
Hello,
After making some tests I have confirmed that the same configuration works with Let's Encrypt instead Zero SSL (so, using the variables `VALIDATION=dns`, `DNSPLUGIN=cloudflare` and `CERTPROVIDER=`).

**Comment by nemchik** [comment]
You can still use the `EMAIL` parameter with letsencrypt as the cert provider.
https://github.com/linuxserver/docker-swag/blob/d00d2dbe95276f9ea67b4d5d3d6a7b0384538208/root/etc/cont-init.d/50-certbot#L144-L151 figures out whether you have set the `EMAIL` parameter
https://github.com/linuxserver/docker-swag/blob/d00d2dbe95276f9ea67b4d5d3d6a7b0384538208/root/etc/cont-init.d/50-certbot#L262 makes use of the email parameter

ZeroSSL uses the email parameter in a different way than letsencrypt (as far as I know). ZeroSSL uses email to associate to an account, where letsencrypt uses email only for notifications when a cert is going to expire and has not been renewed. With letsencrypt, as long as your cert is renewed before its expiration date, you would not receive an email (no news is good news). You can however use cloudflare's certificate transparency feature to receive an email any time a certificate is issued for your domain (this is independent of certbot).

**Comment by masterlog80** [comment]
Hello @nemchik,

Thank you for getting back.
> You can still use the `EMAIL` parameter with letsencrypt as the cert provider.

Interesting. The documentation should better clarify that.

> ZeroSSL uses the email parameter in a different way than letsencrypt (as far as I know). ZeroSSL uses email to associate to an account, where letsencrypt uses email only for notifications when a cert is going to expire and has not been renewed.

Seems a very useful feature.

> With letsencrypt, as long as your cert is renewed before its expiration date, you would not receive an email (no news is good news). You can however use cloudflare's certificate transparency feature to receive an email any time a certificate is issued for your domain (this is independent of certbot).

Thank you for your clarification.

However my point here still stay as I wasn't able to get a certificate for my own Domain once deploying the image trough Docker Compose using `VALIDATION=dns`, `CERTPROVIDER=zerossl` and `DNSPLUGIN=cloudflare`.
No issues so far with using `VALIDATION=dns`, `DNSPLUGIN=cloudflare` and `CERTPROVIDER=` (so with letsencrypt).

Regards,
