### ISSUE TITLE
Include the ngx_http_log_module in the nginx build 

### ISSUE THREAD

**Issue by nealdb** [linuxserver/docker-swag#294]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Include the ngx_http_log_module in the nginx build to allow full urls to be shown and correct IPs when behind Cloudflare

## Current Behavior
Since the default behaviour of SWAG is to place logging for all sites proxied it can be hard to determine which sites are being requested. 
I'd like to be able to use the $host variable in the logs to show the site being requested

Also since putting my sites behind Cloadflare's DNS proxy I only see Cloudflare IP's in my logs. the ngx_http_log_module would allow use of the $http_x_forwarded_for too which would show the originating IP

## Alternatives Considered
I was considering alternate log files per site but wasn't sure if the dashboard would pick them up

**Comment by aptalca** [comment]
What makes you think it's not included?

**Comment by nemchik** [comment]
We have a docker mod https://github.com/linuxserver/docker-mods/tree/swag-cloudflare-real-ip that does what you're asking. If you have trouble getting it setup we can help on our discord.

**Comment by nealdb** [comment]
Thanks for the mod I've now enabled that and it's logging the real IP

But how can I get the full hostname logged so I can see which of the multiple sites swag is proxying added to the logs? As the logs only show the request after the hostname eg /remote.php/dav/files/gloria/ not https://mybloodyawesomeshiz.site/remote.php/dav/files/neal/

@aptalca I can tell it's not included as it's not in the list of included modules if I run nginx -V

**Comment by nealdb** [comment]
Ahh gotcha thanks. I'd specified a new log format in my nginx.conf but hadn't told nginx to **use** that format. 

So problem between chair and keyboard. 
Thanks again
