### ISSUE TITLE
Same error as #66 Unable to retrieve EAB credentials from ZeroSSL.

### ISSUE THREAD

**Issue by J4gQBqqR** [linuxserver/docker-swag#295]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

ZeroSSL operates correctly.

## Current Behavior

ZeroSSL script reports keyerror.

## Steps to Reproduce

1. I use Letsencrypt wildcard
2. Switched to ZeroSSL
3. 50-certbot reports error

## Detail
In file root/etc/cont-init.d/50-certbot, line 15
https://github.com/linuxserver/docker-swag/blob/d159fde608e5102f6d3a805d399ba5275eb42a15/root/etc/cont-init.d/50-certbot#L15
If I inset `echo EMAIL=${EMAIL}`
I get:
```
EMAIL="xxx@xxx.xxx"
```

In line 211
https://github.com/linuxserver/docker-swag/blob/d159fde608e5102f6d3a805d399ba5275eb42a15/root/etc/cont-init.d/50-certbot#L211

If I insert
```
echo ORIGEMAIL=$ORIGEMAIL
echo REV_EAB_CREDS=$REV_EAB_CREDS
```
I get
```
ORIGEMAIL= xxx@xxx.xxx
REV_EAB_CREDS={"success":false,"error":{"code":2901,"type":"invalid_email","info":null}}
```
**Please pay attention to the extra space before the email address!!!**

In the docker container, if I `curl -s https://api.zerossl.com/acme/eab-credentials-email --data "email=xxx@xxx.xxx"`
I was returned
```
{"success":true,"eab_kid":"xxx","eab_hmac_key":"xxx"}
```
In the docker container, if I `curl -s https://api.zerossl.com/acme/eab-credentials-email --data "email= xxx@xxx.xxx"`
I was returned
```
{"success":false,"error":{"code":2901,"type":"invalid_email","info":null}}
```

**Please pay attention to the extra space before the email address!!!**

There is definitely something happening and an extra space is inserted before the email address.
Not sure why it did not happen to everybody else. But I was observing the same as #66.

**Comment by J4gQBqqR** [comment]
It is already pointed out in #66 about this white space problem: https://github.com/linuxserver/docker-swag/issues/66#issuecomment-870864626

This is a bug. I guess only people switching from letsencrypt to zerossl will have this bug. That is why so few people ever run into it.

**Comment by J4gQBqqR** [comment]
Simple fix for your favor: inset `ORIGEMAIL=$(sed 's/^[[:space:]]*//' <<< "$ORIGEMAIL")` before line 211.

**Comment by J4gQBqqR** [comment]
Active. Go away bot.

**Comment by J4gQBqqR** [comment]
Not stale

**Comment by Pheoxy** [comment]
@J4gQBqqR
I had this issue recently with a `.env` file.
Turns out I had a space after the comma.
`EMAIL="dhancock@camelot.network" `
`EMAIL="dhancock@camelot.network"`

Removing that fixed my issue.

**Comment by shlomitan** [comment]
Seems like I'm getting the same problem.
I'm new to pretty much everything but I'm capable, can someone here point me where to find the file in the container so I can add @J4gQBqqR solution? Thanks!
