### ISSUE TITLE
cpanel plugun not working after rollback to 1.32.0

### ISSUE THREAD

**Issue by saue0** [linuxserver/docker-swag#303]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

The certificate should be created

## Current Behavior

I'm getting the following error: 
`certbot: error: unrecognized arguments: --dns-cpanel-credentials /config/dns-conf/cpanel.ini`

## Steps to Reproduce

1.create a new docker container and add domains/subdomains where certificates need to be generated. Alternatively change the subdomains of an existing docker container and restart it, this will force swag to generate new certificates immediatly.
2.VALIDATION : dns
3.DNSPLUGIN : cpanel
4.

## Environment
**OS:** Unraid
**CPU architecture:** x86_64
**How docker service was installed:** Unraid, Community Apps Plugin

## Command used to create docker container (run/create/compose/screenshot)

docker run
  -d
  --name='swag'
  --net='lsio'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME=<redacted>
  -e HOST_CONTAINERNAME="swag"
  -e 'URL'=<redacted>
  -e 'VALIDATION'='dns'
  -e 'SUBDOMAINS'=<redacted>
  -e 'CERTPROVIDER'=''
  -e 'DNSPLUGIN'='cpanel'
  -e 'PROPAGATION'=''
  -e 'EMAIL'=''
  -e 'ONLY_SUBDOMAINS'='false'
  -e 'EXTRA_DOMAINS'=''
  -e 'STAGING'='false'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver-ls-logo.png'
  -p '443:443/tcp'
  -p '80:80/tcp'
  -v '/mnt/user/appdata/swag':'/config':'rw'
  --cap-add=NET_ADMIN
  --restart=unless-stopped 'lscr.io/linuxserver/swag'
f5b0381e544da9e9580783222b77cd81fe58ef23a524a3735d5feaa3b994c2ec

## Temporary fix

in /etc/cont-init.d/50-certbot, added these line...
```
    if [ "$DNSPLUGIN" = "cpanel" ]; then
        if [ -n "$PROPAGATION" ]; then PROPAGATIONPARAM="--dns-${DNSPLUGIN}-propagation-seconds ${PROPAGATION}"; fi
        PREFCHAL="--authenticator certbot-dns-cpanel:cpanel --certbot-dns-cpanel:cpanel-credentials /config/dns-conf/${DNSPLUGIN}.ini ${PROPAGATIONPARAM}"

```
between these lines:
```
# setting the validation method to use
if [ "$VALIDATION" = "dns" ]; then
  <added here, change the next if for elif>
    if [ "$DNSPLUGIN" = "route53" ]; then
```
also had to comment out this line and change the cpanel.ini to the original format.
`sed -i 's|^certbot_dns_cpanel:|dns_|g' /config/dns-conf/cpanel.ini`

## Docker logs

```
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/11-folders
cont-init: info: /etc/cont-init.d/11-folders exited 0
cont-init: info: running /etc/cont-init.d/12-samples
cont-init: info: /etc/cont-init.d/12-samples exited 0
cont-init: info: running /etc/cont-init.d/13-nginx
cont-init: info: /etc/cont-init.d/13-nginx exited 0
cont-init: info: running /etc/cont-init.d/14-php
cont-init: info: /etc/cont-init.d/14-php exited 0
cont-init: info: running /etc/cont-init.d/15-keygen
Generating a RSA private key
..............................................+++++
......................................................+++++
writing new private key to '/config/keys/cert.key'
req: Can't open "/config/keys/cert.key" for writing, No such file or directory
cont-init: info: /etc/cont-init.d/15-keygen exited 1
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/30-test-run
cont-init: info: /etc/cont-init.d/30-test-run exited 0
cont-init: info: running /etc/cont-init.d/31-require-url
cont-init: info: /etc/cont-init.d/31-require-url exited 0
cont-init: info: running /etc/cont-init.d/40-folders
cont-init: info: /etc/cont-init.d/40-folders exited 0
cont-init: info: running /etc/cont-init.d/41-samples
cont-init: info: /etc/cont-init.d/41-samples exited 0
cont-init: info: running /etc/cont-init.d/42-fail2ban
cont-init: info: /etc/cont-init.d/42-fail2ban exited 0
cont-init: info: running /etc/cont-init.d/43-crontabs
cont-init: info: /etc/cont-init.d/43-crontabs exited 0
cont-init: info: running /etc/cont-init.d/45-nginx
cont-init: info: /etc/cont-init.d/45-nginx exited 0
cont-init: info: running /etc/cont-init.d/50-certbot
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

generating self-signed keys in /config/keys, you can replace these with your own keys if required
Variables set:
PUID=99
PGID=100
TZ=America/New_York
URL=<redacted>
SUBDOMAINS=<redacted>
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=cpanel
EMAIL=
STAGING=false

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Sub-domains processed are:  -d <redacted>
No e-mail address entered or address invalid
dns validation via cpanel plugin is selected
Generating new certificate
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-cpanel-credentials /config/dns-conf/cpanel.ini
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cpanel.ini file.
```

**Comment by nemchik** [comment]
I see the issue and am working on a fix.

**Comment by ash-r1** [comment]
In addition, the latest ( or 1.32.0 ) image returns the error like below on my env:

```
AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
```

also, just calling `certbot plugins` shows the same error around `IAuthenticator`.

If fixing this issue is not easy, I think pushing the old `1.31.0` tag as the `latest` tag would be good.

**Comment by nemchik** [comment]
This is resolved in https://github.com/linuxserver/docker-swag/pull/306

**Comment by drizuid** [comment]
OP and others, please test this PR build, if possible, and report back with your findings, thanks!!
