### ISSUE TITLE
Webpage horrible on a any chrome based mobile browser

### ISSUE THREAD

**Issue by realmx2** [linuxserver/docker-swag#304]
Unsure where to report this, but pages like this (swag webpage: https://docs.linuxserver.io/general/swag ) are almost completely unusable on any chrome-based mobile browser. Scrolling around the page is jerky and freezes the browser regularly. If you use Firefox it is better, but only if you wait quite some time looking at a completely white page.

This may be an issue with the documentation app you are using, but I thought I'd let you know in case you weren't aware.

------------------------------
Tested using a Google pixel 5a 5G, using chrome, brave, and firefox

**Comment by aptalca** [comment]
Works perfectly fine here on a pixel 6 and chrome

**Comment by drizuid** [comment]
pixel6a with edge (chromium) and while the scrolling is definitely not smooth (it is quite jerky), i have no freezes and can still use the site.  i forgot to check if it works well when picking "view desktop site" ill do that later and edit this

**Comment by nemchik** [comment]
We're discussing internally.

My Pixel 4a performs pretty poorly (matching @realmrealm 's experience)

**Comment by drizuid** [comment]
can i just say... thank god there's no filthy fucking iphone users in this thread. I commend you all for your great selections :)
