### ISSUE TITLE
[BUG] Directadmin DNS doesn't seem to work

### ISSUE THREAD

**Issue by danielpetrovic** [linuxserver/docker-swag#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Wildcard cert for ***** will be requested
E-mail address entered: *******
dns validation via directadmin plugin is selected
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for ****** and *******
Encountered exception during recovery: UnboundLocalError: local variable 'directadmin_name' referenced before assignment
An unexpected error occurred:
UnboundLocalError: local variable 'directadmin_name' referenced before assignment
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/directadmin.ini file.

### Steps To Reproduce

Starting SWAG for first time after creating container.
User/Pass work when logging directly into DirectAdmin server.
Domainname is anonymized.

### Environment

```markdown
- OS: Ubuntu 22.04LTS
- How docker service was installed: Docker Compose
```

### CPU architecture

x86-64

### Docker creation

```bash
swag:
    container_name: swag
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
      - URL=*****
      - VALIDATION=dns
      - DNSPLUGIN=directadmin
      - SUBDOMAINS=wildcard
      - EMAIL=******
    image: 'linuxserver/swag'
    network_mode: local
    ports:
      - '443:443'
      - '80:80'
    restart: always
    volumes:
      - '/docker/swag:/config'
```

### Container logs

```bash
[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service 00-legacy successfully started
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/11-folders
cont-init: info: /etc/cont-init.d/11-folders exited 0
cont-init: info: running /etc/cont-init.d/12-samples
cont-init: info: /etc/cont-init.d/12-samples exited 0
cont-init: info: running /etc/cont-init.d/13-nginx
using keys found in /config/keys
cont-init: info: /etc/cont-init.d/13-nginx exited 0
cont-init: info: running /etc/cont-init.d/14-php
cont-init: info: /etc/cont-init.d/14-php exited 0
cont-init: info: running /etc/cont-init.d/15-keygen
cont-init: info: /etc/cont-init.d/15-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/30-test-run
cont-init: info: /etc/cont-init.d/30-test-run exited 0
cont-init: info: running /etc/cont-init.d/31-require-url
cont-init: info: /etc/cont-init.d/31-require-url exited 0
cont-init: info: running /etc/cont-init.d/40-folders
cont-init: info: /etc/cont-init.d/40-folders exited 0
cont-init: info: running /etc/cont-init.d/41-samples
cont-init: info: /etc/cont-init.d/41-samples exited 0
cont-init: info: running /etc/cont-init.d/42-fail2ban
cont-init: info: /etc/cont-init.d/42-fail2ban exited 0
cont-init: info: running /etc/cont-init.d/43-crontabs
cont-init: info: /etc/cont-init.d/43-crontabs exited 0
cont-init: info: running /etc/cont-init.d/45-nginx
cont-init: info: /etc/cont-init.d/45-nginx exited 0
cont-init: info: running /etc/cont-init.d/50-certbot
Variables set:
PUID=1000
PGID=1000
TZ=Europe/Amsterdam
URL=*****
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=directadmin
EMAIL=*****
STAGING=

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Wildcard cert for padaco.nl will be requested
E-mail address entered: ******
dns validation via directadmin plugin is selected
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for ****** and *******
Encountered exception during recovery: UnboundLocalError: local variable 'directadmin_name' referenced before assignment
An unexpected error occurred:
UnboundLocalError: local variable 'directadmin_name' referenced before assignment
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/directadmin.ini file.
```

**Comment by nemchik** [comment]
This may be fixed in https://github.com/linuxserver/docker-swag/pull/306

Can you try using `lspipepr/swag:1.32.0-pkg-bdbf434a-pr-306`

**Comment by danielpetrovic** [comment]
Sadly the error is the same. Also tried without Wildcard, just to be sure. Same error.
Currently switched to http and single domain, which works just fine.

**Comment by nemchik** [comment]
Try adding `directadmin_name = something` to `/config/dns-conf/directadmin.ini`

I have no idea what the value would need to be, because it's not documented in the plugin docs as far as i saw.

**Comment by danielpetrovic** [comment]
Nope, error is the same.

**Comment by nemchik** [comment]
This seems to be an issue with the plugin reported here https://github.com/cybercinch/certbot-dns-directadmin/issues/10 and it also seems like something similar happened here https://github.com/cybercinch/certbot-dns-directadmin/issues/6 but the dev released a fix. It's strange that it's still happening.

Just for sanity, can you change your compose to
```yaml
    image: lscr.io/linuxserver/swag:latest
```
and see if this makes a difference?

**Comment by danielpetrovic** [comment]
Switched back to lscr.io/linuxserver/swag:latest, no change sadly.

**Comment by nemchik** [comment]
I think this is going to be something the upstream project needs to resolve (issue 10 on their repo).

It's also worth noting that it seems this plugin uses a very different syntax than all of the officially supported plugins, and also uses [zope](https://github.com/search?q=repo%3Acybercinch%2Fcertbot-dns-directadmin%20zope&type=code) where certbot 2.0 (released recently) seems to have deprecated support for plugins using `zope`.

**Comment by danielpetrovic** [comment]
I will use the HTTP method for now as I only have a few domains to get certificates for anyway, but wildcard was just easy.

**Comment by nemchik** [comment]
The author of the plugin updated it, and we've published a new build that should contain the updated plugin. Can you try running `docker pull lscr.io/linuxserver/swag:latest` and then recreate your container and see if you can use DNS validation?

It is possible that I will need to push an update to how we are using the plugin in order for it to work, but it's worth giving it a shot before I make additional changes.

**Comment by danielpetrovic** [comment]
The error has changed after doing this:

certbot: error: unrecognized arguments: --directadmin-credentials /config/dns-conf/directadmin.ini

--directadmin-credentials is nog present in that .ini file also tried changing filename so new file is created from image, but the template is the same. Maybe the .ini needs updating from the upstream certbot changes?

**Comment by nemchik** [comment]
I suspected as much. I have a very experimental build `lspipepr/swag:1.32.0-pkg-e0c1864b-pr-306` that should include a fix for this issue.

p.s. I unfortunately don't have directadmin to test this myself. the other changes in that PR are all tested though.

**Comment by guisea** [comment]
Hi @nemchik,  

I do have directadmin at my disposal.  I have checked the release: lspipepr/swag:1.32.0-pkg-e0c1864b-pr-306

``` bash
Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/***redacted***/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/***redacted***/privkey.pem
This certificate expires on 2023-03-14.

```

**Comment by danielpetrovic** [comment]
To confirm, lspipepr/swag:1.32.0-pkg-e0c1864b-pr-306 works for me as well. Will keep running this version till it's merged with the main release. Thanks.
