### ISSUE TITLE
ipv6 support with nginx

### ISSUE THREAD

**Issue by bestLR** [linuxserver/docker-swag#311]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be nice to have IPv6 support with nginx by default.

### Reason for change

It can make ddns of my nas easier,and only ipv6 can work well in my internet enviroment when i try to use ddns .

### Proposed code change

Just add '–with-ipv6' when you config nginx.

**Comment by Roxedus** [comment]
ipv6 support is already present in nginx, this image already [listen on ipv6 by default](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/nginx/site-confs/default.conf.sample#L16).
