### ISSUE TITLE
[BUG] Unknown directive stream

### ISSUE THREAD

**Issue by raidenlal** [linuxserver/docker-swag#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Nginx cant start because of wrong configuration:

Unknown directive "stream" in /etc/nginx/conf.d/stream.conf:3

### Expected Behavior

Start without an issue. 

### Steps To Reproduce

I have had swag running for months, 7 hours ago auto update downloaded new image (latest tag), and since then nginx fails to start. 

### Environment

```markdown
- OS: Windows 10
- How docker service was installed: Docker Desktop
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
Unknown directive "stream" in /etc/nginx/conf.d/stream.conf:3

Repeated forever
```

**Comment by danieltownend** [comment]
Also having the same issue, Nginx fails to start after auto-update,

`nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3`

I can't see the following file in the mount so it must be in the image?

Unraid 6.11.5, Docker version 20.10.21

**Comment by raidenlal** [comment]
I have no such file inside host OS. I checked because ofc I thought my configuration is in conflict with new version, but the stream.conf is inside image.

**Comment by danieltownend** [comment]
I've fixed this by reverting to image linuxserver/swag:2.0.0

**Comment by j0nnymoe** [comment]
Dupe https://github.com/linuxserver/docker-swag/issues/318 https://github.com/linuxserver/docker-swag/issues/317

**Comment by raidenlal** [comment]
Sorry about the dupe. I really did search for "stream" inside issue and there were none.
