### ISSUE TITLE
Address in use

### ISSUE THREAD

**Issue by vrelk** [linuxserver/docker-swag#32]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Self-explanatory. See Errors below.

## Current Behavior
nginx: [emerg] bind() to [::]:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use

## Steps to Reproduce
1. Start Swag
2. Wait.This last time had an uptime of 7 days before I got spammed with notifications for things going offline in the middle of the night.

## Environment
**OS: Ubuntu Server 20.04
**CPU architecture:** x86_64
**How docker service was installed: docker repo
**Docker Version: Docker version 19.03.13, build 4484c46d9d

## Command used to create docker container (run/create/compose/screenshot)
https://i.imgur.com/1Gytpx5.png

## Docker logs
docker logs swag: https://pastebin.facewan.com/?698b3fb8da3aba89#EzKt2Kj3AqiqRCDCgLDUViySr3vdKAzmy6p3nnfGZEhz
Logs from inside Portainer (shows the address issues): https://pastebin.facewan.com/?3a563e2b3b28d9fb#7XMxY3hXSjCm9toUcVGFUeo71Mosak4mD6WoW1kuuLu1

**Comment by aptalca** [comment]
```
nginx killed (pid 1302),
nginx killed (pid 1303),
```
same pids repeating suggests that 2 nginx workers had a hard crash during restart (likely after logrotate, or maybe cert renewal) and even our [pkill attempt](https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/root/etc/services.d/nginx/run#L4) fails so it tries over and over again.

It's technically an upstream issue (the workers should not hard crash when attempted to restart) but we'll add a stronger kill attempt and see if that helps
