### ISSUE TITLE
[BUG]  nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3

### ISSUE THREAD

**Issue by Vegardbeider** [linuxserver/docker-swag#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Server started after update and gives this error to the log.

nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3

Tried restarting the container, but no changes. This error results in the nginx server not working, not redirecting any of my requests. 

### Expected Behavior

Startsup and says server ready,  no errors.

### Steps To Reproduce

1. Latest update to swag docker container on Unraid-OS
2. Start the container
3. Open log file

### Environment

```markdown
- OS: Unraid 6.11.3
- How docker service was installed: Using the community applications
```

### CPU architecture

x86-64

### Docker creation

```bash
Using the latest repo. linuxserver/swag
```

### Container logs

```bash
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3

Repeating this error
```

**Comment by j0nnymoe** [comment]
Dupe https://github.com/linuxserver/docker-swag/issues/320 https://github.com/linuxserver/docker-swag/issues/319 https://github.com/linuxserver/docker-swag/issues/318 https://github.com/linuxserver/docker-swag/issues/316

Learn to search issues correctly.
