### ISSUE TITLE
[BUG] <title>stream

### ISSUE THREAD

**Issue by fithwum** [linuxserver/docker-swag#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3

### Expected Behavior

should just work

### Steps To Reproduce

start the docker

### Environment

```markdown
- OS:unraid
- How docker service was installed:the apps tab
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='swag'
  --net='proxynet'
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="N/A"
  -e HOST_CONTAINERNAME="swag"
  -e 'EMAIL'='N/A'
  -e 'URL'='N/A'
  -e 'SUBDOMAINS'='nextcloud,'
  -e 'ONLY_SUBDOMAINS'='true'
  -e 'VALIDATION'='http'
  -e 'DNSPLUGIN'=''
  -e 'EXTRA_DOMAINS'=''
  -e 'STAGING'='false'
  -e 'DUCKDNSTOKEN'=''
  -e 'PROPAGATION'=''
  -e 'PUID'='99'
  -e 'PGID'='100'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='https://[IP]:[PORT:443]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver-ls-logo.png'
  -p '80:80/tcp'
  -p '443:443/tcp'
  -v '/mnt/user/appdata/swag':'/config':'rw'
  --cap-add=NET_ADMIN 'linuxserver/swag'
```

### Container logs

```bash
no such file
```

**Comment by bpoulliot** [comment]
Having the same issue. If you're looking for a workaround @fithwum, I swapped back to 1.32.0 without luck so went back even further and found that `1.32.0-ls172` worked without modifying my config. The breaking change listed did not mention any config requirements for general use.

**Comment by HannesJo0139** [comment]
The new Alpine version looks for stream configs (*.conf) in `/etc/nginx/stream.d/`. So setting up a bind mount to include your configs there should work. Just keep in mind that swag is not gonna check its permissions and stuff. Bit of a dirty workaround though.

https://gitlab.alpinelinux.org/alpine/aports/-/commit/8f85c54baa60128af2da6b1ee32699b3a265cc38
