### ISSUE TITLE
[BUG] <Unable to generate certificate>

### ISSUE THREAD

**Issue by zasl** [linuxserver/docker-swag#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.

### Expected Behavior

ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.

### Steps To Reproduce

Unable to generate certificate

### Environment

```markdown
- OS:debian11
- How docker service was installed:
apt remove docker docker-engine docker.io
apt install ca-certificates curl gnupg lsb-release
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
chmod a+r /etc/apt/keyrings/docker.gpg
apt update
apt install docker-ce docker-ce-cli containerd.io docker-compose-plugin
```

### CPU architecture

arm64

### Docker creation

```bash
---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - URL=xxx.eu.org
      - VALIDATION=dns 
      - SUBDOMAINS=wildcard 
      - CERTPROVIDER=zerossl
      - DNSPLUGIN=cloudflare 
      #- PROPAGATION= #optional
      - EMAIL=xxx@outlook.com 
      - ONLY_SUBDOMAINS=false 
      - EXTRA_DOMAINS= 
      - STAGING=false 
    volumes:
      - /docker_date/swag/config:/config
      - /docker_date/swag/swag-ssl:/swag-ssl
      - /docker_date/swag/letsencrypt:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80 #optional
    networks:
      - swag 
    restart: unless-stopped
networks:   
  swag:
    external: true
```

### Container logs

```bash
docker logs swag
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

using keys found in /config/keys
rm: cannot remove '/etc/letsencrypt': Resource busy
Variables set:
PUID=1000
PGID=1000
TZ=Asia/Shanghai
URL=xxx.eu.org
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
CERTPROVIDER=zerossl
DNSPLUGIN=cloudflare
EMAIL=xxx@outlook.com
STAGING=false

ZeroSSL is selected as the cert provider, registering cert with xxx@outlook.com
SUBDOMAINS entered, processing
Wildcard cert for xxx.eu.org will be requested
E-mail address entered: xxx@outlook.com
dns validation via cloudflare plugin is selected
Retrieving EAB from ZeroSSL
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for *.xxx.eu.org and xxx.eu.org
Waiting 10 seconds for DNS changes to propagate

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/xxx.eu.org/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/xxx.eu.org/privkey.pem
This certificate expires on 2023-04-27.
These files will be updated when the certificate renews.
NEXT STEPS:
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```

**Comment by j0nnymoe** [comment]
Remove the `/etc/letsencrypt` volume. We don't tell you to add that anywhere.

**Comment by zasl** [comment]
> Remove the `/etc/letsencrypt` volume. We don't tell you to add that anywhere.

Thank you very much for your help. After I commented out the line, it has started successfully, but why it cannot start after mounting this directory

**Comment by zasl** [comment]
Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/xxx.eu.org/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/xxx.eu.org/privkey.pem
This certificate expires on 2023-04-28.
These files will be updated when the certificate renews.
NEXT STEPS:
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
New certificate generated; starting nginx
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[custom-init] No custom files found, skipping...
[ls.io-init] done.
2023-01-28 10:06:07,780 fail2ban.configreader   [345]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
Server ready


But there is no file in the swag-ssl directory, is this normal?

**Comment by aptalca** [comment]
Stop mapping random folders. `/swag-ssl` is not a recognized or used path for this image so of course there is nothing in there.

**Comment by drizuid** [comment]
OP is just not following the readme, this is not a bug, it's pebkac
