### ISSUE TITLE
[Feature Request] Individual Cert for Each Subdomain

### ISSUE THREAD

**Issue by ma-karai** [linuxserver/docker-swag#33]
Hey Guys,
The issue I am having is that I have two domains that are served utilizing SWAG one for plex and one with a personal blog that contains sensitive information. When you check the SSL certificate for each of the domains both domains are listed in the SSL chain. It would be great if SWAG creates for each subdomain an individual SSL Cert.

I basically run my docker command using these ENV vars
```
-e URL=myplexdomain.url 
-e EXTRA_DOMAINS= myblogdomain.url 
```

**Comment by tobbenb** [comment]
As far as I know we have no plans to create multiple certs.

I don't really understand why you would need two different certs either?

**Comment by nemchik** [comment]
If you were to use cloudflare for DNS you can have them act as an additional proxy and apply a certificate. The certificate applied should not reveal each additional domain.

**Comment by ma-karai** [comment]
> As far as I know we have no plans to create multiple certs.
> I don't really understand why you would need two different certs either?

Well, I thought it is quite obvious but when you have an SSL cert for multiple domains you might leak information about the owner of both domains.

**Comment by aptalca** [comment]
Let's Encrypt publicly publishes all domains that they provide certs for in a list. None of that is private info. Your dns records are also public. A simple reverse ip lookup easily reveals all the domains running on the same server.

**Comment by ma-karai** [comment]
thats correct, however,  it does not link domainA and domainB to the same owner.

**Comment by nemchik** [comment]
I don't think this conversation is going to be productive. We have reviewed and discussed this functionality previously:

https://github.com/linuxserver/docker-letsencrypt/issues/479
https://github.com/linuxserver/docker-letsencrypt/issues/443
https://github.com/linuxserver/docker-letsencrypt/issues/302
https://github.com/linuxserver/docker-letsencrypt/issues/117
https://github.com/linuxserver/docker-letsencrypt/pull/115

Setting up the nginx configs to accommodate this would be very intricate and could require end users to jump through some hoops. You may be interested in https://blog.linuxserver.io/2019/09/14/customizing-our-containers/ which would allow you to make it do whatever suits you.

**Comment by ma-karai** [comment]
Thank you for looking into it. Cheers
