### ISSUE TITLE
Update fail2ban.local for "allowipv6" option

### ISSUE THREAD

**Issue by NBPub** [linuxserver/docker-swag#335]
## Log Issue

              Got this on startup of an existing container:
```
swag  | 2023-01-21 10:26:34,008 fail2ban.configreader   [380]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
```

_Originally posted by @thespad in https://github.com/linuxserver/docker-swag/issues/315#issuecomment-1399223984_

## fail2ban

I am getting this on startup, and have seen it in recent logs from other issues. I looked through the changelog for [fail2ban 1.02](https://github.com/fail2ban/fail2ban/blob/1.0.2/ChangeLog) and found this:

> fail2ban.conf: new fail2ban configuration option allowipv6 (default auto), can be used to allow or disallow IPv6 interface in fail2ban immediately by start (e. g. if fail2ban starts before network interfaces), gh-2804

## Possible Fix?

Add ipv6 option to [fail2ban.local](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/fail2ban/fail2ban.local)

`allowipv6 = auto` or `allowipv6 = yes`

This should suppress the warning at startup. It could also be something that's configured via environmental variable. I tried adding this to **jail.local**, but still got the warning.

**Comment by drizuid** [comment]
This is not an error and can be ignored. We have no plans to change this from using the default of auto
