### ISSUE TITLE
Add Sentry selfhosted config sample

### ISSUE THREAD

**Issue by akarabach** [linuxserver/docker-swag#341]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add proxy sample for https://github.com/getsentry/self-hosted

### Reason for change

Sentry is popular

**Comment by Roxedus** [comment]
Proxy samples are not subject to this repo. They are sourced from [https://github.com/linuxserver/reverse-proxy-confs](https://github.com/linuxserver/reverse-proxy-confs).
