### ISSUE TITLE
[BUG] insufficient worker threads for certbot validation

### ISSUE THREAD

**Issue by jelinj8** [linuxserver/docker-swag#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using swag to create Letsencrypt certificate (http authentication) fails on validation with timeout on random subdomain(s) of the list. Failing subdomains change between attempts, sometimes one, sometimes 7 of 12...

I have 12 subdomains, disabled main domain certificate, ports forwarded correctly, no additional firewall.
It used to work out of the box, started to fail after adding another domain (thus renewing the cert).

Fixed by raising worker_processes from 4 to 10 in config/nginx/worker_processes.conf - it might even not be a bug, but it'd help to get a hint about an error like this.

### Expected Behavior

validate correctly without digging details.

### Steps To Reproduce

create container (docker-compose) with multiple subdomains

docker-coimpose up

validation fails with timeouts.

### Environment

```markdown
- OS:Debian 11, Odroid H3, 64G RAM (NVMe storage + HDD in raid1)
- How docker service was installed:
docker repository https://docs.docker.com/engine/install/debian/#install-using-the-repository
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=10000
      - PGID=998
      - TZ=Europe/Prague
      - URL=bliksoft.cz
      - VALIDATION=http
      - SUBDOMAINS=sub1,sub2,...,sub12 #optional
#      - CERTPROVIDER= #optional
#      - DNSPLUGIN=cloudflare #optional
#      - PROPAGATION= #optional
      - EMAIL=****@gmail.com #optional
      - ONLY_SUBDOMAINS=true #optional
#      - EXTRA_DOMAINS= #optional
#      - STAGING=false #optional
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
```

### Container logs

```bash
swag    | Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
swag    |   Domain: zm.bliksoft.cz
swag    |   Type:   connection
swag    |   Detail: 90.176.193.38: Fetching http://zm.bliksoft.cz/.well-known/acme-challenge/jRrz34dRVHAgD6NE0HHk6wxGGbJKSOps8SJY8RpYvU8: Timeout during connect (likely firewall problem)
swag    |
swag    | Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.
```

**Comment by nemchik** [comment]
I don't have a specific answer, but it sounds like modifying the worker processes is a workable solution. worker processes it set by default by detecting the number of cpu cores your system has using `nproc`. Setting this too high can cause issues. I would start by maybe doubling the number you see when running `docker exec swag nproc` (in your case, try `8`, since the default detected was `4`). You can increase it more if required, just be mindful that it could cause other issues if you have it set too high.

Alternatively, if you can use dns validation, i would recommend this over http validation any day. I would also recommend using wildcard certs rather than subdomain specific certs (which can only be done with dns validation).

**Comment by aptalca** [comment]
I don't know how you deduced the number of workers was the culprit but it is highly unlikely as the certbot http validation does not rely on nginx here. Certbot puts up its own temporary webserver during http validation. Nginx isn't even running at that time

**Comment by jelinj8** [comment]
Not using nginx for validation would explain the empty nginx logs, OK. In that case it might be just a coincidence that it worked. Other systems just configure nginx to serve the .well_known folder via nginx or let certbot to configure nginx for the validation, that is why I thought that it might be relevant.
It was working before without the change, only difference is that now there are running a couple more docker images on the host (HomeAssistant + supplementary systems instead of whole HomeAssistantOS as a libvirt/qemu virtual) and using docker-compose instead of docker CLI (with the same parameters including networking setup).
I'd like to use DNS + wildcard certificate, but I have my domain at czech Wedos, they have some API, but don't seem to be supported at the moment. Maybe later I'd try to implement/configure it that way, but as it is just my home automation system, I don't expect the domains changing too often.

**Comment by aptalca** [comment]
> Other systems just configure nginx to serve the .well_known folder via nginx or let certbot to configure nginx for the validation, that is why I thought that it might be relevant.

We opted for using certbot's webserver because our nginx confs are user configurable and we didn't want the users to customize the config and break cert renewals

> I'd like to use DNS + wildcard certificate, but I have my domain at czech Wedos

Domain registrar and the dns provider can be separate. We recommend Cloudflare for dns, it's a much better dns service then what most registrars provide

**Comment by jelinj8** [comment]
Wedos is a huge provider with good services and I have more than the domain there (VPS, hosting...), so nothing against Cloudflare, but I'm stayng local, maybe I'll try to contribute with the API implementation in the future.
To stay on topic - I'm still not sure what caused the problem, as there were no logs even from Certbot on the failed attempts except for the timeout error message on console. It might even be some network glitch, I don't know how long it waits for response, but it was failing quite quickly (I think under 10sec). If the worker count isn't relevant to http validation, lets close this issue, I'll see on next renewal...

**Comment by nemchik** [comment]
If you decide to attempt to implement a way to use Wedos with certbot, i would recommend checking out https://github.com/infinityofspace/certbot_dns_duckdns (a 3rd party plugin) or https://github.com/certbot/certbot/tree/master/certbot-dns-cloudflare (official plugin) and consider making and publishing (to pypi) a plugin for certbot. We could include it in the image.
