### ISSUE TITLE
Problem using the variable FILE__DUCKDNSTOKEN

### ISSUE THREAD

**Issue by GeoCookie** [linuxserver/docker-swag#35]
Hi there,

Currently, I got my swag container working like a charm. I am using a wildcard certificate with DuckDNS validation. My DuckDNS token is defined in my portainer stack (working like a docker-compose file).
I would like to put it in a file and use the variable FILE__DUCKDNSTOKEN to pass the content to swag but I cannot get it to work.

I am using this method with my openldap and authelia containers.

Please find information about the problem and my environment. I hope I haven't forgotten anything

## Expected Behavior
Swag reads the content of the file defined in FILE__DUCKDNSTOKEN and generate the certificate.

## Current Behavior
Swag fails at the DNS verification step. The error says the TXT record is incorrect and asks me to check my DuckDNS token.
The volume is correctly mounted in swag and the file is readable.
![image](https://user-images.githubusercontent.com/43962716/99061757-51121000-25a2-11eb-80f6-13f6b5576f28.png)

## Steps to Reproduce
Create a file /root/docker/secrets/swag/DUCKDNSTOKEN and write my DUCKDNSTOKEN inside.
Open my portainer stack
Add a volume to my swag service
--> add: `- /root/docker/secrets/swag:/run/secrets`
Replace the env variable DUCKDNSTOKEN by FILE__DUCKDNSTOKEN
--> replace: `-DUCKDNSTOKEN=ABCDEF...`
--> by: `FILE__DUCKDNSTOKEN=/run/secrets/DUCKDNSTOKEN`
Deploy the container

## Environment
Debian 10 running on a Hyper-V virtual machine (4 vCPU / 4Gb RAM)
x64 arch
Docker has been installed via the official repository (apt)
I use Portainer CE v2 to deploy my containers through stacks

## Command used to create docker container (run/create/compose/screenshot)
Here is my stack

![image](https://user-images.githubusercontent.com/43962716/99061235-866a2e00-25a1-11eb-8360-ab668ff1f732.png)

## Docker logs
Here is swag logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[env-init] DUCKDNSTOKEN set from FILE__DUCKDNSTOKEN
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=1000
PGID=1000
TZ=Europe/Paris
URL=XXX
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=duckdns
DNSPLUGIN=
EMAIL=XXX
STAGING=

SUBDOMAINS entered, processing
Wildcard cert for XXX will be requested
E-mail address entered: XXX
duckdns validation is selected
the resulting certificate will only cover the subdomains due to a limitation of duckdns, so it is advised to set the root location to use www.subdomain.duckdns.org
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for XXX
Running manual-auth-hook command: /app/duckdns-txt
Output from manual-auth-hook command duckdns-txt:
OKsleeping 60

Error output from manual-auth-hook command duckdns-txt:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     2    0     2    0     0      2      0 --:--:-- --:--:-- --:--:--     2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: &txt=XXX

Waiting for verification...
Challenge failed for domain XXX
dns-01 challenge for XXX
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: XXX
   Type:   unauthorized
   Detail: Incorrect TXT record
   "XXX" found at
   _acme-challenge.XXX

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
ERROR: Cert does not exist! Please see the validation error above. Make sure your DUCKDNSTOKEN is correct.
```

**Comment by aptalca** [comment]
Your secret has a trailing newline. Use printf to write it as described in the docker docs: https://docs.docker.com/engine/reference/commandline/secret_create/#create-a-secret

**Comment by GeoCookie** [comment]
Wow thank you!

For my culture, have you seen it on the logs or you guessed it because it's a common mistake?

**Comment by aptalca** [comment]
curl error `curl: (6) Could not resolve host: &txt=XXX` suggested the address was being broken up, also we've encountered the trailing newline issue with secrets before, so it was a combo this time

**Comment by GeoCookie** [comment]
Ok, thank you for your feedback. I will go to bed less dumb tonight 😄
