### ISSUE TITLE
[BUG] Invalid credentials when accessing services through SWAG

### ISSUE THREAD

**Issue by 15rhema** [linuxserver/docker-swag#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When accessing a web application (Mealie v0.5.6) via local network, authentication within the app works as expected. Accessing via the proxy gives "Invalid credentials" authentication errors. 

There is a similar issue that I found on the Mealie github that mentions nginx proxy manager settings as a possible solution or work around, but I'm unsure of what to adjust in SWAG. Here is the issue: https://github.com/hay-kot/mealie/issues/1845

### Expected Behavior

Authentication should work via the proxy. 

### Steps To Reproduce

Mealie v0.5.6 running through SWAG reverse proxy. 
Attempt to authenticate via the proxied site
Receive "Invalid Credentials"

### Environment

```markdown
- OS: Unraid 6
- How docker service was installed: Unraid docker community apps
```

### CPU architecture

x86-64

### Docker creation

```bash
docker settings: https://imgur.com/a/9ZeP1Wy
```

### Container logs

```bash
No e-mail address entered or address invalid
dns validation via duckdns plugin is selected
Certificate exists; parameters unchanged; starting nginx
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
/config/nginx/geoip2.conf exists.
        Please migrate to https://github.com/linuxserver/docker-mods/tree/swag-maxmind
/config/nginx/ldap.conf exists.
        Please apply any customizations to /config/nginx/ldap-server.conf
        Ensure your configs are updated and remove /config/nginx/ldap.conf
        If you do not use this config, simply remove it.
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2020-06-02 │ 2022-08-20 │ /config/nginx/ldap-server.conf                                         │
│ 2020-05-31 │ 2023-02-09 │ /config/nginx/authelia-location.conf                                   │
│ 2020-05-31 │ 2023-02-09 │ /config/nginx/authelia-server.conf                                     │
│ 2020-10-04 │ 2023-02-09 │ /config/nginx/proxy.conf                                               │
│ 2022-09-08 │ 2023-02-05 │ /config/nginx/proxy-confs/mealie.subdomain.conf                        │
│ 2022-10-03 │ 2023-02-09 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
**** installing docker and docker compose ****
Copying over docker and docker-compose binaries
**** Please map /var/run/docker.sock for access to docker service on host. Alternatively you can manually define a remote host address with the docker cli option -H ****
**** Adding swag-auto-reload deps to package install list ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
(1/2) Installing inotify-tools-libs (3.22.6.0-r0)
(2/2) Installing inotify-tools (3.22.6.0-r0)
Executing busybox-1.35.0-r29.trigger
OK: 207 MiB in 207 packages
[custom-init] No custom files found, skipping...
MOD Auto-reload: Watching the following files/folders for changes (excluding .sample and .md files):
/config/nginx
[ls.io-init] done.
Server ready
```

**Comment by aptalca** [comment]
Update the confs mentioned in the log and see if it fixes it

**Comment by 15rhema** [comment]
> 

Thanks for the tip, but that doesn't seem to have helped. Here is the updated logs:

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Variables set:
PUID=99
PGID=100
TZ=America/Los_Angeles
URL=*****.duckdns.org
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=duckdns
EMAIL=
STAGING=false

the resulting certificate will only cover the subdomains due to a limitation of duckdns, so it is advised to set the root location to use www.subdomain.duckdns.org
Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Wildcard cert for only the subdomains of  ******.duckdns.org will be requested
No e-mail address entered or address invalid
dns validation via duckdns plugin is selected
Certificate exists; parameters unchanged; starting nginx
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
/config/nginx/geoip2.conf exists.
        Please migrate to https://github.com/linuxserver/docker-mods/tree/swag-maxmind
**** installing docker and docker compose ****
**** docker and docker-compose already installed, skipping ****
**** Please map /var/run/docker.sock for access to docker service on host. Alternatively you can manually define a remote host address with the docker cli option -H ****
**** swag-auto-reload deps already installed, skipping ****
[custom-init] No custom files found, skipping...
MOD Auto-reload: Watching the following files/folders for changes (excluding .sample and .md files):
/config/nginx
[ls.io-init] done.
Server ready
