### ISSUE TITLE
[FEAT] host: command not found, request to include bind9-host

### ISSUE THREAD

**Issue by schumi2004** [linuxserver/docker-swag#355]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I got SWAG running with fail2ban active and maxmind mod enabled. 
Now I would like to exclude google from being banned/blocked as described here: https://forum.cleavr.io/t/ignore-google-bots-on-fail2ban/306
I'm not going to use it for the same purpose but i want to exclude/allow Google assistant request to my homeassistant instance and block the rest.
For the scrip to work host command is needed which currently is not present.

### Reason for change

I installed Maxmind mod with a GEO whitelist for my own country but don't want to expose all the countries google is located in and might communicate from towards my HA instance.
Also keeping track of all the subnets google is using is a time consuming job so using script mentioned earlier would make it more simple.

I might beable to install the module myself but it will probably overwritten with a new container update.
From my point of view it could be useful for others aswell if they want to script something similiar unless there is a different approach that accomplish the same thing?

### Proposed code change

include bind9-host in image.

**Comment by schumi2004** [comment]
Followed instructions but it gives errors when installing bind9 package, is there a conflict with other mods maybe?

/config/nginx
./run: line 15: inotifywait: command not found
nginx: [emerg] unknown directive "lua_package_path" in /etc/nginx/http.d/crowdsec_nginx.conf:1
MOD Auto-reload: Watching the following files/folders for changes (excluding .sample and .md files):
/config/nginx
./run: line 15: inotifywait: command not found
nginx: [emerg] unknown directive "lua_package_path" in /etc/nginx/http.d/crowdsec_nginx.conf:1
MOD Auto-reload: Watching the following files/folders for changes (excluding .sample and .md files):
/config/nginx
./run: line 15: inotifywait: command not found
nginx: [emerg] unknown directive "lua_package_path" in /etc/nginx/http.d/crowdsec_nginx.conf:1
MOD Auto-reload: Watching the following files/folders for changes (excluding .sample and .md files):
/config/nginx
./run: line 15: inotifywait: command not found
nginx: [emerg] unknown directive "lua_package_path" in /etc/nginx/http.d/crowdsec_nginx.conf:1
MOD Auto-reload: Watching the following files/folders for changes (excluding .sample and .md files):
/config/nginx
./run: line 15: inotifywait: command not found
nginx: [emerg] unknown directive "lua_package_path" in /etc/nginx/http.d/crowdsec_nginx.conf:1
MOD Auto-reload: Watching the following files/folders for changes (excluding .sample and .md files):
/config/nginx
./run: line 15: inotifywait: command not found
nginx: [emerg] unknown directive "lua_package_path" in /etc/nginx/http.d/crowdsec_nginx.conf:1

**Comment by thespad** [comment]
You'd need to provide the full container logs, looks like something hasn't installed properly.

**Comment by schumi2004** [comment]
Thanks for your quick reply.  
Apparently I tried to install the wrong package Ubuntu instead of Alpine linux package.
My appologies ;)
