### ISSUE TITLE
Allow wildcard sub-sub-domains and sub-domains together

### ISSUE THREAD

**Issue by skylord123** [linuxserver/docker-swag#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I expected placing `*,*.test` in the sub-domains would give me `*.example.com` and `*.test.example.com` but it actually iterates all files in the directory and will instead give you a sub-domain for each file (because * in bash iterates files in the current directory). I tried using just `wildcard` for the sub-domains but this makes my sub-sub-domains not work (such as yay.test.example.com).

It would be nice if I could define `wildcard,*.test` to achieve what I want (to avoid the `*` from iterating files in the current directory).

## Current Behavior

Well currently the only way I found to get this working is to define every sub-domain in my sub-domain list but then add `*.test` as another sub-domain. This works but I want my sub-domains to be wildcard as well.

## Steps to Reproduce

1. Select a DNS provider like cloudflare or the such so you can do wildcard certs
2. Set the sub-domains to `*,*.test`
3. Watch the logs as the sub-domain list gets filled with filenames from the current directory of the running script

## Environment
**OS:** Unraid
**CPU architecture:** x86_64
**How docker service was installed:**

Installed via CA in Unraid

## Command used to create docker container (run/create/compose/screenshot)

Created via UI

## Docker logs

I'm not going to include my log. It literally dumped a sub-domain list of all my files in my www directory and going through to remove all my personal information from that would make the log useless anyways.

If a log is absolutely necessary please mention it and I can send it over email privately.

**Comment by skylord123** [comment]
It would be great to be able to specify `*.*,*` for the sub-domains so you cover all first and second level sub-domains (or however deep the user wants to go).

**Comment by Roxedus** [comment]
This is not our restriction, it is letsencrypts restriction, its not something we can support.

You want to use the extra_domains variable to escape globbing and use * if you want *.test.example.com. This is why our readme explicit call out that you need to use "wildcard" as the subdomain.

**Comment by skylord123** [comment]
Ah you are right. `*.*.example.com` is not valid. I should have known better.

I also missed the EXTRA_DOMAINS variable. For some reason I thought it was only for top-level domains.

It may be a good idea to explain that `wildcard` doesn't support sub-sub-domains in the readme and that those need to be defined separately in the `EXTRA_DOMAINS`.

**Comment by Ozzah** [comment]
So if we don't necessarily need `*.*.example.com` but we want, say, `*.example.com` and `*.server1.example.com` and `*.server2.example.com`, then how can that be achieved?

I just set up:
```
 - URL=example.com
 - EXTRA_DOMAINS=server1.example.com,server2.example.com
 - SUBDOMAINS=wildcard
 - VALIDATION=dns
 - DNSPLUGIN=cloudflare
```

and I got the following error:

> Requesting a certificate for *.example.com and 2 more domains
> An unexpected error occurred:
> The request message was malformed :: Error creating new order :: Domain name "server1.example.com" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.

**Comment by j0nnymoe** [comment]
`EXTRA_DOMAINS=*.server1.example.com,*.server2.example.com` should do it.
