### ISSUE TITLE
[BUG] SSL certificates wrong link on Docker Desktop for Windows + Hyper-V

### ISSUE THREAD

**Issue by raidenlal** [linuxserver/docker-swag#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Nginx won't start.
 During start-up SWAG creates links in /config/keys:

- lrwxr-xr-x 1 root root 1067 Apr 10 18:15 cert.crt -> ./letsencrypt/fullchain.pem
- lrwxr-xr-x 1 root root 1067 Apr 10 18:15 cert.key -> ./letsencrypt/privkey.pem

However inside ./letsencrypt directory there are differently named files:

- -rwxr-xr-x 1 root root  692 May  8  2021 README
- -rwxr-xr-x 1 root root    0 Apr 10 18:15 priv-fullchain-bundle.pem

Seems like the link is wrong. Any ideas how to fix this? This was working before I migrated to Hyper-V (I was not able to solve vmmem memory leaks).

### Expected Behavior

Nginx is able to read certificates.

### Steps To Reproduce

Install SWAG in Docker Desktop for Windows using Hyper-V

### Environment

```markdown
- OS: Windows 10, using Hyper-V
- How docker service was installed: Docker Desktop
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run --name=nginx -v C:/Nginx:/config -d linuxserver/swag:latest
```

### Container logs

```bash
2023-04-10 18:11:55 nginx: [emerg] SSL_CTX_load_verify_locations("/config/keys/cert.crt") failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/config/keys/cert.crt, r) error:10000080:BIO routines::no such file error:05880002:x509 certificate routines::system lib)
2023-04-10 18:11:56 nginx: [emerg] SSL_CTX_load_verify_locations("/config/keys/cert.crt") failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/config/keys/cert.crt, r) error:10000080:BIO routines::no such file error:05880002:x509 certificate routines::system lib)
```

**Comment by j0nnymoe** [comment]
Likely something docker desktop is doing that's breaking it. We do not test nor recommend docker desktop for deploying our containers. If you must windows as a host, setup Ubuntu within WSL2 and install docker then use Linux folder paths. 

Also note you're missing a lot of the ENV's for swag as well in your docker run command.

**Comment by nemchik** [comment]
FYI the symlinks are created based on where certbot should put the certs once it generates them. If certbot does not generate the certs the symlinks would be broken.

**Comment by raidenlal** [comment]
After trying out multiple things I have hit letsencrypt rate limiter, however I there is this flag "only subdomains" which changes request to letsencrypt and then I had another 5 attempts. After clearing everything and running again, it went through. I am not sure why or how the symlinks got broken, but now fixed. Sorry about this ticket.
