### ISSUE TITLE
DYNADOT DNS Configuration

### ISSUE THREAD

**Issue by SheikhTalal** [linuxserver/docker-swag#368]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Can you please add dynadot to the dns provider?

### Reason for change

I found all  common providers like, netcup, cloudflare, godaddy... but unfortunately I couldn't make the one for dynadot.com

### Proposed code change

I am newbie and I don't know much but I love using SWAG

**Comment by Roxedus** [comment]
There is no dynadot certbot-dns-plugin.

We cannot support dynadot until this is in place.
