### ISSUE TITLE
[BUG] container died very soon

### ISSUE THREAD

**Issue by Leefurmore** [linuxserver/docker-swag#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use docker run to start the container, it stopped very soon.

### Steps To Reproduce

Please see below, thanks.

### Environment

```markdown
- OS: openwrt 5.15.106
- Docker version 20.10.22, build 3a2c30b
- install docker via openwrt-software-install
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=swag \
  --cap-add=NET_ADMIN \
  --net=macvlan \
  --ip=192.168.0.45 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Asia/Shanghai \
  -e URL=leefurmore.com.cn \
  -e VALIDATION=dns \
  -e SUBDOMAINS=chat,cloud `#optional` \
  -e CERTPROVIDER= `#optional` \
  -e DNSPLUGIN=aliyun `#optional` \
  -e PROPAGATION= `#optional` \
  -e EMAIL=junenever@gmail.com `#optional` \
  -e ONLY_SUBDOMAINS=false `#optional` \
  -e EXTRA_DOMAINS= `#optional` \
  -e STAGING=false `#optional` \
  -p 3443:443 \
  -p 6780:80 `#optional` \
  -v /opt/docker/appdata/swag:/config \
  --restart unless-stopped \
  linuxserver/swag
```

### Container logs

```bash
stderr: mkdir: cannot create directory ‘/var/lib/nginx’: Not supported
stderr: s6-rc: warning: unable to start service init-folders: command exited 1
stderr: /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
stderr: /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
stdout: [migrations] started
stdout: [migrations] 01-nginx-site-confs-default: skipped
stdout: [migrations] done
stdout: usermod: no changes
```

**Comment by Roxedus** [comment]
Missing information on the docker installation

**Comment by Leefurmore** [comment]
> Missing information on the docker installation

I don't understand what does it mean?

**Comment by nemchik** [comment]
> > Missing information on the docker installation
> 
> I don't understand what does it mean?

![image](https://github.com/linuxserver/docker-swag/assets/725456/e3051b8f-a87d-4ceb-b548-a497ad16c60a)

**Comment by Leefurmore** [comment]
- Docker version 20.10.22, build 3a2c30b
- install docker via openwrt-software-install

**Comment by Roxedus** [comment]
openwrt doesnt make it clear if the package configures rootless docker, do you know if that is the case?

**Comment by Leefurmore** [comment]
> openwrt doesnt make it clear if the package configures rootless docker, do you know if that is the case? 

I am not sure to this case, do you know what can I do?
