### ISSUE TITLE
[BUG] Certificate creation fails on cloudflare api when using over 5 subdomains

### ISSUE THREAD

**Issue by fentix** [linuxserver/docker-swag#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As soon as I try to generate a certificate with more than 5 subdomains from cloudflare the certificate generation fails.
_(When using over 8 subdomains, the errors in the logs change to something different than provided in the "Container Log" form)_
This is the same unfixed issue from the old linuxserver/docker-letsencrypt image.
https://github.com/linuxserver/docker-letsencrypt/issues/125

As soon as I remove the sixth or more entries from the subdomain list the certificate get generated without any problems.
I can't find any way, to implement and increase the "-dns-cloudflare-propagation-seconds", this seems to be the root cause for the error.

### Expected Behavior

Successful generation of Let's Encrypt Certificate for more than 5 Subdomains.

### Steps To Reproduce

1. create linuxserver swag container with docker-compose.
2. add cloudflare dns config with api token.
3. add more than 5 subdomains to the cloudflare certificate creation, (or over 8 to get two different error logs).
4. try to start the container.
5. remove one or more subdomains to have less than 5 in the cloudflare dns config.
6. try to start the container again.

The threshold amount of entries needed to reproduce both error messages (same cause) might differ regarding the current network quality.

### Environment

```markdown
- OS: Ubuntu 22.04 lts
- How docker service was installed: docker-compose file from linuxserver
- configured the dns-conf from cloudflare with api token
```

### CPU architecture

x86-64

### Docker creation

```bash
the default linuxserver.io docker-compose with own credentials
```

### Container logs

```bash
(exchanged private information)

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Sub-domains processed are:  -d sub1.domain.tld -d sub2.domain.tld -d sub3.domain.tld -d sub4.domain.tld -d sub5.domain.tld -d sub6.domain.tld
E-mail address entered: mail@example.com
dns validation via cloudflare plugin is selected
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for domain.tld and 6 more domains
live directory exists for domain.tld
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Could not read private key from -inkey file from privkey.pem
cat: privkey.pem: Is a directory
cat: fullchain.pem: Is a directory
New certificate generated; starting nginx
Could not read certificate from /config/keys/letsencrypt/fullchain.pem
Unable to load certificate
The cert is either expired or it expires within the next day. Attempting to renew. This could take up to 10 minutes.
<------------------------------------------------->

<------------------------------------------------->
cronjob running on Sat Jun  3 19:01:15 CEST 2023
Running certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/domain.tld.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewal configuration file /etc/letsencrypt/renewal/domain.tld.conf is broken.
The error was: renewal config file {} is missing a required file reference
Skipping.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
No renewals were attempted.

Additionally, the following renewal configurations were invalid: 
  /etc/letsencrypt/renewal/domain.tld.conf (parsefail)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
0 renew failure(s), 1 parse failure(s)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
[custom-init] No custom files found, skipping...
[ls.io-init] done.
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
2023-06-03 19:01:20,326 fail2ban.configreader   [388]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
Server ready
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
```

**Comment by aptalca** [comment]
There is an env var for propagation. In my case, if I add more than 6 or 7 arguments into extra domains, I need to bump it up to 20-30 sec for cloudflare instead of the default 10

**Comment by fentix** [comment]
@aptalca adding the environment var to the docker-compose file has not worked for me so far?
How did you implement it into the compose file?

**Docker compose change:**
`environment: - DNS-CLOUDFLARE-PROPAGATION-SECONDS=20`
**Result in the docker log after restarting the container:**
_"Waiting 10 seconds for DNS changes to propagate"_

**Comment by j0nnymoe** [comment]
If you read the readme, you'd see it's `PROPAGATION=` env.

**Comment by fentix** [comment]
Searched in the wrong readme.
@j0nnymoe you meant the [docker-swag README](https://github.com/linuxserver/docker-swag).
I was looking in the [dns-plugin README](https://github.com/certbot/certbot/blob/master/certbot-dns-cloudflare/certbot_dns_cloudflare/__init__.py#L20).
I'll test the behavior again.

**Comment by fentix** [comment]
Worked for me now.
It seems that I have been misled in the first place (the cloudflare dns config pointed me to the wrong readme and I did not realize the `propagation` in the swag readme was referring to that `DNS-CLOUDFLARE-PROPAGATION-SECONDS` value)

**Comment by aptalca** [comment]
Our docs only refer to the plugin readme for the ini contents, nothing else.

**Comment by fentix** [comment]
Like I said I have been misled by some readme.
I am not blaming anyone for that.

Regarding:
> "Our docs only refer to the plugin readme for the ini contents, nothing else."

I looked at the following places for Information:
1. Visited [SWAG setup on linuxserver.io](https://docs.linuxserver.io/general/swag). No mention regarding a `propagation ` or `dns-cloudflare-propagation-seconds` value. So I looked into the docker container logs
2. The SWAG Container logs said it's something related to the cloudflare DNS plugin. So I investigated the corresponding path in the persistent SWAG subfolder (`swag/dns-conf/cludflare.ini`). The config file there ` Instructions: https://github.com/certbot/certbot/blob/master/certbot-dns-cloudflare/certbot_dns_cloudflare/__init__.py#L20
Replace with your values` pointed me to the [certbot/certbot-dns-cloudflare/certbot_dns_cloudflare/__init__.py](https://github.com/certbot/certbot/blob/master/certbot-dns-cloudflare/certbot_dns_cloudflare/__init__.py#L20) which stated there must be an `dns-cloudflare-propagation-seconds` value.
3. So I started to I search for an implementation regarding the `dns-cloudflare-propagation-seconds` value on the search engine and found this old Issue [GitHub linuxserver/docker-letsencrypt | Add an environment variable for DNS propagation time #125](https://github.com/linuxserver/docker-letsencrypt/issues/125).
4. Since the ticket was closed and I appeared to have the same Issue I searched for the SWAG repository, searched the existing issues regarding my problem and found none. Then I created this current Issue.

And I missed the two places with a hint to the `propagation ` value.
1. The first one is the [Docker Hub | linuxserver/swag](https://hub.docker.com/r/linuxserver/swag).
2. The Second one is this repository [GitHub linuxserver/docker-swag](https://github.com/linuxserver/docker-swag).
Also because I thought the [SWAG setup on linuxserver.io](https://docs.linuxserver.io/general/swag) would have all Information needed.
