### ISSUE TITLE
[BUG] Can't use DNS cert validation, certbot package too old

### ISSUE THREAD

**Issue by Kurasami** [linuxserver/docker-swag#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to use DNS validation I get the error that the certbot package is too old.

### Expected Behavior

Certbot would use my Cloudflare token correctly to validate my DNS records.

### Steps To Reproduce

1. Run the docker compose and see the output

### Environment

```markdown
- OS: Docker
- How docker service was installed: docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
As above
```

### Container logs

```bash
Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.11.6)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```

**Comment by Kurasami** [comment]
> 

A human huh? Suuuuure.

**Comment by Roxedus** [comment]
Yes, I, a human marked it, because the log is incomplete, and there is no compose snippet. 

Nothing that is currently provided in the issue points to the package being out of date,

**Comment by j0nnymoe** [comment]
Also swag has the correct version of certbot: https://github.com/linuxserver/docker-swag/blob/b2e8d8c8ab37e7521cf27efd8264c3b1828bac98/package_versions.txt#L35

**Comment by osirisinferi** [comment]
Also, the error is *mentioning* the `cloudflare` Python package, not Certbot. And it's merely as verbose information, not the actual issue. As you can clearly see, the installed `cloudflare` package 2.11.6, which is more recent than the required 2.3.11. So no problem there.

You probably want to check your Cloudflare credentials for correctness.

**Comment by slattman** [comment]
getting /etc/s6-overlay/s6-rc.d/init-certbot-config/run: line 317: certbot: command not found on arm using dns with luadns
