### ISSUE TITLE
[FEAT] Install PHP calendar extension

### ISSUE THREAD

**Issue by pml-jpe** [linuxserver/docker-swag#388]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi, I would like to install calendar extension for PHP, can anyone tell me how to do it?
Thanks

### Reason for change

PHP calendar extension required

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by pml-jpe** [comment]
> https://github.com/linuxserver/docker-mods/tree/universal-package-install

Thanks, so it's correct to put following in docker-compose.yml file under environment: for swag?

`      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=php-calendar
`

**Comment by aptalca** [comment]
That's not the name of the package in the repo: https://pkgs.alpinelinux.org/packages?name=php*calendar&branch=v3.18&repo=&arch=x86_64&maintainer=
`php82-calendar`
