### ISSUE TITLE
Modify UnifiController sample configuration.

### ISSUE THREAD

**Issue by olivierdc94** [linuxserver/docker-swag#39]
Add following to unifi controller sample. Without this config I got WebSocket errors inside the app.

    location /wss/ {
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 86400;
        proxy_set_header Host $http_host;
    }

Docker version 19.03.8, build afacb8b7f0
Ubuntu 20.04.1 LTS x86_64
Unifi controller image from LinuxServer: https://hub.docker.com/r/linuxserver/unifi-controller

**Comment by Roxedus** [comment]
Update your configs. We changed how websockets gets handled. https://github.com/linuxserver/reverse-proxy-confs/issues/198

**Comment by nemchik** [comment]
After [updating configs](https://github.com/linuxserver/docker-swag#updating-configs), you should be able to use the included default proxy for unifi. We added global handling of websockets across all proxies by moving the lines to another file. Individual proxy samples no longer need to have special handling for websockets.

If you're still having trouble after [updating configs](https://github.com/linuxserver/docker-swag#updating-configs) feel free to let us know.
