### ISSUE TITLE
[BUG] Typo in README

### ISSUE THREAD

**Issue by jcgoette** [linuxserver/docker-swag#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Type in README.md

`supoprts`

### Steps To Reproduce

Read the README

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by nemchik** [comment]
Could you copy the whole sentence or line where you're seeing this as an issue?

**Comment by jcgoette** [comment]
> DuckDNS only supoprts two types of DNS validated certificates (not both at the same time):

**Comment by nemchik** [comment]
Thanks!
Fixed in https://github.com/linuxserver/docker-swag/pull/393
