### ISSUE TITLE
[FEAT] Allow mounting of arbitrary volumes

### ISSUE THREAD

**Issue by bambury** [linuxserver/docker-swag#395]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Currently all content needs to reside in /config/www, which means it needs to be in the same filesystem as the volume mounted as config. I would like to be able to add arbitrary volumes to the docker container.

### Reason for change

I'm running the container on a Raspberry Pi with limited storage on the OS filesystem, however I have data on other drives that I would like to make available via Swag.

**Comment by Roxedus** [comment]
You are free to do this already. You can mount `/config` and `/config/www` to different places. 

We also don't enforce the content to reside in `/config/www`, you can have it in a arbitrary folder like `/content` if you want, just make sure your nginx config is using this folder.

**Comment by bambury** [comment]
> You are free to do this already. You can mount `/config` and `/config/www` to different places.
> 
> We also don't enforce the content to reside in `/config/www`, you can have it in a arbitrary folder like `/content` if you want, just make sure your nginx config is using this folder.

I'm sorry, it must be a Portainer limitation then. For other containers, I have "Recreate" and "Duplicate/Edit" actions available, but I don't for Swag. I thought this was an intentional choice by Swag, but evidently it's not.

**Comment by bambury** [comment]
Just to understand who to ask: do you know who maintains the SWAG add-on for Kodi? That's my use case and there you can't configure a separate volume for /config/www

**Comment by aptalca** [comment]
@bambury you can add it to `Additional docker parameters (optional)` in the docker run format:
`-v /path/on/host:/path/in/container`
Make sure the folder is owned by user `nobody` on host (`65534:100`)

**Comment by bambury** [comment]
@aptalca 
Perfect, thank you! :)
