### ISSUE TITLE
[BUG] Unable to get cert via route53 via IAM role due to cli.ini

### ISSUE THREAD

**Issue by jordankoehn** [linuxserver/docker-swag#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On past releases of swag, I was able to comment out the lines in /config/dns-conf/route53.ini or even remove the file with an s6 mod. Doing so would cause certbot to use the ec2 instance IAM role.  However, on the newer releases of swag. This line in cli.ini causes certbot to fail.

`dns-route53-credentials=/config/dns-conf/route53.ini`

with this error

`certbot: error: unrecognized arguments: --dns-route53-credentials=/config/dns-conf/route53.ini`

I can modify `/etc/s6-overlay/s6-rc.d/init-certbot-config/run` in order to remove that line from the ini file which allows my cert to renew

### Expected Behavior

Cert should renew using ec2's IAM role

### Steps To Reproduce

run swag using route53

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose
```

### Container logs

```bash
`certbot: error: unrecognized arguments: --dns-route53-credentials=/config/dns-conf/route53.ini`
```

**Comment by nemchik** [comment]
I think I see the problem.
https://github.com/linuxserver/docker-swag/blob/66a86947721b595b62652b3cec1c5890f1067d44/root/etc/s6-overlay/s6-rc.d/init-certbot-config/run#L295-L298 should remove that line, but it's expecting spaces.
```ini
# expected
dns-route53-credentials = /config/dns-conf/route53.ini
# actual
dns-route53-credentials=/config/dns-conf/route53.ini
```
This should be an easy fix and I'll try to get it resolved tonight.

**Comment by nemchik** [comment]
Can you give `lspipepr/swag:2.6.0-pkg-34f2a8ff-dev-2b0bf5869cb09581d4c0cd666dd285556c47f4c2-pr-398` a try?

**Comment by jordankoehn** [comment]
It works! Thank you.
