### ISSUE TITLE
[FEAT] add support for namecheap dns provider

### ISSUE THREAD

**Issue by Maxim4711** [linuxserver/docker-swag#405]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Would it be possible to add certbot plugin for namecheap dns provider - https://github.com/iHamsterball/certbot-dns-namecheap.git ? I rebuilt docker image with this certbot plugin and it seems to work without any issue

### Reason for change

missing certbot plugin for namecheap dns provider

### Proposed code change

in Dockerfile add line with namecheap plugin:
  pip install -U --no-cache-dir --find-links https://wheel-index.linuxserver.io/alpine-3.18/ \
    certbot==${CERTBOT_VERSION} \
    certbot-dns-acmedns \
...
    certbot-dns-luadns \
    certbot-dns-namecheap \
    certbot-dns-netcup \

add root/defaults/dns-conf/namecheap.ini with following content

dns_namecheap_username=my-username
dns_namecheap_api_key=my-api-key

**Comment by nemchik** [comment]
Just as a note, https://pypi.org/project/certbot-dns-namecheap/ uses https://github.com/knoxell/certbot-dns-namecheap which was forked from the repo listed above. Shouldn't make any difference in our implementation.

This should be an easy add. I'll try to get it soon.

**Comment by drizuid** [comment]
@Maxim4711 are you still wanting this? We cannot merge until you test and verify.

**Comment by Maxim4711** [comment]
sorry for delay, was on vacation. Thanks for the work done, i tested your image and it worked as expected.

Here is the output from docker compose logs

swag  | ───────────────────────────────────────
swag  | GID/UID
swag  | ───────────────────────────────────────
swag  |
swag  | User UID:    1000
swag  | User GID:    1000
swag  | ───────────────────────────────────────
swag  |
swag  | Setting resolver to  127.0.0.11
swag  | Setting worker_processes to 4
swag  | generating self-signed keys in /config/keys, you can replace these with your own keys if required
swag  | ....+....+.........+.....+.+..............+.+......+.....+++++++++++++++++++++++++++++++++++++++*........+......+..+............+.+..............+.+..+...+.............+......+...+...+++++++++++++++++++++++++++++++++++++++*......+.+..+....+...+...+........+.......+..+.......+.....+...+...+.......+...........+.......+...+..+............+.......+...+...+..+...+....+...............+.........+.....+.+...+..+...+...+..........+.....+.........+......+..................+.......+...+.....+......+.........+.+.........+.....+....+...+........+......+.+........+......+.+..+.......+.........+..+...+.........+............+.+...+.....+............+...+....+...+.........+...+..+...............+.+...+.........+...........+....+.....+......+....+...........+.+......+.....+....+.....+.+............+..+....+..+.........+......+....+.....+...+......+.+...+...........+.+.....+...+............+.+...+......+...+...+.....+...+.......+.................+.+...........+...+..........+...+............+......+.....+......+..........+.....+.+..+...+..................+.......+...+......+...+..+......+....+........+...+...+......+..........+.....+.+..+.+............+..+..........+..+.+............+..+...+...............+.+.................+....+..............+......+.+...+...........+......+.......+...+...+.....+....+..+..........+........+.+............+.....+.........+.+..+..................+...+....+...........+............++++++
swag  | ......+.......+..+++++++++++++++++++++++++++++++++++++++*....+..........+......+.....+....+...+++++++++++++++++++++++++++++++++++++++*..........+.++++++
swag  | -----
swag  | # do daily/weekly/monthly maintenance
swag  | # min   hour    day     month   weekday command
swag  | */15    *       *       *       *       run-parts /etc/periodic/15min
swag  | 0       *       *       *       *       run-parts /etc/periodic/hourly
swag  | 0       2       *       *       *       run-parts /etc/periodic/daily
swag  | 0       3       *       *       6       run-parts /etc/periodic/weekly
swag  | 0       5       1       *       *       run-parts /etc/periodic/monthly
swag  | # renew letsencrypt certs
swag  | 8       2       *       *       *       /app/le-renew.sh >> /config/log/letsencrypt/letsencrypt.log 2>&1
swag  | Variables set:
swag  | PUID=1000
swag  | PGID=1000
swag  | TZ=Europe/Berlin
swag  | URL=********.net
swag  | SUBDOMAINS=wildcard
swag  | EXTRA_DOMAINS=
swag  | ONLY_SUBDOMAINS=false
swag  | VALIDATION=dns
swag  | CERTPROVIDER=
swag  | DNSPLUGIN=namecheap
swag  | EMAIL=
swag  | STAGING=
swag  |
swag  | Created .donoteditthisfile.conf
swag  | Using Let's Encrypt as the cert provider
swag  | SUBDOMAINS entered, processing
swag  | Wildcard cert for nexttry.net will be requested
swag  | No e-mail address entered or address invalid
swag  | dns validation via namecheap plugin is selected
swag  | Generating new certificate
