### ISSUE TITLE
[FEAT] systemd socket activation

### ISSUE THREAD

**Issue by virtorgan** [linuxserver/docker-swag#408]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Systemd socket activation does not work with Swag while it works with official NGINX image.

### Reason for change

Tendency is to evolve to rootless containers thus people move away from Docker to more secure rootless Podman.
Networking in rootless is slower due to the use of Slirp4netns which adds processing. other solution like [Netavark](https://github.com/containers/netavark) or [bypass4netns](https://github.com/rootless-containers/bypass4netns) still need processing time. the fastest (and maybe more secure) way would be to use socket activation of swag container.

### Proposed code change

official docker-nginx have already made the changes to allow socket activation. see https://github.com/nginxinc/docker-nginx/issues/702

Would be nice to get same modifications for swag.

**Comment by drizuid** [comment]
Unfortunately, we do not test or support podman. An enhancement like this would require someone with the understanding of our s6 init process to submit a fully functional PR that supports this while not impacting our target audience in any way. This is not something that we as a team plan to work on.
