### ISSUE TITLE
[FEAT] Revert deprecation of armhf platform if possible

### ISSUE THREAD

**Issue by dzett** [linuxserver/docker-swag#410]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I noticed that with PR #372 the docker builds for the armhf platform have been discontinued. 
I couldn't find the reasoning behind this, but the change implies that my running swag on raspbian no longer gets updated. In case this was just an optimization, I would kindly ask to take the armhf platform back up again... 

Thanks for your work!

### Reason for change

Existing armhf installs no longer get potentially security relevant updates.

**Comment by aptalca** [comment]
https://info.linuxserver.io/issues/2023-07-01-armhf/

**Comment by dzett** [comment]
Thanks @aptalca for the pointer. My google queries apparently were not good enough to find this post. Oh well, then I'll have to rather sooner than later get rid of raspbian... Thanks and have a good one...
