### ISSUE TITLE
certbot throws error on first certificate request (but succeeds)

### ISSUE THREAD

**Issue by jmigual** [linuxserver/docker-swag#42]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When starting the container for the first time with duckdns provider, a new certificate is generated.

## Current Behavior

When obtaining a new certificate through duckdns, certbot throws the following error:

```
Waiting for verification...
Cleaning up challenges
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: argument --manual-public-ip-logging-ok: expected one argument
New certificate generated; starting nginx
```

Note that the certificates are generated properly. It's just that it throws this warning/error but continues running anyway

## Steps to Reproduce

1. Use the following configuration for docker-compose:
[example.txt](https://github.com/linuxserver/docker-swag/files/5625535/example.txt)

2. Check logs with `docker logs swag -f`
3. Certbot prints the following error:

```
certbot: error: argument --manual-public-ip-logging-ok: expected one argument
```

4. Certificates are generated properly

## Environment
**OS:** Raspbian GNU/Linux 10 (buster)
**CPU architecture:** armv7l
**How docker service was installed:** Using the get-docker.sh file provided at https://get.docker.com

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d`

## Docker logs

[log.txt](https://github.com/linuxserver/docker-swag/files/5625566/log.txt)

**Comment by aptalca** [comment]
Thanks, looks like that option was just deprecated in the certbot release earlier today: https://github.com/certbot/certbot/releases/tag/v1.10.0
Although I would have expected it to show a deprecation warning rather than an error message. Seems like an upstream issue

**Comment by jmigual** [comment]
Ah I see! It's nice then that we caught this early on

**Comment by aptalca** [comment]
looks like they fixed it upstream, new swag build in the works: https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md
