### ISSUE TITLE
[BUG] files that do not exists downloads index.php

### ISSUE THREAD

**Issue by golles** [linuxserver/docker-swag#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not an expert in Nginx, so I hope I've provided enough information.

When I open the following URLs in a browser, this is what happens:
https://domain.tld/foo -> downloads foo (content is index.php)
https://domain.tld/foo.html -> downloads foo (content is index.php)
https://domain.tld/foo.php -> serves index.php

My `index.php` looks like this:
```php
<?php
header("HTTP/1.0 404 Not Found");

```

I do not have an `index.html` file.

### Expected Behavior

My assumption is that all the above examples would serve `index.php`.

I think the problem is with this line, 
https://github.com/linuxserver/docker-swag/blob/master/root/defaults/nginx/site-confs/default.conf.sample#L51
When I change it to
```
try_files $uri /index.php$is_args$args;
```
Things happen as I expect.

### Steps To Reproduce

I'm using the default config as provided here: https://github.com/linuxserver/docker-swag/blob/master/root/defaults/nginx/site-confs/default.conf.sample

See my steps in the current behavior above.

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- How docker service was installed: docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
swag:
    container_name: swag
    restart: unless-stopped
    image: linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - ${DATA_DIR}/swag:/config
    ports:
      - 80:80
      - 443:443
    environment:
      - EMAIL=${PROXY_CERT_EMAIL}
      - URL=${PROXY_CERT_URL}
      - SUBDOMAINS=${PROXY_CERT_SUBDOMAINS}
      - ONLY_SUBDOMAINS=${PROXY_CERT_ONLY_SUBDOMAINS}
      - VALIDATION=${PROXY_CERT_VALIDATION}
      - DNSPLUGIN=${PROXY_CERT_DNSPLUGIN}
      - PROPAGATION=${PROXY_CERT_PROPAGATION}
      - STAGING=${PROXY_CERT_STAGING}
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-maxmind
      - MAXMINDDB_LICENSE_KEY=${PROXY_MAXMIND_LICENSE_KEY}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
```

### Container logs

```bash
N/A
```

**Comment by nemchik** [comment]
If you remove 
```php
header("HTTP/1.0 404 Not Found");
```
from your `index.php` and put something like
```php
echo "Hello World";
```
with the original nginx configuration shipped, does that work as expected?

The reason for the `=404` in `try_files` is so that 404 pages can redirect to `index.php` to be handled. This is common with many php scripts, including for example WordPress, which has its own 404 pages.

**Comment by golles** [comment]
If I replace it with the hello world example, the browser downloads `foo` (`https://domain.tld/foo`) with 
```php
<?php
echo "Hello World";

```

**Comment by nemchik** [comment]
I have confirmed the behavior and done some searching as to the reason behind it but not found a concrete answer yet. I'll keep searching later. I am unsure about making the exact change you mentioned (removing `=404` from `try_files`) as I believe it was put there intentionally as it is needed by some php scripts (we have other images using the same logic and they don't work without it).

If you can dig up any documentation on why nginx/php behave this way with this configuration feel free to cite it here and I'll see what we can do to adjust.

**Comment by golles** [comment]
Like I mentioned, I'm not an expert in nginx, but I'm happy to do a bit of investigation as well

**Comment by nemchik** [comment]
Leaving a note for myself to continue investigating:
```nginx
try_files $fastcgi_script_name =404;
```
inside the php location and removing `=404` from the `try_files` in the main location seems to work. I need to find an image that depends on the `=404` and remove it, observe the break, then add the new line and confirm if it restores the expected behavior without downloading the php code.

**Comment by nemchik** [comment]
> Leaving a note for myself to continue investigating:
> 
> ```nginx
> try_files $fastcgi_script_name =404;
> ```
> 
> inside the php location and removing `=404` from the `try_files` in the main location seems to work. I need to find an image that depends on the `=404` and remove it, observe the break, then add the new line and confirm if it restores the expected behavior without downloading the php code.

After a bit of testing this seems to be a working fix. @golles if you'd like to test the changes you can see a fully updated copy of the default.conf here https://github.com/linuxserver/docker-swag/blob/fbe212b67c8dd255e326daa30fd4517fed0523e4/root/defaults/nginx/site-confs/default.conf.sample and specifically the lines changed are easy to see in this PR https://github.com/linuxserver/docker-swag/pull/432

**Comment by golles** [comment]
This looks good, awesome!

None php files give an empty body, with the PHP extension I get:
```html
<html>

<head>
	<title>404 Not Found</title>
</head>

<body>
	<center>
		<h1>404 Not Found</h1>
	</center>
	<hr>
	<center>nginx</center>
</body>

</html>
```

But I guess that is expected as the request is handled by PHP in such a case.
