### ISSUE TITLE
[BUG] Incorrect order of s6 init-certbot-config clean up/checks resulting in "Please set the DNSPLUGIN variable to one of the following"

### ISSUE THREAD

**Issue by Maweypeyyu** [linuxserver/docker-swag#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I believe my issue is related to #419 and #398.

I have not updated for quite some time, but when my certificate didn't auto-renew (I believe due to the config ini issue as per #398) I updated to the latest. This however resulted in the same error message like #419.

The underlying issue is that `certbot plugins --authenticators` will not work, because the ini file is still invalid. I moved the code that fixes the ini file ( https://github.com/linuxserver/docker-swag/blob/master/root/etc/s6-overlay/s6-rc.d/init-certbot-config/run#L291-L328 ) temporarily to above the check [here](https://github.com/linuxserver/docker-swag/blob/master/root/etc/s6-overlay/s6-rc.d/init-certbot-config/run#L27) after which swag booted up again, including renewing the cert during the next cronjob run; though there was an error which I ignored:
```
Hook 'post-hook' ran with error output:
 s6-svc: fatal: unable to control /var/run/s6/services/nginx: No such file or directory
```

This may only be an edge case but would it be possible to reorganize how the certbot config is fixed/migrated? I temporarily moved the clean-up up in the file, but I'm not sure that is actually safe for everyone (reason for not creating a PR).

### Steps To Reproduce

1. Have an invalid certbot config (`dns-route53-credentials=/config/dns-conf/route53.ini` in `/config/etc/letsencrypt/cli.ini`)
2. Pull the latest swag image (2.7.1)
3. try to run it -> stops execution at `"Please set the DNSPLUGIN variable to one of the following:"`

### Environment

```markdown
- OS: Ubuntu
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up -d


services:
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=REDACTED
      - URL=REDACTED
      - SUBDOMAINS=wildcard
      - EXTRA_DOMAINS=REDACTED
      - VALIDATION=dns
      - DNSPLUGIN=route53
      - EMAIL=REDACTED
      - DOCKER_MODS=linuxserver/mods:swag-auto-reload
    volumes:
      - swag_data:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    networks:
      - t_internal
```

### Container logs

```bash
swag      | 2023-10-16T06:36:54.214220685Z [mod-init] Attempting to run Docker Modification Logic
swag      | 2023-10-16T06:36:54.347694573Z [mod-init] Adding linuxserver/mods:swag-auto-reload to container
swag      | 2023-10-16T06:36:55.355560805Z [mod-init] Downloading linuxserver/mods:swag-auto-reload from lscr.io
swag      | 2023-10-16T06:36:55.777899206Z [mod-init] Installing linuxserver/mods:swag-auto-reload
swag      | 2023-10-16T06:36:55.783484045Z [mod-init] linuxserver/mods:swag-auto-reload applied to container
swag      | 2023-10-16T06:36:55.879254996Z [migrations] started
swag      | 2023-10-16T06:36:55.882236013Z [migrations] 01-nginx-site-confs-default: skipped
swag      | 2023-10-16T06:36:55.882259352Z [migrations] done
swag      | 2023-10-16T06:36:56.336515347Z ───────────────────────────────────────
swag      | 2023-10-16T06:36:56.336532726Z
swag      | 2023-10-16T06:36:56.336535990Z       ██╗     ███████╗██╗ ██████╗
swag      | 2023-10-16T06:36:56.336538939Z       ██║     ██╔════╝██║██╔═══██╗
swag      | 2023-10-16T06:36:56.336541616Z       ██║     ███████╗██║██║   ██║
swag      | 2023-10-16T06:36:56.336544286Z       ██║     ╚════██║██║██║   ██║
swag      | 2023-10-16T06:36:56.336546887Z       ███████╗███████║██║╚██████╔╝
swag      | 2023-10-16T06:36:56.336549642Z       ╚══════╝╚══════╝╚═╝ ╚═════╝
swag      | 2023-10-16T06:36:56.336552332Z
swag      | 2023-10-16T06:36:56.336554779Z    Brought to you by linuxserver.io
swag      | 2023-10-16T06:36:56.336557358Z ───────────────────────────────────────
swag      | 2023-10-16T06:36:56.336635636Z
swag      | 2023-10-16T06:36:56.336644095Z To support the app dev(s) visit:
swag      | 2023-10-16T06:36:56.337314818Z Certbot: https://supporters.eff.org/donate/support-work-on-certbot
swag      | 2023-10-16T06:36:56.337471903Z
swag      | 2023-10-16T06:36:56.337479433Z To support LSIO projects visit:
swag      | 2023-10-16T06:36:56.337482541Z https://www.linuxserver.io/donate/
swag      | 2023-10-16T06:36:56.337485250Z
swag      | 2023-10-16T06:36:56.337487878Z ───────────────────────────────────────
swag      | 2023-10-16T06:36:56.337490853Z GID/UID
swag      | 2023-10-16T06:36:56.337496300Z ───────────────────────────────────────
swag      | 2023-10-16T06:36:56.339176075Z
swag      | 2023-10-16T06:36:56.339184493Z User UID:    1000
swag      | 2023-10-16T06:36:56.339187597Z User GID:    1000
swag      | 2023-10-16T06:36:56.339190212Z ───────────────────────────────────────
swag      | 2023-10-16T06:36:56.339193122Z
swag      | 2023-10-16T06:36:56.411092289Z using keys found in /config/keys
swag      | 2023-10-16T06:36:56.914049448Z Variables set:
swag      | 2023-10-16T06:36:56.914063069Z PUID=1000
swag      | 2023-10-16T06:36:56.914066370Z PGID=1000
swag      | 2023-10-16T06:36:56.914069160Z TZ=REDACTED
swag      | 2023-10-16T06:36:56.914071863Z URL=REDACTED
swag      | 2023-10-16T06:36:56.914074515Z SUBDOMAINS=wildcard
swag      | 2023-10-16T06:36:56.914077157Z EXTRA_DOMAINS=REDACTED
swag      | 2023-10-16T06:36:56.914079755Z ONLY_SUBDOMAINS=false
swag      | 2023-10-16T06:36:56.914082305Z VALIDATION=dns
swag      | 2023-10-16T06:36:56.914084838Z CERTPROVIDER=
swag      | 2023-10-16T06:36:56.914087370Z DNSPLUGIN=route53
swag      | 2023-10-16T06:36:56.914089955Z EMAIL=REDACTED
swag      | 2023-10-16T06:36:56.914092531Z STAGING=
swag      | 2023-10-16T06:36:56.914095071Z
swag      | 2023-10-16T06:36:57.886969271Z Please set the DNSPLUGIN variable to one of the following:
swag      | 2023-10-16T06:36:57.886984643Z
```

**Comment by nemchik** [comment]
Unfortunately it doesn't make sense to move https://github.com/linuxserver/docker-swag/blob/2b5a2785d6bf987a24218078205921644eb7bf47/root/etc/s6-overlay/s6-rc.d/init-certbot-config/run#L291-L328 above the validation of the DNSPLUGIN variable because those lines are meant to use the variable and expect a validated value to be in it.

If you can post the contents of your `dns-route53-credentials=/config/dns-conf/route53.ini` file before and after the problem we can try to add in some specific replacements for it if there was some change in what gets written to that file that we haven't accounted for. If the changes were made manually and don't adhere to the recommended variables/values provided in the file, there's not much we can do to support it.

It could be possible to sideline the `cli.ini` temporarily while the authenticator validation command is run, but based on what you provided above there is not enough information to confirm that would resolve the issue. There may be some other variable involved that would have caused your `cli.ini` to be recreated in a valid state.

In the future, a potential step before reporting an issue would be to set `STAGING=true` and restart the container. If certbot is able to retrieve a cert you should be able to swap to `STAGING=false` (or remove the variable) and everything should work (unless you're rate limited, but that doesn't seem to be the case here).

**Comment by jordankoehn** [comment]
Can confirm this behavior. On my container I actually removed /config/dns-conf/route53.ini so it would use the ec2's IAM role within AWS. Haven't figured out any workarounds yet
