### ISSUE TITLE
[FEAT] Add reference to T.I.'s "Swagga Like Us" in README or somewhere? #maybe

### ISSUE THREAD

**Issue by GregSweats** [linuxserver/docker-swag#424]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Nuff Said in the Screenshot below?
I'm just not sure where the reference should go...too bad we can't autoplay YouTube Videos in the background like the good ol' 90s and background midi's. Lol.

![image](https://github.com/linuxserver/docker-swag/assets/106463642/a05bae9a-21e6-481d-82eb-778bb70b52ec)

### Reason for change

You had the awesome SWAG GIF, one of my favourite btw,  on the README. Thought you might get a kick out of this as it just came on when I was testing qobuz for higher quality audio streaming, so I have no music library and just going through some classicz.

**Comment by nemchik** [comment]
Here's a bit of fun backstory for context:
![image](https://github.com/linuxserver/docker-swag/assets/725456/ee134a27-b344-4dcf-9110-9d8db6bb2651)
![image](https://github.com/linuxserver/docker-swag/assets/725456/6c4ca553-615c-4ce7-b6a3-b30b01ee4109)

We were discussing what to rename our [letsencrypt](https://github.com/linuxserver/docker-letsencrypt) image to. It was kind of a tongue in cheek suggestion but @j0nnymoe tossed in the gif and it stuck 😂 

It's great having a name we just picked for fun, knowing it's kind of silly, and the gif is definitely the icing on the cake. I don't think we would want to go as far as including any kind of auto-playing audio, or even linking to a specific song as it wasn't actually part of the original inspiration for the name.
