### ISSUE TITLE
[FEAT] Update GandI DNS plugin to support Personal Access Tokens

### ISSUE THREAD

**Issue by RichardJRL** [linuxserver/docker-swag#426]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Domain registrar GandI have deprecated the use of API Keys and are in the process of replacing them with new Personal Access Tokens which allow more fine-grained control over the user's GandI account, see [here](https://news.gandi.net/en/2023/09/pat-jetons-acces-personnels-api-gandi/) for details.

The GandI DNS plugin needs to be updated within SWAG to handle the new Personal Access Tokens.

### Reason for change

GandI are deprecating the use of API keys and are replacing them with Personal Access Tokens. It's more than just a name change, [the backend API calls differ](https://api.gandi.net/docs/authentication/) depending on which one is used, so the new token can't just be pasted in as the value for the old `dns_gandi_api_key` API key variable in `root/defaults/dns-conf/gandi.ini`

### Proposed code change

The GandI plugin's own Github page has recently [merged a commit](https://github.com/obynio/certbot-plugin-gandi/pull/47) that enables the use of Personal Access Tokens alongside the old API keys, so the coding for the change has been done already. Can you pull this across to SWAG directly, or do you have to wait for certbot or something else upstream to pick up this change before you inherit it?

**Comment by Roxedus** [comment]
This change should already bein the image, as we ship version 1.5.0 of the plugin
