### ISSUE TITLE
[FEAT] Please reopen bug 335 

### ISSUE THREAD

**Issue by TheCakeGit** [linuxserver/docker-swag#427]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Issue 335 still exists.

I put in...

[Definition]
allowipv6 = no

As a newbie I found the error message very confusing, I still don't know if ipv6 is allowed or not:
"WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'"

Further information here (including repro steps:
https://github.com/linuxserver/docker-swag/issues/335

### Reason for change

I believe this to be a bug because this warning is a misreporting.
I did define allowipv6, yet your warning says I didn't. Furthermore it says it's changed it to "auto" and I don't want that.

### Proposed code change

N/A

**Comment by nemchik** [comment]
The fail2ban project has this value commented out in their default packaged config https://github.com/fail2ban/fail2ban/blob/eed319e896f603471cc4027b353b8535faac4208/config/fail2ban.conf#L62

We try to stick close to their defaults. The message does not affect functionality, and no action is required. If you want to silence the message you can add
```conf
allowipv6 = auto
```
to your `fail2ban.local` file.
