### ISSUE TITLE
[BUG] jail.d pointer for fail2ban jail.d folder is missing

### ISSUE THREAD

**Issue by hrv231** [linuxserver/docker-swag#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I create a "jail.d" folder inside my host folder where I point to /config, the docker is not able to read the files inside that folder.

### Expected Behavior

If I have ".local" files to use with fail2ban and put them inside the jail.d folder, I expect that swag is going to be able to read them.

### Steps To Reproduce

1. create the swag docker
2. create a "jail.d" folder inside your mounted host path , example: /swag/fail2ban/jail.d
3. put your .local files there and your custom filter in your filter.d folder
4. restart the docker and check the fail2ban logs to see if fail2ban is using the .local files

### Environment

```markdown
- OS: unraid
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='swag'
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="swag"
  -e 'TCP_PORT_80'='80'
  -e 'TCP_PORT_443'='443'
  -e 'EMAIL'='aaaaaaaaaaaaaaa@outlook.com'
  -e 'URL'='duckdns.org'
  -e 'SUBDOMAINS'='bbbbbbbbbbbbbbbbbb'
  -e 'ONLY_SUBDOMAINS'='true'
  -e 'VALIDATION'='http'
  -e 'DNSPLUGIN'=''
  -e 'EXTRA_DOMAINS'=''
  -e 'STAGING'='false'
  -e 'DUCKDNSTOKEN'=''
  -e 'PROPAGATION'=''
  -e 'PUID'='99'
  -e 'PGID'='100'
  -v '/mnt/user/appdata/swag':'/config':'rw'
  -v '/mnt/user/nextcloud_data/nextcloud.log':'/nextcloud/nextcloud.log':'ro'
  -v '/mnt/user/appdata/swag/fail2ban/jail.d/':'/etc/fail2ban/jail.d':'ro'
  --cap-add=NET_ADMIN 'linuxserver/swag'
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Variables set:
PUID=99
PGID=100
TZ=America/Los_Angeles
URL=duckdns.org
SUBDOMAINS=bbbbbbbbbbbbbbbbbb
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=true
VALIDATION=http
CERTPROVIDER=
DNSPLUGIN=
EMAIL=aaaaaaaaaaaaaaa@outlook.com
STAGING=false

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Sub-domains processed are: bbbbbbbbbbbbbbbbbb.duckdns.org
E-mail address entered: aaaaaaaaaaaaaaa@outlook.com
http validation is selected
Certificate exists; parameters unchanged; starting nginx
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Server ready
```

**Comment by aptalca** [comment]
SWAG doesn't utilize a user configurable `jail.d` folder. You can add your jails to `jail.local`

**Comment by hrv231** [comment]
> SWAG doesn't utilize a user configurable `jail.d` folder. You can add your jails to `jail.local`

I understand that, but Fail2Ban originally uses them.
Do you think it is too complex to edit the Dockerfile on your part and place that volume mount there?

**Comment by aptalca** [comment]
Volume in the Dockerfile wouldn't magically do what you think it would do. It would not be very different than you mounting that path in your compose yaml or docker run. We don't plan to support a user configurable `jail.d` folder at this time.
