### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by gastonMM** [linuxserver/docker-swag#43]
Hi,

I need disable IPv6

When disabling IPv6 from ubuntu I get the error
(97: address family not supported by protocol)

I need to disable IPv6 as it brings me problems with my ISP.

How can I do it?

Thanks

**Comment by Roxedus** [comment]
How is this a container issue?

**Comment by gastonMM** [comment]
sorry, yes, in docker

**Comment by gastonMM** [comment]
in ubuntu server 20.04, in grub I put ipv6.disable = 1:

this removes IPv6 from Ubuntu. and I start to have the error
(97: address family not supported by protocol)
in the container log

**Comment by j0nnymoe** [comment]
Disabling ipv6 on the host causes problems with docker itself, not the container. This isn't a container issue.

**Comment by glensc** [comment]
Disagree with @j0nnymoe comment. I have ipv6 disabled for ages, and now only this container fails to start:

```
swag    | nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)                       
```

**Comment by j0nnymoe** [comment]
@glensc well no - as per one of your other comments about libseccomp, your container is failing due to that, not ipv6

**Comment by nemchik** [comment]
I can confirm i'm running the latest image pulled as of 4am CST and my system has ipv6 disabled and I do not have issues.

**Comment by glensc** [comment]
@j0nnymoe no. the ipv6 errors are still there. and due the repeat interval I would say it's retried every 1 second

```
glen@acai:~/scm/swag$ docker-compose up -d
Starting swag ... done

glen@acai:~/scm/swag$ docker-compose logs --tail=20 -t
Attaching to swag                                                                                              
swag    | 2021-02-20T07:44:23.261374104Z [services.d] starting services
swag    | 2021-02-20T07:44:23.287080938Z [services.d] done.
swag    | 2021-02-20T07:44:23.413942329Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:24.013937160Z Server ready
swag    | 2021-02-20T07:44:24.382779503Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:25.441645760Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:26.449157126Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:27.449683444Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:28.445631179Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
```

and the service (nginx stays down), connection refused.

```
glen@acai:~/scm/swag$ curl localhost
curl: (56) Recv failure: Connection reset by peer


6 glen@acai:~/scm/swag$ telnet localhost 80
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

It's really connection refused from application point, but docker port forwarding makes error appear as connection reset.

```
glen@acai:~/scm/swag$ docker-compose exec swag netstat -nat|grep LISTEN
tcp        0      0 127.0.0.11:34147        0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN
glen@acai:~/scm/swag$
```

ipv6 is disabled via kernel commandline here;

```
glen@acai:~/scm/swag$ cat /proc/cmdline
... ipv6.disable=1
```

**Comment by glensc** [comment]
The fix is to remove ipv6 listen lines.

@nemchik perhaps you need to test from scratch config dir, as you may already have modified config in place.

```diff
diff --git a/config/nginx/site-confs/default b/config/nginx/site-confs/default
index 6d76de6..980e5be 100644
--- a/config/nginx/site-confs/default
+++ b/config/nginx/site-confs/default
@@ -5,7 +5,6 @@ error_page 502 /502.html;
 # redirect all traffic to https
 server {
        listen 80 default_server;
-       listen [::]:80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
 }
@@ -13,7 +12,6 @@ server {
 # main server block
 server {
        listen 443 ssl http2 default_server;
-       listen [::]:443 ssl http2 default_server;

        root /config/www;
        index index.html index.htm index.php;
(END)
```

**Comment by nemchik** [comment]
> The fix is to remove ipv6 listen lines.
> 
> @nemchik perhaps you need to test from scratch config dir, as you may already have modified config in place.
> 
> ```diff
> diff --git a/config/nginx/site-confs/default b/config/nginx/site-confs/default
> index 6d76de6..980e5be 100644
> --- a/config/nginx/site-confs/default
> +++ b/config/nginx/site-confs/default
> @@ -5,7 +5,6 @@ error_page 502 /502.html;
>  # redirect all traffic to https
>  server {
>         listen 80 default_server;
> -       listen [::]:80 default_server;
>         server_name _;
>         return 301 https://$host$request_uri;
>  }
> @@ -13,7 +12,6 @@ server {
>  # main server block
>  server {
>         listen 443 ssl http2 default_server;
> -       listen [::]:443 ssl http2 default_server;
> 
>         root /config/www;
>         index index.html index.htm index.php;
> (END)
> ```

This is not required. I am using the stock configs that include these lines. I run swag on a system in my lan and on a vps, neither have ipv6, both using the same config files which include the listen lines, neither one has any issues like you're mentioning.

Would you please post your compose file here so we can have a look at how you've got that set?

**Comment by j0nnymoe** [comment]
In fact @glensc please open a new issue posting the information we request so we can track it correctly rather than using an old issue. Thanks.

**Comment by glensc** [comment]
@j0nnymoe posted: https://github.com/linuxserver/docker-swag/issues/92#issue-813320933
