### ISSUE TITLE
ClouDNS DNS Challenge

### ISSUE THREAD

**Issue by jeffshead** [linuxserver/docker-swag#435]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add support for ClouDNS DNS Challenge

### Reason for change

I'm looking for a NPM replacement but I can't use SWAG without this feature. ClouDNS is a popular and feature rich DNS provider and one of the best providers that I've used. I'm surprised it's not already supported. Thanks for considering :-)

### Proposed code change

Use ClouDNS's official plug-in: https://github.com/cloudns/certbot-dns-cloudns

**Comment by nemchik** [comment]
You can accomplish this by creating `/config/dns-conf/cloudns.ini` with the credentials mentioned in https://github.com/cloudns/certbot-dns-cloudns#credentials and using https://github.com/linuxserver/docker-mods/tree/universal-package-install to install the package by setting
```
- DOCKER_MODS=linuxserver/mods:universal-package-install
- INSTALL_PIP_PACKAGES=certbot-dns-cloudns
- VALIDATION=dns
- DNSPLUGIN=cloudns
```
and and then restarting the container.

**Comment by maxiwheat** [comment]
That would be nice if ClouDNS DNS challenge could be supported natively by this container.

**Comment by drizuid** [comment]
Note for all, PRs are welcome :)
