### ISSUE TITLE
> If its not broken don't fix it! Causing grief for no reason!!

### ISSUE THREAD

**Issue by bachoo786** [linuxserver/docker-swag#436]
> If its not broken don't fix it! Causing grief for no reason!!

With that mentality, you shouldn't have updated your container. But I'm glad you did because running a 4 year old deprecated image is really not a good idea.

> I haven't received any help.
>
> My ports have been forwarded as I said initially.
> 
> And my dns is working fine however the swag reverse proxy is NOT!

Github issues are for bug reports, not general support. We directed to you the right place for hand holding multiple times but you refuse to listen.
Excuse us if we don't take your word. There is only so much we can do when the issue description is `not working`. Based on what you reported, it sure sounds like a networking issue.

Good luck.

_Originally posted by @aptalca in https://github.com/linuxserver/docker-swag/issues/433#issuecomment-1832582765_
 
@aptalca You didn't let me  reply you. I suggest getting rid of the issues page all together ❤️

**Comment by aptalca** [comment]
Please don't open unnecessary new issues. The other one was locked because you were directed to the correct place and no reply was requested or necessary.

Github Issues are for bug reports, not support requests.

Consider this an official warning.

**Comment by bachoo786** [comment]
> Please don't open unnecessary new issues. The other one was locked because you were directed to the correct place and no reply was requested or necessary.
> 
> Github Issues are for bug reports, not support requests.
> 
> Consider this an official warning.

I did realise I shouldn't have hence I closed it "as not planned" 

Relax yourself and get too worked up mate.
