### ISSUE TITLE
[BUG] SWAG doesn't find addons on repository

### ISSUE THREAD

**Issue by gottoesplosivo** [linuxserver/docker-swag#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SWAG can't find addons

Can't access Dashboard either locally or remotely, 403 error remotely.

### Expected Behavior

SWAG finding and installing addons

### Steps To Reproduce

Adding environment variable as per instructions

![image](https://github.com/linuxserver/docker-swag/assets/46649143/70653f72-2a60-4914-aaf7-92cf68e6554e)

### Environment

```markdown
- OS:  Unraid 6.12.4
- How docker service was installed: through unraid apps
```

### CPU architecture

x86-64

### Docker creation

```bash
used unraid image, added following variable


![image](https://github.com/linuxserver/docker-swag/assets/46649143/70653f72-2a60-4914-aaf7-92cf68e6554e)
```

### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:swag-dashboard to container
[mod-init] linuxserver/mods:swag-dashboard could not be found on lscr.io
[mod-init] Adding linuxserver/mods:swag-auto-reload to container
[mod-init] linuxserver/mods:swag-auto-reload could not be found on lscr.io
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Variables set:
PUID=99
PGID=100
TZ=Europe/Berlin
URL=**REDACTED**
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=cloudflare
EMAIL=
STAGING=false

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Wildcard cert for **REDACTED** will be requested
No e-mail address entered or address invalid
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2023-06-05 │ 2023-11-27 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Server ready
```

**Comment by gottoesplosivo** [comment]
> Posting whole container, and not just the box for a variable would be nice. Though you should go trough the checks in https://docs.linuxserver.io/FAQ/#lscr

Thank you for the link, I missed it. Scarf was indeed blocked, however even after whitelisting it I keep getting the same error.

Here's the whole container 
![Screenshot 2023-12-03 at 19-34-45 Tower_UpdateContainer](https://github.com/linuxserver/docker-swag/assets/46649143/3738d764-feb1-48e1-96b1-2e2173c20c43)

**Comment by drizuid** [comment]
` it I keep getting the same error.`  are you referring to `[mod-init] linuxserver/mods:swag-auto-reload could not be found on lscr.io` ? we can't control whether you can reach lscr.io or not... this is a network problem specific to you that you need to resolve.. if it is a different error, please share it

**Comment by gottoesplosivo** [comment]
try to have a look here https://discord.com/channels/354974912613449730/1181600849592594512

specifically to this message: https://discord.com/channels/354974912613449730/1181600849592594512/1181612308225593397

however the whole thread was useful for me!

**Comment by drizuid** [comment]
those are my messages and have nothing to do with fixing your network issue, as stated in the very link you provided. this is a network issue specific to you. That said, I will go ahead and close this issue as it is not a container problem.
