### ISSUE TITLE
[FEAT] Add Tailscale as a DNS Plugin

### ISSUE THREAD

**Issue by Imzxhir** [linuxserver/docker-swag#448]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I want SWAG to add an option to use Tailscale as a DNS Plugin. I recently saw Traefik added this in the Traefik v3 beta and I thought it would be nice if the same could be added to SWAG.

Here is a link to the blog post where this was announced: https://traefik.io/blog/traefik-proxy-3-0-scope-beta-program-and-the-first-feature-drop/#tailscale-certificate-resolver

Here is a link to how Traefik integrates Tailscale: https://traefik.io/blog/exploring-the-tailscale-traefik-proxy-integration/

### Reason for change

I want Tailscale to be added as Tailscale itself is a great service for people who want to create their own private network and let the network be only accessible by them through a secure VPN. 

Tailscale also has this nice feature which is Magic DNS and it gives each of your devices a unique domain to use and configure. By using this, Tailscale can generate SSL certificates for each of your domains or devices for you to use anywhere.

**Comment by j0nnymoe** [comment]
If someone has developed a tailscale plugin for certbot, we can look into it.

**Comment by Roxedus** [comment]
No plugin exists, not doable until it does.
