### ISSUE TITLE
OpenSSL 1.1.1g Advisory

### ISSUE THREAD

**Issue by sydlexius** [linuxserver/docker-swag#45]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

CISA published a vulnerability bulletin in all versions of OpenSSL prior to v1.1.1i.  The notice can be found here:
https://us-cert.cisa.gov/ncas/current-activity/2020/12/08/openssl-releases-security-update
OpenSSL's details can be found here:
https://www.openssl.org/news/secadv/20201208.txt

------------------------------

## Expected Behavior

Upgrade to version 1.1.1i
## Current Behavior

Existing 1.1.1g install is susceptible to a DoS condition.

## Steps to Reproduce

1. N/A

## Environment
**OS:** UnRAID 6.9.0-beta35
**CPU architecture:** x86_64, however all releases are impacted.

**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

Installed via Community Applications in UnRAID 6.9

**Comment by aptalca** [comment]
When it's updated in the alpine repo, our package check build will pick it up: https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.12
You can report it to them on alpine's gitlab
