### ISSUE TITLE
[FEAT] ngx_http_v3_module

### ISSUE THREAD

**Issue by garfieldairlines** [linuxserver/docker-swag#452]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add ngx_http_v3_module to support http3

### Reason for change

...

**Comment by thespad** [comment]
Alpine currently only package 1.24 and 1.25 is required for http3/quic support. As and when they start distributing 1.25 we can look at this again.

**Comment by TalEdd** [comment]
According to [Alpine NGINX Commits](https://git.alpinelinux.org/aports/commit/?id=4c43d25ac7b43d7c92bdec210205bd831d6adc06) there won't be any upgrade to 1.25. 
>  NOTE: Upgrade only to even-numbered versions (e.g. 1.14.z, 1.16.z)!
 Odd-numbered versions are mainline (development) versions.

Will have to wait even longer till 1.26 is released. According to [serverfault StackExchange](https://serverfault.com/a/715126), mainline might be more reliable and recommended in general. I have shifted to NPMPlus till SWAG is updated, as I want to use HTTP/3 for my servers.

**Comment by ckantor8** [comment]
Any update on this? Been upgrading/securing my web services and was super bummed to find out SWAG still has not implemented HTTP3 support.

**Comment by thespad** [comment]
Alpine aren't currently building nginx with http3 because openssl lacks full support for all the needed features, we're limited by their packaging.

**Comment by ckantor8** [comment]
@thespad Ah I see, so it's totally on them that sucks. Any chance you guys would consider switching to LibreSSL (or does a LibreSSL SWAG fork already exist)? Either way, thank y'all for all the work you put in, greatly appreciate it!

**Comment by thespad** [comment]
We don't really have a choice; Alpine build nginx against openssl. We'd have to compile it from source to build against libressl and enable http3 support.

**Comment by rootmax84** [comment]
Is there any progress about QUIC/HTTP3 support?

**Comment by brokoler** [comment]
Also waiting for HTTP3, it improves latency a lot and would be great to have.
