### ISSUE TITLE
DNSPLUGIN for hostido.pl

### ISSUE THREAD

**Issue by kwtor** [linuxserver/docker-swag#462]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I am asking you to add DNSPLUGIN: for registrar server Hostido.pl

### Reason for change

Extension of the list of domain registrar servers

**Comment by Roxedus** [comment]
Does the registrar offer a certbot plugin? this is a prerequisite for swag inclusion

**Comment by kwtor** [comment]
Yes, this domain registrar (Hostido.pl) supports Certbot and API

**Comment by aptalca** [comment]
where is the certbot plugin for it?

**Comment by kwtor** [comment]
I can't find the plugin ;-(
I used standard certbot commands to manually generate an SSL certificate:
sudo certbot certonly --manual --preferred-challenges=dns --email your-email@xxx.pl --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d your- domain -d *.your-domain
and adding domain TXT (authentication) records.
I also found in the domain management panel -> the ability to generate an API key ("authinfo")

**Comment by aptalca** [comment]
SWAG doesn't support manual cert generation.

If there is a certbot plugin for it in the future, let us know. If not, we recommend Cloudflare for managing DNS as they do a much better job than most if not all registrars. You can keep your domain at the registrar, but point the nameservers to Cloudflare to manage DNS there.

**Comment by kwtor** [comment]
My problem is that I can't run the SWAG proxy server properly, because it stops at the certificate generation stage (no appropriate DNSPLUGIN), and I can't import my Let's Encrypt SSL certificate (previously generated, e.g. with standard certbot commands?)

**Comment by aptalca** [comment]
No. SWAG needs to be fully automated.

Your options are:
1. Use cloudflare for dns
2. Use http validation (no wildcard)
3. Use our nginx image with proxy mod and manage the cert manually

**Comment by kwtor** [comment]
OK thank you

**Comment by kwtor** [comment]
P.S> CloudFlare has not been able to properly adapt my domain registered at Hostido.pl for 3 days now :-(
