### ISSUE TITLE
[feature request] manual mode(or disable cert request) for certbot as additional env. variable

### ISSUE THREAD

**Issue by bread-cat** [linuxserver/docker-swag#47]
Hi, it'll be great to have additional option for getting certificate with manual option by certbot or disabling cert request if certificate is already taken. Thanks in advance!

**Comment by leranp** [comment]
How can i use the new option? I am testing the docker and every restart of the docker that cert is renew

**Comment by Roxedus** [comment]
This is not a option.

**Comment by leranp** [comment]
> This is not a option.

So there's no way to restart the container without renewal of the certificate?

**Comment by Roxedus** [comment]
It will not renew if the certificate in /config does not expire within the next day.

**Comment by leranp** [comment]
This is not my case, the docker renew the certificate every restart, do you
want a log file?

**Comment by Roxedus** [comment]
If anything it should be a new issue. Remember to use the bug template
