### ISSUE TITLE
[FEAT] add ddns support

### ISSUE THREAD

**Issue by iHuahua** [linuxserver/docker-swag#471]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

swag是一个非常棒的项目，尤其是对于家庭用户来说简直是神器。看到项目里既然已经支持了很多种dns验证，麻烦提供一个入口设置ddns解析，这对动态ip用户来说非常实用

### Reason for change

辛苦开发团队考虑一下这个建议

**Comment by j0nnymoe** [comment]
We have no plans to add ddns support as that belongs in a dedicated container or done via a different means.
