### ISSUE TITLE
Suchen Sie die letzte Version mit php 7.4. Vorzugsweise Version 7.4.33

### ISSUE THREAD

**Issue by MalikWilliams1greher** [linuxserver/docker-swag#473]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Lieber Linuxserver-Entwickler, ich muss jetzt ein Programm einsetzen, aber es unterstützt bis zu php7.4, was ist die letzte Version mit php7.4.33?

### Reason for change

Lieber Linuxserver-Entwickler, ich muss jetzt ein Programm einsetzen, aber es unterstützt bis zu php7.4, was ist die letzte Version mit php7.4.33?

**Comment by thespad** [comment]
We were *strongly* advise against running an old version of Swag with an unsupported version of PHP. If you absolutely have to run an unsupported version of PHP, do so in another container behind Swag and proxy it.
