### ISSUE TITLE
[BUG] Squarespace support after Google Domains acquisition

### ISSUE THREAD

**Issue by DevDema** [linuxserver/docker-swag#486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recently, Google Domains was acquired by Squarespace.

The existing documentation and ini files display instructions for Google Domains, but they have not yet been updated to Squarespace.

The current access token I used to have for Google Domains, gives out 400: Bad request when trying to use it:

` Unable to rotate DNS challenges: 400 Client Error: Bad Request for url: https://acmedns.googleapis.com/v1/acmeChallengeSets/###:rotateChallenges` 

### Expected Behavior

We should be provided in the docs and in the ini files some instruction on how to setup a domain registered on Squarespace.

### Steps To Reproduce

1. Have a domain registered on Google Domains
2. Generating an API_KEY on Squarespace with the same properties for Google Domains does not work

### Environment

```markdown
- OS: Ubuntu Server
- How docker service was installed: Docker Compose
```

### CPU architecture

arm64

### Docker creation

```bash
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - URL=###
      - SUBDOMAINS=###
      - VALIDATION=dns
      - dns_google_domains_access_token=###
      - dns_google_domains_zone=###
      - CERTPROVIDER=letsencrypt
      - DNSPLUGIN=google-domains
      - EMAIL=###
      - ONLY_SUBDOMAINS=false
```

### Container logs

```bash
swag  | dns validation via google-domains plugin is selected
swag  | Generating new certificate
swag  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
swag  | Requesting a certificate for #### and 3 more domains
swag  | Unsafe permissions on credentials configuration file: /config/dns-conf/google-domains.ini
swag  | Encountered exception during recovery: certbot.errors.PluginError: Unable to rotate DNS challenges: 400 Client Error: Bad Request for url: https://acmedns.googleapis.com/v1/acmeChallengeSets/###:rotateChallenges
swag  | Unable to rotate DNS challenges: 400 Client Error: Bad Request for url: https://acmedns.googleapis.com/v1/acmeChallengeSets/####:rotateChallenges
swag  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
swag  | ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/google-domains.ini file.
⏺ docker-
```

**Comment by wxianxin** [comment]
Second this issue. If there is no plan on supporting square space, could some one suggest a service provider that I should transfer the domain to?

**Comment by thespad** [comment]
https://support.squarespace.com/hc/en-us/articles/17131164996365-About-the-Google-Domains-migration-to-Squarespace#toc-does-squarespace-support-acme-tls-ssl-certificates-

We need to remove the google domains certbot plugin as it is no longer supported.

**Comment by martinmiglio** [comment]
> suggest a service provider that I should transfer the domain to?

Using another service's name servers would suffice without a full domain transfer, like cloud flare or route 53.
