### ISSUE TITLE
[FEAT] nginx-mod-http-zstd

### ISSUE THREAD

**Issue by garfieldairlines** [linuxserver/docker-swag#487]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Would be great to have zstd too !

### Reason for change

It's finally implemented in firefox.

### Proposed code change

+ https://pkgs.alpinelinux.org/package/edge/main/x86_64/nginx-mod-http-zstd

**Comment by aptalca** [comment]
Looks like this package was added in alpine 3.20.

SWAG is currently based on 3.19, but will move over to 3.20 in the near future. We'll make sure to add it during the rebase.

Thanks
