### ISSUE TITLE
[FEAT] Add nginx-ultimate-bad-bot-blocker as a mod for SWAG

### ISSUE THREAD

**Issue by jettycake** [linuxserver/docker-swag#490]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Create a SWAG/Nginx mod for nginx-ultimate-bad-bot-blocker https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker

This was previously requested under #221 but went stale and was closed.

### Reason for change

To block bad bots. What do I mean by 'bad bots?' See here: https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker#define-bad-bots

Overall it's general security. Having a mod would be easier than having people try to manuually add it.

### Proposed code change

Implement https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker in a Docker mod.

**Comment by j0nnymoe** [comment]
I would say considering the last request for this went stale that we have no plans to consider a mod for this but if someone within the mod was willing to submit something and maintain it, we could look at accepting it.

**Comment by jettycake** [comment]
> I would say considering the last request for this went stale that we have no plans to consider a mod for this but if someone within the mod was willing to submit something and maintain it, we could look at accepting it.

Thanks for the response. The last one didn't even get that :) 

Probably beyond my skillset - I have no real clue how to build and maintain a mod like this. I could look into it if there's a mod base template, but it would probably only end up being for my personal use unless I was incredibly confident.
