### ISSUE TITLE
[FEAT] nginx brotli compression support

### ISSUE THREAD

**Issue by rootmax84** [linuxserver/docker-swag#494]
### Is this a new feature request?

- [x] I have searched the existing issues

### Wanted change

Missed libraries:
- libnginx-mod-http-brotli-filter
- libnginx-mod-http-brotli-static

### Reason for change

Better compression than old gzip

### Proposed code change

Suggested nginx.conf changes:
```
brotli_static on;
brotli on;
brotli_comp_level 6;
brotli_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

```

**Comment by j0nnymoe** [comment]
Well discuss internally if this is something we want to add but you will be able to add this yourself now via our universal package installer mod. (Assuming the packages are in alpines repo)
