### ISSUE TITLE
[FEAT] Seafile config file

### ISSUE THREAD

**Issue by isvein** [linuxserver/docker-swag#498]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi :)
Will it someday be an config file for Seafile included?

### Reason for change

I try to get seafile to work behind swag.
I can get it to work just fine behind NPM, but not swag
Tried every config file I can find out there, some work and I can log in, but then download/upload does not work with any, even if I set URL correct in seafile settings. 

I use unraid and used the "dglb99" image of Seafile

**Comment by j0nnymoe** [comment]
We used to have one included but it got removed to numerous people reporting issues with it and no one within the team uses seafile, we could not test this.

**Comment by isvein** [comment]
> We used to have one included but it got removed to numerous people reporting issues with it and no one within the team uses seafile, we could not test this.

sad!
Seems like seafile is hard to get to work correctly behind swag :(
I would not mind testing the config and report back what happens, but I get that if no one on the team uses seafile, its harder to get it to work.
