### ISSUE TITLE
[FEAT] Add Mail in a box (MIAB) as a dns verification provider

### ISSUE THREAD

**Issue by Glich440** [linuxserver/docker-swag#501]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add [Mail in a box](https://mailinabox.email/) as a provider for dns verification. It provides an easy way to manage a mail server, but to do this it takes over DNS.

### Reason for change

MIAB is a popular project and adding it as an option for DNS verification would make it easier to setup SWAG on subdomains on which MIAB controls the DNS.

### Proposed code change

MIAB provides an API for managing the DNS records, an example for adding and removing a TXT record is below: 
From the official documentation
```
# adds a TXT record using POST to preserve any previous TXT records
curl -X POST --user me@mydomain.com:$PASSWORD -d "some text here" https://box.example.net/admin/dns/custom/foo.mydomain.com/txt

# deletes that one TXT record while preserving other TXT records
curl -X DELETE --user me@mydomain.com:$PASSWORD -d "some text here" https://box.example.net/admin/dns/custom/foo.mydomain.com/txt
```
If TOPT authentication is enabled a header must be added, example:
```
# adds a TXT record using POST to preserve any previous TXT records
curl -X POST -H "$TOPT" --user me@mydomain.com:$PASSWORD -d "some text here" https://box.example.net/admin/dns/custom/foo.mydomain.com/txt

# deletes that one TXT record while preserving other TXT records
curl -X DELETE -H "$TOPT" --user me@mydomain.com:$PASSWORD -d "some text here" https://box.example.net/admin/dns/custom/foo.mydomain.com/txt
```
These codes can be generated by tools such as oathtool, example:
```
TOTP="X-Auth-Token: $(oathtool --totp -b -d 6 $TOTP_KEY)"
```
ps: TOTP_KEY and PASSWORD should be a docker secret

**Comment by thespad** [comment]
There needs to be a certbot plugin available for us to add support, if there is one please link to it and we can get it included in the image.

**Comment by Glich440** [comment]
I can't find any, but if it's only creating and deleting DNS records I would be open to creating one myself, I would need the documentation on what its behavior should be

**Comment by Glich440** [comment]
ended up just using the external dns feature on miab
