### ISSUE TITLE
[BUG] <title> Duplicate Location - default.conf (issue after updating docker)

### ISSUE THREAD

**Issue by almulder** [linuxserver/docker-swag#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So I just updated to the latest docker version and now sites are unavailable, and now I am getting this message:

nginx: [emerg] duplicate location "/" in /config/nginx/site-confs/default.conf:37

Also was getting messages about:
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/proxy-confs/overseerr.subdomain.conf:8
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/proxy-confs/overseerr.subdomain.conf:9

### Expected Behavior

Update should not break old config files, or atleast not the default one.

### Steps To Reproduce

not sure other than to use old files

### Environment

```markdown
- OS: Unraid
- How docker service was installed: Unraid Update
```

### CPU architecture

x86-64

### Docker creation

```bash
Was use from unraid app
```

### Container logs

```bash
Not sure what log file as there are several
```

**Comment by j0nnymoe** [comment]
`Container logs`
This is from the container window not the actual logs of nginx etc within the container.

**Comment by almulder** [comment]
I just reinstalled and used updated templates and modified as needed now it work.
