### ISSUE TITLE
[BUG] Porkbun cercbot dns version too old, causes "key-error"

### ISSUE THREAD

**Issue by connbrack** [linuxserver/docker-swag#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the DNSPLUGIN=porkbun option, I get the error in the logs listed below. 

### Expected Behavior

DNS works properly

### Steps To Reproduce

Use standard config in swag documentation. Use VALIDATION=dns, DNSPLUGIN=porkbun. Enter API key and secret in porkbun.ini

### Environment

```markdown
- OS: Fedora 40 server
- How docker service was installed: Using official instructions: https://docs.docker.com/engine/install/fedora/
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up swag
```
```bash
swag:
  image: lscr.io/linuxserver/swag:latest
  container_name: swag
  cap_add:
    - NET_ADMIN
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - URL=example.domain.com
    - VALIDATION=dns
    - SUBDOMAINS=www,
    - DNSPLUGIN=porkbun
  volumes:
    - /home/server/services/swag/config:/config
  ports:
    - 443:443
    - 80:80
  restart: unless-stopped

```

### Container logs

```bash
Encountered exception during recovery: KeyError: 'oN94YkJWnu2pdC0XLUtGSaprnZLrmhjMJ1aovVBXZfY'
'PKBClient' object has no attribute 'dns_create'
```

**Comment by connbrack** [comment]
We have already found the solution, the version number in the [package_versions.txt](https://github.com/linuxserver/docker-swag/blob/master/package_versions.txt) is 0.5, while the latest version is 0.8. by adding the following lines in the docker compose yaml, the DNS certification works

- DOCKER_MODS=linuxserver/mods:universal-package-install
- INSTALL_PIP_PACKAGES=certbot-dns-porkbun==0.8

**Comment by connbrack** [comment]
Ah yes it did, the certbot version in the container is now 2.11.0

**Comment by aptalca** [comment]
Thanks for the confirmation.

So that workaround is probably the best one for you at the moment, but we can't apply that to the image as we don't want certbot downgraded for everyone.

**Comment by connbrack** [comment]
Great, thanks for the update!
