### ISSUE TITLE
Permission problems /var/lib/nginx/tmp

### ISSUE THREAD

**Issue by steamyRayV** [linuxserver/docker-swag#52]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I'm using this with several other linuxserver.io containers. Original issue was getting "error 500" when trying to upload to Nextcloud. Looking through the logs I see that Emby has also had issues with nginx in SWAG.
## Current Behavior

Inside SWAG config directory, /log/nginx/error.log shows permission errors.
2020/12/14 02:19:19 [crit] 576#576: *[sanitized] open() "/var/lib/nginx/tmp/proxy/7/04/0000003047" failed (13: Permission denied) while reading upstream, client: [sanitized], server: emby.*, request: "GET /emby/videos/[sanitized] HTTP/1.1", upstream: "[sanitized]", host: "[sanitized]"
2020/12/19 23:32:50 [crit] 455#455: *[sanitized] open() "/var/lib/nginx/tmp/client_body/0000003648" failed (13: Permission denied), client: [sanitized], server: nextcloud.*, request: "PUT /remote.php/dav/files/[sanitized] HTTP/1.1", host: "[sanitized]"
## Steps to Reproduce

I went inside the container and did "chmod 777 /var/lib/nginx/tmp -R" and that has corrected my issue but I'm not sure if this causes a seperate security issue and it won't survive a container update.
For a rundown of the original permissions from inside the container:
root@[sanitized]:/var/lib/nginx/tmp# ls -l
total 20
drwxr-xr-x 2 xfs xfs  4096 Dec 20 01:48 client_body
drwx------ 2 xfs root 4096 Dec 20 01:48 fastcgi
drwx------ 2 xfs root 4096 Dec 20 01:48 proxy
drwx------ 2 xfs root 4096 Dec 20 01:48 scgi
drwx------ 2 xfs root 4096 Dec 20 01:48 uwsgi
root@[sanitized]:/var/lib/nginx/tmp# ps aux | grep "nginx: worker process"
xfs        455  0.0  0.0 179816  9780 ?        S    01:48   0:00 nginx: worker process
xfs        456  0.0  0.0 179796  9780 ?        S    01:48   0:00 nginx: worker process
xfs        457  0.0  0.0 180200  9772 ?        S    01:48   0:00 nginx: worker process
xfs        458  0.0  0.0 180096  9728 ?        S    01:48   0:00 nginx: worker process
root       488  0.0  0.0   1580     4 pts/0    S+   01:51   0:00 grep nginx: worker process

As you can see I've set the user to 33:33 in the docker command.

Sorry in advance if this is obviously my fault, I'm learning. Thanks for all these containers, linuxserver.io is amazing.
Thanks.

## Environment
**OS:** Ubuntu 16.04.7 LTS
**CPU architecture:** x86_64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

#SWAG
docker run -d \
  --name=swag \
  --net=[sanitized] \
  -e PUID=33 \
  -e PGID=33 \
  -e TZ=America/New_York \
  -e URL=[sanitized] \
  -e SUBDOMAINS=wildcard \
  -e VALIDATION=duckdns \
  -e DUCKDNSTOKEN=[sanitized] \
  -e EMAIL=[sanitized] \
  -p 443:443 \
  -p 80:80 \
  -v /home/[sanitized]/swag:/config \
  --restart unless-stopped \
  linuxserver/swag

**Comment by aptalca** [comment]
See here: https://github.com/linuxserver/docker-letsencrypt/issues/67#issuecomment-382715473

**Comment by steamyRayV** [comment]
I see. Thank you, and apologies for rehashing a known issue. Am I understanding correctly that my options are to upgrade the Ubuntu host (my kernel is the latest for 16,04) or share a volume to the container to hold the tmp folder?

I'm not confident I have this right, but I added the following to my Docker run command for SWAG:     -v /home/user/swag/tmp:/var/lib/nginx/tmp \
Thanks again.

**Comment by steamyRayV** [comment]
Seems to be good to go!
