### ISSUE TITLE
Lets Encrypt recommendations

### ISSUE THREAD

**Issue by jabcreations** [linuxserver/docker-swag#53]
Hi,
I came across your post on Stack about your Lets Encrypt trouble. I use it for my web platform and it works great. I can't directly help you though I can recommend testing out whatever you're working on with the third party validation services that work on my platform. The ones listed provide actual useful insight and aren't skin deep or pointless and I hope will help you clean up whatever is broken by giving you some insight that you may not yet have access to or whatever. Not intended at all for self-promotion so please feel free to delete this "bug report". If you have a question about one of the services post and I will try to help though I'm mostly ignoring email while working on building my own email so it might take a few days. Good luck!

https://www.jabcreations.com/performance/#third-parties

**Comment by nemchik** [comment]
I'm not entirely sure what you're saying here. Was your post meant to be directed at us (lsio staff)? Or meant to be a reply to a user who left a comment or posted somewhere else?

**Comment by jabcreations** [comment]
No idea the size of this GIT and how many folks are working on it.

Here is the original Stack. I figured posting a ton of links on Stack would get it deleted before the OP saw it so this way the links could get collected and then the thread deleted thus at least serving the purpose of helping someone else.

https://stackoverflow.com/questions/65251339/letsencrypt-dosent-recogonize-my-domain-name
