### ISSUE TITLE
[Feature Request] NTLM Support

### ISSUE THREAD

**Issue by Nonobis** [linuxserver/docker-swag#64]
## Desired Behavior
Could you add this NTLM Plugin in Swag ? I want to make reverse proxy for my self hosted DevOps Server (Express) but the free version of nginx doesn't support NTLM authnetication witouth a plugins.

https://github.com/gabihodoroaga/nginx-ntlm-module

Thank you

## Current Behavior
NTLM authentication not working

## Alternatives Considered
None ... Maybe i will cry ... ^^

**Comment by j0nnymoe** [comment]
Unless this is something that is provided via the alpine packages, It's not something we will include.

**Comment by aptalca** [comment]
Also, the readme for the plugin says not to use it in production

**Comment by Nonobis** [comment]
ok, i understand .... how can i include manually a plugin with swag ? I don't care about 'production' it's only for accessing my self hosted devops when i am outsite. I will use https and authelia

**Comment by aptalca** [comment]
You'll have to compile nginx yourself with that plugin
