### ISSUE TITLE
certbot-dns-hetzner

### ISSUE THREAD

**Issue by Magic01** [linuxserver/docker-swag#65]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Support of the DNS service of hetzner.com as the offer a free of charge service
There is blog article on https://community.hetzner.com/tutorials/letsencrypt-dns
And if I understood everything correct here it seems as if there is also a usable plugin at 
https://github.com/ctrlaltcoop/certbot-dns-hetzner

## Current Behavior
no support of hetzner.com as far as I understood

**Comment by aptalca** [comment]
@Magic01 can you give this build a try? `lsiodev/swag:1.11.0-pkg-f63d4034-dev-6f25f82996e09d7af3e210afadfc9084fb1c34cf`

Just replace `ghcr.io/linuxserver/swag` with the above, set DNSPLUGIN to `hetzner` and enter your api key into hetzner.ini

Once you confirm it works, we'll merge to the main repo

Thanks

**Comment by Magic01** [comment]
@aptalca Hi, I can confirm it works.

Many Thanks!
