### ISSUE TITLE
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.

### ISSUE THREAD

**Issue by spicerackk** [linuxserver/docker-swag#68]
# Expected Behavior
Certificates would be fetched and NGINX would start

# Current Behavior
Telling me that my credentials for cloudflare.ini are incorrect

# Steps to Reproduce
1. Remove all files and folders for swag container
2. Run `docker-compose up -d swag`
3. Start swag
4. error shows up.

# Environment
**OS:** Windows 10 **CPU architecture:** x86_64 **How docker service was installed:** Docker desktop

# Command used to create docker container (run/create/compose/screenshot)**
`docker-compose up -d swag`

# Docker logs
```Using Let's Encrypt as the cert provider

SUBDOMAINS entered, processing

Wildcard cert for thespicefiles.com will be requested

E-mail address entered: email@email.com

dns validation via cloudflare plugin is selected

Generating new certificate

Saving debug log to /var/log/letsencrypt/letsencrypt.log

Plugins selected: Authenticator dns-cloudflare, Installer None

Requesting a certificate for *.domain.com and domain.com

An unexpected error occurred:

There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: *.domain.com,domain.com: see https://letsencrypt.org/docs/rate-limits/

Please see the logfiles in /var/log/letsencrypt for more details.

ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```

I have verified my credentials are correct, even going as far as changing my CF API Key. 

Things I have tested:

- commenting out the username/global API key lines and using my generated zone token
- using generated zone token as the global key in the first section
- deleting all folders for swag and re-adding the compose and running again. 

I have checked and I have not exceeded the 50 cert requests in the last week. 

Permissions are fine on all folders, and I really have no idea what is causing the error.

**Comment by j0nnymoe** [comment]
Nothing we can do about the `There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: *.domain.com,domain.com: see https://letsencrypt.org/docs/rate-limits/`.

You must've triggered something at LetsEncrypt for this to show.

**Comment by j0nnymoe** [comment]
You should be able to use `STAGING=true` to test your config so at least you know it will work once the rate limit clears.

**Comment by spicerackk** [comment]
ah ok will try that, thank you. I did check crt.sh and it showed only a handful of certs pulled in the last week or so, but will try staging to see what comes back!
