### ISSUE TITLE
Mock https certificate

### ISSUE THREAD

**Issue by cdalexndr** [linuxserver/docker-swag#71]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Some env variable that disables cert validation.
This is useful for testing purposes where a valid cert is not required.

## Current Behavior
A valid certificate validation method is required or else nginx doesn't start:
`ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container`

## Alternatives Considered
Replacing init files with custom ones that avoid cert validation.

**Comment by aptalca** [comment]
If you don't want certs, you can use our nginx image, which is almost the same as this but without certbot and fail2ban

**Comment by cdalexndr** [comment]
Not quite the same
```
nginx: [emerg] open() "/config/nginx/proxy.conf" failed (2: No such file or directory) in /config/nginx/site-confs/default:30
```

**Comment by aptalca** [comment]
There is a mod for it

**Comment by cdalexndr** [comment]
@aptalca, container image `ghcr.io/linuxserver/nginx` with `DOCKER_MODS=linuxserver/mods:nginx-proxy-confs`, using `include /config/nginx/proxy.conf;` results in:
`nginx: [emerg] unknown "connection_upgrade" variable`
