### ISSUE TITLE
Enable full webdav support

### ISSUE THREAD

**Issue by trvb** [linuxserver/docker-swag#76]
swag does not include full support for webdav.

------------------------------

## Desired Behavior
The docker image should include the "nginx-mod-http-dav-ext" extension, as the stock dav nginx extension only implements partial support.

## Current Behavior
Cannot have full webdav support with stock image:
`nginx: [emerg] unknown directive "dav_ext_methods" in /config/nginx/site-confs/myconf...`

nginx-dav-ext-module provides the additional implementation and is required for useful configurations. It provides the PROPFIND, OPTIONS, LOCK & UNLOCK dav methods.

## Alternatives Considered
Use limited dav support from stock nginx module.

**Comment by trvb** [comment]
To elaborate about the limited support from the stock dav nginx module: it is impossible to expose a simple webdav file share with it for instance.

Tested with Cyberduck:
> [08/Feb/2021:12:25:07 +0100] "PROPFIND / HTTP/1.1" 405 157 "-" "Cyberduck/7.8.2.34203 (Mac OS X/11.2) (x86_64)"

And with the finder:
> [08/Feb/2021:12:26:27 +0100] "OPTIONS / HTTP/1.1" 405 157 "-" "WebDAVLib/1.3"

The OPTIONS and PROPFIND methods are required to get started.

**Comment by aptalca** [comment]
added in #80
