### ISSUE TITLE
Proxy buffering will crash on big downloads above 1024M

### ISSUE THREAD

**Issue by BrightCandle** [linuxserver/docker-swag#84]
## Expected Behavior
When proxying other sites Swag/nginx should allow through whatever size of download that is supported by the underlying application. It also shouldn't depend on the speed at which that can be read nor be storing large files on the drive in order to buffer those files.

## Current Behavior
Swag/nginx is copying the contents of the file as fast as the backend server can provide and then serving to the customer up to a limit of 1024M at which point it fails for the customer, but it reads the backend file fully.

## Steps to Reproduce
1. Setup a proxy to a backend nginx server on the same machine using the standard settings as copied from proxy-conf
2. Have that backend nginx server up a file of over 1024M, say 1.5GB in total size
3. Download the file with Firefox.

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:**
Installed from hub.docker.io.

## Command used to create docker container (run/create/compose/screenshot)
Docker-compose using the following
   image: linuxserver/swag
    container_name: swag
    ports:
      - 443:443
      - 80:80
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/***
      - URL=***
      - SUBDOMAINS=***
      - VALIDATION=http
      - EMAIL=***

## Docker logs
The relevant log entry will show the following is local file system log/nginx/error.log and the message it produces follows this pattern:

2021/02/10 19:00:00 [error] 461#461: *1 upstream prematurely closed connection while reading upstream, client: *.*.*.*, server: *.*, request: "GET /ABIGFILE HTTP/2.0", upstream: "http://*.*.*.*:80/ABIGFILE", host: "*"

## The solution
It seems to be caused by the default setting of http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size it is a problem with buffering. When the nginx is local it reads the backend as fast as it can and fills to the files limit (1024m) and then when the client gets to that point it fails to get the subsequent bytes. Setting this value in the proxy config to 0 along with the other proxy settings stops nginx producing pointless caching files of monster size and peaking out the CPU the moment a request is asked for and allows larger downloads to complete and is what I would recommend be done to fix it.

**Comment by aptalca** [comment]
All those confs are user customizable. Feel free to edit them as you see fit. We provide sample/default confs that work for most common scenarios out of the box, but other folks may have different needs.

**Comment by BrightCandle** [comment]
All I am suggesting is a more universal default given the likely use scenarios of swag. One of the big consequences of the existing setting beyond the fact it crashes in this weird way is that a local process that is proxied (to give it SSL) will be completely read as fast as possible and then the buffer is transferred to the client over time. On anything more than 8x 32KB this results in a file write onto the drive and a corresponding spike in CPU and drive usage as it copies from one process to the other as quick as the CPU will allow. 

I don't think that this is the right default behaviour so if you can change it without breaking peoples installations I would suggest doing so. I have fixed it for our installation but it was a surprising problem to say the least and one setting change would improve the resource utilisation of swag quite noticeably as well as being less surprising for other users.

**Comment by drizuid** [comment]
this is a request specific to a particular user and not the best course of action for the majority. closing this as the OP can do this themselves for this edge case.
