### ISSUE TITLE
Python Errors since rebase to Alpine 3.13

### ISSUE THREAD

**Issue by mvnixon** [linuxserver/docker-swag#85]
Since the rebase to alpine on 3.13 (on both SWAG and a number of other docker containers), on my raspberry pi Docker Swarm, I am seeing a series of errors causing containers to crash, hang, etc.

`
Current thread 0xb6f06390 (most recent call first):,
<no Python frame>,
Fatal Python error: pyinit_main: can't initialize time,
Python runtime state: core initialized,
PermissionError: [Errno 1] Operation not permitted`

Over and over again.

Any ideas on how to fix this?

**Comment by Roxedus** [comment]
Please fill out the issue template, its there for a reason. 

My guess is that you are running into [this](https://docs.linuxserver.io/faq#libseccomp)

**Comment by epleypa** [comment]
> Please fill out the issue template, its there for a reason.
> 
> My guess is that you are running into [this](https://docs.linuxserver.io/faq#libseccomp)

This fixed my issue

**Comment by Roxedus** [comment]
@mvnixon Can you confirm too?

**Comment by raulmorales** [comment]
I have the same problem in the latest version. In linuxserver/swag:version-1.11.0 it works correctly.

My operating system on the Raspberrypi:
Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux

**Log**
`fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
2 errors; 223 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
OK: 217 MiB in 223 packages
[custom-init] memcached: exited 0
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted
Current thread 0xb6f31390 (most recent call first):
<no Python frame>
[services.d] done.
Fatal Python error: pyinit_main: can't initialize time`

**Comment by Roxedus** [comment]
@raulmorales did you check the link I posted?

**Comment by raulmorales** [comment]
Yes, I have reviewed it. I have run  apk add libseccomp

restarted the container, but it keeps showing the same error

**Comment by j0nnymoe** [comment]
@raulmorales try restarting your host.

**Comment by Roxedus** [comment]
@raulmorales is your host Alpine?

**Comment by raulmorales** [comment]
> @raulmorales is your host Alpine?

yes, it's

**Comment by Roxedus** [comment]
@raulmorales so you installed it in the container? It needs to be up to date on the host

**Comment by raulmorales** [comment]
Sorry, I have followed the link, executed the following on the host

wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb

restarted and now it works

Thank you very much

**Comment by glensc** [comment]
Can confirm that using the older image `ghcr.io/linuxserver/swag:version-1.11.0` works for me:
- https://github.com/linuxserver/docker-swag/issues/85#issuecomment-778401171


My host system is Rasbian/10:

```
Sat Jun  8 03:04:58 2019 libseccomp2_2.3.3-4_armhf
```

**Comment by j0nnymoe** [comment]
@glensc so update your libseccomp2 and you'll be able to use latest.

**Comment by glensc** [comment]
@j0nnymoe but this means that this issue has to stay open forever (err, for quite long), as the patching is needed on the HOST SYSTEM. And Debian/10 is up to date on its own.

Perhaps a note to swag readme needed for this problem as it's common.

**Comment by j0nnymoe** [comment]
It's actually only an issue with armhf platforms. It's in our docs site: https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal .

So once you patch your "HOST SYSTEM" it'll all be working again :)

**Comment by Roxedus** [comment]
> Perhaps a note to swag readme needed for this problem as it's common.

We have implemented a banner in the container logs that notifies about this.
