### ISSUE TITLE
upstream bug with libmaxminddb

### ISSUE THREAD

**Issue by derekpurdy** [linuxserver/docker-swag#86]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Should start cleanly without error

## Current Behavior
libmaxminddb does not create the conf file "/etc/conf.d/libmaxminddb"

## Steps to Reproduce
1. Create docker from Template
2. Add ENV Variable called "MAXMINDDB_LICENSE_KEY"
3. Start new Docker container

## Environment
Installed from Unraid

## Command used to create docker container (run/create/compose/screenshot)
created with unraid

## Docker logs
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=99
PGID=100
TZ=America/New_York
URL=REDACTED
SUBDOMAINS=REDACTED
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=true
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=cloudflare
EMAIL=REDACTED
STAGING=false

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Only subdomains, no URL in cert
Sub-domains processed are: -d REDACTED
E-mail address entered: REDACTED
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
sed: /etc/conf.d/libmaxminddb: No such file or directory
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing...
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 70-templates: executing...
[cont-init.d] 70-templates: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Server ready

ticket created on request from aptalca on Discord Server.

**Comment by aptalca** [comment]
Reported upstream: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12420

**Comment by aptalca** [comment]
fixed in https://github.com/linuxserver/docker-swag/commit/2988ac4a5fa49fdccf80cdd2a2141561438a8ce3

**Comment by jkossis** [comment]
+ 1 in terms of having this issue as well. Sounds like a regression that has cropped up.
