### ISSUE TITLE
File globbing causes problems with editor backups

### ISSUE THREAD

**Issue by glensc** [linuxserver/docker-swag#90]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

---- 

It's a known problem if you glob files with `*` you end up matching unwanted backup files.
Some tools have workaround the problem by adding blacklists, i.e `*.bak`, `*.orig`, ...
A more fool-proof situation is to always use "extension", i.e glob `*.conf`.

I've edited confs/default, and the editor created a backup file `default~`. Some other editors could create `.bak` files, even some other editors create `.swp` files.

------------------------------

## Steps to Reproduce

1. `cp config/nginx/site-confs/default config/nginx/site-confs/default~`
2. `docker-compose up -d`
3.
4.

## Environment
**OS:**
**CPU architecture:** arm32/arm64
**How docker service was installed:**

## Docker logs

```
swag    | Server ready
swag    | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /config/nginx/site-confs/default~:7
swag    | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /config/nginx/site-confs/default~:7
...
```

**Comment by glensc** [comment]
Actually, The other files are globbed like this, using *.conf pattern, somewhy site-confs are wildcard globbed. 

The fix is actually pretty simple:

```diff
--- swag/config/nginx/nginx.conf~    2021-02-19 19:48:40.000000000 +0200
+++ swag/config/nginx/nginx.conf    2021-02-19 20:11:03.701331399 +0200
@@ -84,7 +84,7 @@
     # Virtual Host Configs
     ##
     include /etc/nginx/conf.d/*.conf;
-    include /config/nginx/site-confs/*;
+    include /config/nginx/site-confs/*.conf;
     #Removed lua. Do not remove this comment

     ##
(END)
```

**Comment by glensc** [comment]
Perhaps a backward compatible variant be:


```diff
--- swag/config/nginx/nginx.conf~    2021-02-19 20:12:59.000000000 +0200
+++ swag/config/nginx/nginx.conf    2021-02-19 20:13:02.448681188 +0200
@@ -84,7 +84,8 @@
     # Virtual Host Configs
     ##
     include /etc/nginx/conf.d/*.conf;
-    include /config/nginx/site-confs/*;
+    include /config/nginx/site-confs/default;
+    include /config/nginx/site-confs/*.conf;
     #Removed lua. Do not remove this comment

     ##
(END)
```

**Comment by nemchik** [comment]
This would be a breaking change for existing users who may have `site-confs` named for the FQDN the config is made for. For example if someone hosts multiple web sites and makes one config for each and names them by the FQDN (ex: `www.mysite.com`) and we apply this change it could require those users to do some renaming.

Editors leaving behind files is not something we can account for since every editor does this differently.

You are free to modify your own `nginx.conf` for your needs and those changes will be persistent through upgrades of our image. I just don't think we'd want to roll this out for everyone who uses the image.

**Comment by glensc** [comment]
> This would be a breaking change 

I was thinking about this, but isn't `config/` populated only when it's empty? so it will not affect existing users, but only users who start from scratch?

> Editors leaving behind files is not something we can account for since every editor does this differently.

I disagree. Can do something about it. Use extension when globbing.

**Comment by Roxedus** [comment]
> but isn't `config/` populated only when it's empty

No. You get new proxy-confs and fail2ban config as they change. We also sed some files to support downstream changes.
