### ISSUE TITLE
Can not upload files larger than 10Mb using WebDav 

### ISSUE THREAD

**Issue by Exist2Resist** [linuxserver/docker-swag#91]
I am trying to upload a file size no more than `150 Mb` in size. 
Nginx comes back with `client intended to send too large body:` error message.
I increased the `client_max_body_size 10G;` but I still keep getting that error. 
As a matter of fact I tried using several different file sizes in the setting and all yielded the same result. 
When I bypass SWAG on the local network and connect to the local IP of the server/container the uploads work fine. 

I am **able** to upload large file sizes via the web interface. This only does not work when using WedDav

## Expected Behavior
Upload file size over 10mb to my nextcloud instance using webdav from a backup application.
When I click upload in SwiftBackup application it should upload the files to my Nextcloud server. 

## Current Behavior
When I upload any file using webdav that is over 10mb in size I get:
```
StreamResetException: stream was reset: NO_ERROR
```
I am able to successfully upload files if I bypass SWAG and connect to forwarded local IP of the container on unRAID. 

## Steps to Reproduce

1. Install Swift Backup
2. Connect Swift Bakckup to Nextcloud
3. Backup application and select cloud destination.
4. Run Backup
5. Backup errors out on upload with: StreamResetException: stream was reset: NO_ERROR

## Environment
**OS:**
unRAID
**CPU architecture:** x86_64/arm32/arm64
x86_64
**How docker service was installed:**
From official docker repo using linuxserver.io docker template

## Command used to create docker container (run/create/compose/screenshot)
Used docker template. 

## Docker logs
# Nginx errror.log
```
2021/02/19 11:47:17 [error] 490#490: *202 client intended to send too large body: 60250193 bytes, client: 192.168.1.1, server: cloud.*, request: "PUT /remote.php/webdav/Swift_Backup/Swift%20Backup%20(c73cc6735395862c)/Pixel%203%20XL/com.azure.authenticator.app%20(Pixel%203%20XL) HTTP/2.0", host: "xxxxxx.xxxxxxx.duckdns.org"
```
# nextcloud subdomain conf
```
# make sure that your dns has a cname set for nextcloud
# assuming this container is called "letsencrypt", edit your nextcloud container's config
# located at /config/www/nextcloud/config/config.php and add the following lines before the ");":
#  'trusted_proxies' => ['letsencrypt'],
#  'overwrite.cli.url' => 'https://nextcloud.your-domain.com/',
#  'overwritehost' => 'nextcloud.your-domain.com',
#  'overwriteprotocol' => 'https',
#
# Also don't forget to add your domain name to the trusted domains array. It should look somewhat like this:
#  array (
#    0 => '192.168.0.1:444', # This line may look different on your setup, don't modify it.
#    1 => 'nextcloud.your-domain.com',
#  ),

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    #HTTP Strict Transport Security
    add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;   
    server_name cloud.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 10G;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $protocol https;
        set $upstream_nextcloud 192.168.1.151;
        set $nc_port 448;
        proxy_max_temp_file_size 2048m;
        proxy_pass $protocol://$upstream_nextcloud:$nc_port;
        proxy_ssl_session_reuse off;
    }
}
```

# PHP config on nextcloud

```
{
    "system": {
        "loglevel": 0,
        "overwriteprotocol": "https",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.151:448",
            "cloud.domain.domain.org"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.7.1",
        "overwrite.cli.url": "https:\/\/192.168.1.151:448",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "maintenance": false,
        "has_rebuilt_cache": true
    }
}
root@a9a6a87c6cc9:/#
```

**Comment by nemchik** [comment]
The default we ship is
https://github.com/linuxserver/docker-swag/blob/79d8ff03782b46c33fb1dffc3fbc1528c89d69df/root/defaults/nginx.conf#L20
inside the `http` block, and
https://github.com/linuxserver/docker-swag/blob/79d8ff03782b46c33fb1dffc3fbc1528c89d69df/root/defaults/default#L41
inside the main `server` block, however it appears we may also want to ship this in the proxy config files https://github.com/linuxserver/reverse-proxy-confs/blob/master/nextcloud.subdomain.conf.sample (inside the `server` block) and https://github.com/linuxserver/reverse-proxy-confs/blob/master/nextcloud.subfolder.conf.sample (inside the `location` blocks). Would you try setting all your `client_max_body_size` back to `0` (so it reads `client_max_body_size 0;`) and add `client_max_body_size 0;` inside the server block for the proxy config if you're using the subdomain proxy, or the location blocks if you're using the subfolder proxy.

Please let us know if that makes any difference.

p.s. we use `0` which is explained in the docs http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
> Setting _size_ to 0 disables checking of client request body size.
which should allow requests of any size.

**Comment by nemchik** [comment]
I realized after submitting my first comment that we actually already ship
https://github.com/linuxserver/reverse-proxy-confs/blob/f5f4f8c54424ee2c0cf0eb38b32a208df0540e27/nextcloud.subdomain.conf.sample#L24
inside the `server` block for the proxy, so this should be all that's needed.

**Comment by Exist2Resist** [comment]
Yeah and that's what was set when the failures to upload happened, it was set to `0`
I changed it to '10G' because when I searched online for a solution to this problem, the online community says change this value to a desired size. 

When I add it to the server block as well I get.
```
nginx: [emerg] "client_max_body_size" directive is duplicate in /config/nginx/proxy-confs/nextcloud.subdomain.conf:28
```

**Comment by nemchik** [comment]
`0` means unlimited. You shouldn't need to set a specific size.

**Comment by Exist2Resist** [comment]
That's fair, but it's still timing out. Something is complaining about the file size being too large for the proxy.

**Comment by Exist2Resist** [comment]
Any update on this? 
What can I try or where should I look?

**Comment by tobbenb** [comment]
Is the log mentioning any outdated files?

**Comment by Exist2Resist** [comment]
All I see in the NGINX log is `too large body` messages...  
```2021/02/19 11:47:17 [error] 490#490: *202 client intended to send too large body: 60250193 bytes, client: 192.168.1.1, server: cloud.*, request: "PUT /remote.php/webdav/Swift_Backup/Swift%20Backup%20(c73cc6735395862c)/Pixel%203%20XL/com.azure.authenticator.app%20(Pixel%203%20XL) HTTP/2.0", host: "xxxxxx.xxxxxxx.duckdns.org"
```
Outside of that there are no other errors in any other logs in nextcloud. 
Which is odd because I successfully uploaded files about 400 mb in size via the web interface. 
It seems like webdav may need a separate configuration in the nginx config, maybe?

Can you elaborate on outdated files, what do you mean by that?

**Comment by tobbenb** [comment]
That would have been in the container log, but I see that we haven't implemented the same check in nextcloud as in swag, so it will not spit out outdated config files.
You should be able to delete the default nginx config and restart the container to get the latest version.
You should also check swags container log in case it mentions any outdated files.

**Comment by Exist2Resist** [comment]
> That would have been in the container log, but I see that we haven't implemented the same check in nextcloud as in swag, so it will not spit out outdated config files.
> You should be able to delete the default nginx config and restart the container to get the latest version.
> You should also check swags container log in case it mentions any outdated files.

The nextcloud container is brand new, fresh pull and database, etc. 
With SWAG it is not the case. 

Are you talking about the swag nginx configs, delete those?

**Comment by tobbenb** [comment]
We have updated the container since you opened the issue, so if you didn't start with a new fresh appdata, then please delete the default file in nextcloud.

Then you should take a look in the swag log to see if it mentions any outdated files and if it does, delete them and restart swag.

**Comment by Exist2Resist** [comment]
OK will do and report back. 

Thanks

**Comment by Exist2Resist** [comment]
Deleting and recreating the config worked, I can now upload via webdav. 
It also improved the overall performance of the nextcloud instance. 

Thanks
