### ISSUE TITLE
Add rdns ngnix module

### ISSUE THREAD

**Issue by blademckain** [linuxserver/docker-swag#96]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Add the [rdns module for ngnix](http://www.nginx.com/nginx-wiki/build/dirhtml/modules/rdns/)
------------------------------

## Desired Behavior
Having the ability to block / enable only some ip related to dns names. For example, allow entry only to calls from aws.amazon.com

**Comment by Roxedus** [comment]
This module is not a mod in the [Alpine](https://pkgs.alpinelinux.org/packages?name=nginx-mod*&branch=v3.13&arch=x86_64) repos.

**Comment by Ruvetuve** [comment]
Is their any other way to resolve DNS, e.g. allowing your duck dns for a particular site so you are not blocked from your site if your home ip changes?
