### ISSUE TITLE
Hope to add support for dnspod

### ISSUE THREAD

**Issue by piloer** [linuxserver/docker-swag#98]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Hope to add support for dnspod
## Current Behavior

![image](https://user-images.githubusercontent.com/34529215/110251402-39302300-7fbb-11eb-91a1-a9ac3f8b0a3d.png)

## Alternatives Considered

I tried running "pip3 install certbot-dns-dnspod inside the container and adding the dnspod key to dnspod.ini in the dns-conf folder, then restarting the container, but it didn't work.

**Comment by iujmnb98** [comment]
Hope we can have dnspod support as soon as possible.Thanks.
